// frontend2/components/whatsapp/LabelFormModal.vue
<template>
  <Teleport to="body">
    <div v-if="open" class="label-form-overlay" @click.self="$emit('cancel')">
      <div class="label-form-modal" role="dialog" aria-modal="true" :aria-label="title">
        <header class="label-form-header">
          <button type="button" class="label-form-close" aria-label="Fechar" @click="$emit('cancel')">
            <X class="label-form-close-icon" />
          </button>
          <h2 class="label-form-title">{{ title }}</h2>
        </header>

        <form class="label-form-body" @submit.prevent="onSubmit">
          <div class="label-form-field-row">
            <WhatsappLabelTagIcon :color-hex="previewColorHex" large />
            <label class="label-form-field">
              <span class="label-form-field-label">Etiqueta</span>
              <input
                v-model="localName"
                type="text"
                class="label-form-input"
                maxlength="80"
                required
                autofocus
                placeholder="Etiqueta"
              />
            </label>
          </div>

          <p v-if="error" class="label-form-error">{{ error }}</p>

          <footer class="label-form-footer">
            <button type="button" class="label-form-btn label-form-btn--ghost" @click="$emit('cancel')">
              Cancelar
            </button>
            <button
              type="submit"
              class="label-form-btn label-form-btn--primary"
              :disabled="saving || !localName.trim()"
            >
              <Loader v-if="saving" class="spin label-form-btn-icon" />
              Salvar
            </button>
          </footer>
        </form>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { X, Loader } from 'lucide-vue-next'
import WhatsappLabelTagIcon from './WhatsappLabelTagIcon.vue'
import { resolveLabelColorHex, WA_LABEL_COLOR_HEX } from '~/composables/whatsapp/useWhatsappLabels.js'

const props = defineProps({
  open: { type: Boolean, default: false },
  saving: { type: Boolean, default: false },
  error: { type: String, default: '' },
  label: { type: Object, default: null },
})

const emit = defineEmits(['cancel', 'save'])

const localName = ref('')

const title = computed(() => (props.label?.id ? 'Editar etiqueta' : 'Adicionar etiqueta'))

const previewColorHex = computed(() => {
  if (props.label?.colorHex) return resolveLabelColorHex(props.label)
  return WA_LABEL_COLOR_HEX[2]
})

watch(
  () => [props.open, props.label],
  () => {
    if (!props.open) return
    localName.value = String(props.label?.name || '').trim()
  },
  { immediate: true },
)

const onSubmit = () => {
  const name = localName.value.trim()
  if (!name) return
  emit('save', {
    labelid: props.label?.id ? String(props.label.id) : 'new',
    name,
    color: props.label?.color ?? 2,
  })
}
</script>

<style scoped>
.label-form-overlay {
  position: fixed;
  inset: 0;
  z-index: 10080;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px 16px;
  background: rgba(11, 20, 26, 0.45);
}

.label-form-modal {
  width: min(100%, 440px);
  background: #fff;
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(11, 20, 26, 0.18);
}

.label-form-header {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 18px 20px 8px;
}

.label-form-close {
  width: 36px;
  height: 36px;
  border: none;
  border-radius: 999px;
  background: transparent;
  color: #54656f;
  cursor: pointer;
}

.label-form-close:hover {
  background: rgba(11, 20, 26, 0.06);
}

.label-form-close-icon {
  width: 20px;
  height: 20px;
}

.label-form-title {
  margin: 0;
  font-size: 1.05rem;
  font-weight: 500;
  color: #111b21;
}

.label-form-body {
  padding: 8px 20px 20px;
}

.label-form-field-row {
  display: flex;
  align-items: flex-end;
  gap: 16px;
}

.label-form-field {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.label-form-field-label {
  font-size: 0.8125rem;
  color: #667781;
}

.label-form-input {
  width: 100%;
  border: none;
  border-bottom: 2px solid #111b21;
  padding: 8px 0 10px;
  font: inherit;
  font-size: 1rem;
  color: #111b21;
  background: transparent;
  outline: none;
}

.label-form-error {
  margin: 12px 0 0;
  color: #ea0038;
  font-size: 0.875rem;
}

.label-form-footer {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding-top: 24px;
}

.label-form-btn {
  min-width: 96px;
  min-height: 40px;
  padding: 0 18px;
  border-radius: 999px;
  border: none;
  font: inherit;
  font-size: 0.9375rem;
  cursor: pointer;
}

.label-form-btn--ghost {
  background: transparent;
  color: #1daa61;
}

.label-form-btn--primary {
  background: #111b21;
  color: #fff;
}

.label-form-btn--primary:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}

.label-form-btn-icon {
  width: 16px;
  height: 16px;
}

.spin {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}
</style>

// frontend/components/whatsapp/panels/LabelFormModal.tsx
'use client'
import { useState, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { X, Loader } from 'lucide-react'
import type { WaLabel } from '@/lib/whatsapp/labels'
import { resolveLabelColorHex, WA_LABEL_COLOR_HEX } from '@/lib/whatsapp/labels'
import styles from './LabelFormModal.module.scss'

function LabelTagIconLarge({ colorHex }: { colorHex: string }) {
  return (
    <svg width="48" height="34" viewBox="0 0 48 34" aria-hidden="true" className={styles.tagIcon}>
      <path
        fill={colorHex || '#99b6c1'}
        d="M3 3C3 2.17 3.67 1.5 4.5 1.5H24c.6 0 1.15.24 1.57.66l16.5 13.7a2.03 2.03 0 0 1 0 3.08l-16.5 13.7c-.42.42-.97.66-1.57.66H4.5A3 3 0 0 1 1.5 31V3z"
      />
    </svg>
  )
}

interface Props {
  open: boolean
  saving: boolean
  error: string
  label: WaLabel | null
  onCancel: () => void
  onSave: (payload: { labelid: string; name: string; color: number }) => void
}

export function LabelFormModal({ open, saving, error, label, onCancel, onSave }: Props) {
  const [name, setName] = useState('')

  useEffect(() => {
    if (!open) return
    setName(String(label?.name || '').trim())
  }, [open, label])

  const previewColorHex = label?.colorHex
    ? resolveLabelColorHex(label as unknown as Record<string, unknown>)
    : WA_LABEL_COLOR_HEX[2]

  const title = label?.id ? 'Editar etiqueta' : 'Adicionar etiqueta'

  if (!open || typeof document === 'undefined') return null

  return createPortal(
    <div className={styles.overlay} onClick={(e) => e.target === e.currentTarget && onCancel()}>
      <div className={styles.modal} role="dialog" aria-modal="true" aria-label={title}>
        <header className={styles.header}>
          <button type="button" className={styles.closeBtn} aria-label="Fechar" onClick={onCancel}>
            <X size={20} />
          </button>
          <h2 className={styles.title}>{title}</h2>
        </header>

        <form className={styles.body} onSubmit={(e) => { e.preventDefault(); if (name.trim()) onSave({ labelid: label?.id ? String(label.id) : 'new', name: name.trim(), color: label?.color ?? 2 }) }}>
          <div className={styles.fieldRow}>
            <LabelTagIconLarge colorHex={previewColorHex} />
            <label className={styles.field}>
              <span className={styles.fieldLabel}>Etiqueta</span>
              <input
                className={styles.input}
                type="text"
                maxLength={80}
                required
                autoFocus
                placeholder="Etiqueta"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </label>
          </div>

          {error && <p className={styles.error}>{error}</p>}

          <footer className={styles.footer}>
            <button type="button" className={`${styles.btn} ${styles.btnGhost}`} onClick={onCancel}>
              Cancelar
            </button>
            <button
              type="submit"
              className={`${styles.btn} ${styles.btnPrimary}`}
              disabled={saving || !name.trim()}
            >
              {saving && <Loader size={16} className={styles.spinner} />}
              Salvar
            </button>
          </footer>
        </form>
      </div>
    </div>,
    document.body,
  )
}
