// expo-app/src/components/dieta/DiaryDatePicker.tsx
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { CalendarDays } from 'lucide-react-native';
import DiaryCalendarSheet from '@/components/dieta/DiaryCalendarSheet';
import { useDiaryDate } from '@/hooks/useDiaryDate';
import {
  diaryDateChipOffset,
  formatDiaryDateLabel,
  formatDiaryDatePillLabel,
} from '@/lib/diary-date';
import { colors, fonts, radii } from '@/theme/tokens';

type Props = {
  /** `chips` = Hoje/Ontem/Anteontem + calendário. `pill` = só data centralizada (Dieta). */
  variant?: 'chips' | 'pill';
  /** Remove espaçamento extra quando a pill fica ao lado de outro botão. */
  inline?: boolean;
};

export default function DiaryDatePicker({ variant = 'chips', inline = false }: Props) {
  const { selectedDateKey, setDateOffset, setDateKey, diaryDateOptions, isToday } = useDiaryDate();
  const [calendarOpen, setCalendarOpen] = useState(false);

  const selectedOffset = useMemo(
    () => diaryDateChipOffset(selectedDateKey),
    [selectedDateKey],
  );

  const calendarActive = selectedOffset == null;
  const pillLabel = formatDiaryDatePillLabel(selectedDateKey);
  const filtered = !isToday;

  if (variant === 'pill') {
    return (
      <>
        <View style={[styles.pillWrap, inline && styles.pillWrapInline]}>
          <Pressable
            style={[styles.pillBtn, filtered && styles.pillBtnFiltered]}
            accessibilityRole="button"
            accessibilityLabel={`Dia do consumo: ${pillLabel}`}
            onPress={() => setCalendarOpen(true)}
          >
            <CalendarDays
              color={filtered ? '#fff' : colors.primaryDark}
              size={14}
              strokeWidth={2}
            />
            <Text style={[styles.pillLabel, filtered && styles.pillLabelFiltered]} numberOfLines={1}>
              {pillLabel}
            </Text>
          </Pressable>
        </View>

        <DiaryCalendarSheet
          open={calendarOpen}
          selectedDateKey={selectedDateKey}
          onClose={() => setCalendarOpen(false)}
          onSelect={setDateKey}
        />
      </>
    );
  }

  const calendarLabel = calendarActive ? formatDiaryDateLabel(selectedDateKey) : '';

  return (
    <>
      <View style={styles.row} accessibilityRole="tablist">
        {diaryDateOptions.map((option) => {
          const active = selectedOffset === option.offset;
          return (
            <Pressable
              key={option.id}
              style={[styles.chip, active && styles.chipActive]}
              accessibilityRole="tab"
              accessibilityState={{ selected: active }}
              onPress={() => setDateOffset(option.offset)}
            >
              <Text style={[styles.chipText, active && styles.chipTextActive]}>{option.label}</Text>
            </Pressable>
          );
        })}

        <Pressable
          style={[styles.calendarBtn, calendarActive && styles.calendarBtnActive]}
          accessibilityRole="button"
          accessibilityLabel="Escolher data no calendário"
          onPress={() => setCalendarOpen(true)}
        >
          <CalendarDays
            color={calendarActive ? '#fff' : colors.textMuted}
            size={15}
            strokeWidth={2}
          />
          {calendarActive && calendarLabel ? (
            <Text style={styles.calendarLabel} numberOfLines={1}>{calendarLabel}</Text>
          ) : null}
        </Pressable>
      </View>

      <DiaryCalendarSheet
        open={calendarOpen}
        selectedDateKey={selectedDateKey}
        onClose={() => setCalendarOpen(false)}
        onSelect={setDateKey}
      />
    </>
  );
}

const styles = StyleSheet.create({
  pillWrap: {
    alignItems: 'center',
    paddingBottom: 12,
  },
  pillWrapInline: {
    paddingBottom: 0,
    alignItems: 'flex-start',
  },
  pillBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 36,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  pillBtnFiltered: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  pillLabel: {
    fontFamily: fonts.semibold,
    fontSize: 13,
    color: colors.text,
  },
  pillLabelFiltered: {
    color: '#fff',
  },
  row: { flexDirection: 'row', gap: 6, paddingBottom: 12 },
  chip: {
    flex: 1,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  chipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  chipText: { fontFamily: fonts.medium, fontSize: 12, color: colors.textMuted },
  chipTextActive: { color: '#fff' },
  calendarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minWidth: 36,
    minHeight: 36,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
  },
  calendarBtnActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  calendarLabel: {
    maxWidth: 56,
    fontFamily: fonts.semibold,
    fontSize: 11,
    color: '#fff',
  },
});

// frontend2/components/dieta/DiaryDatePicker.vue
<template>
  <div
    class="diary-date-picker"
    :class="{ 'diary-date-picker--pill': variant === 'pill' }"
    role="group"
    aria-label="Dia do consumo"
  >
    <template v-if="variant === 'pill'">
      <button
        type="button"
        class="diary-date-picker__pill"
        :class="{ 'diary-date-picker__pill--filtered': filtered }"
        :aria-label="`Dia do consumo: ${pillLabel}`"
        @click="calendarOpen = true"
      >
        <CalendarDays aria-hidden="true" />
        <span>{{ pillLabel }}</span>
      </button>
    </template>

    <template v-else>
      <button
        v-for="option in diaryDateOptions"
        :key="option.id"
        type="button"
        class="diary-date-picker__chip"
        :class="{ active: selectedOffset === option.offset }"
        @click="selectOffset(option.offset)"
      >
        {{ option.label }}
      </button>

      <button
        type="button"
        class="diary-date-picker__calendar"
        :class="{ active: calendarActive }"
        aria-label="Escolher data no calendário"
        @click="calendarOpen = true"
      >
        <CalendarDays aria-hidden="true" />
        <span v-if="calendarActive" class="diary-date-picker__calendar-label">{{ calendarLabel }}</span>
      </button>
    </template>

    <DiaryCalendarSheet
      :open="calendarOpen"
      :selected-date-key="selectedDateKey"
      @close="calendarOpen = false"
      @select="selectDateKey"
    />
  </div>
</template>

<script setup>
import { CalendarDays } from 'lucide-vue-next'
import {
  DIARY_DATE_OPTIONS,
  diaryDateChipOffset,
  formatDiaryDateLabel,
  formatDiaryDatePillLabel,
} from '~/utils/diary-date'

const props = defineProps({
  /** `chips` = atalhos + calendário. `pill` = só data centralizada (Dieta). */
  variant: {
    type: String,
    default: 'chips',
    validator: (value) => ['chips', 'pill'].includes(value),
  },
})

const { selectedDateKey, setDateOffset, setDateKey, isToday } = useDiaryDate()

const diaryDateOptions = DIARY_DATE_OPTIONS
const calendarOpen = ref(false)

const selectedOffset = computed(() => diaryDateChipOffset(selectedDateKey.value))
const calendarActive = computed(() => selectedOffset.value == null)
const filtered = computed(() => !isToday.value)
const pillLabel = computed(() => formatDiaryDatePillLabel(selectedDateKey.value))

const calendarLabel = computed(() => {
  if (!calendarActive.value) return ''
  return formatDiaryDateLabel(selectedDateKey.value)
})

function selectOffset(offset) {
  setDateOffset(offset)
}

function selectDateKey(dateKey) {
  setDateKey(dateKey)
}
</script>

<style scoped>
.diary-date-picker {
  display: flex;
  gap: 0.375rem;
  padding: 0 0 0.75rem;
}

.diary-date-picker--pill {
  justify-content: center;
}

.diary-date-picker__pill {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.35rem;
  min-height: 2.25rem;
  padding: 0 0.85rem;
  border: 1px solid var(--cf-border, #e2e5e0);
  border-radius: 999px;
  background: #fff;
  color: var(--cf-text, #1c1816);
  font: 600 0.8125rem/1 inherit;
  cursor: pointer;
}

.diary-date-picker__pill svg {
  width: 0.95rem;
  height: 0.95rem;
  color: #798a70;
}

.diary-date-picker__pill--filtered {
  border-color: #798a70;
  background: #798a70;
  color: #fff;
}

.diary-date-picker__pill--filtered svg {
  color: #fff;
}

.diary-date-picker__chip {
  flex: 1;
  min-height: 2.25rem;
  border: 1px solid var(--cf-border, #e2e5e0);
  border-radius: 999px;
  background: #fff;
  color: #60665e;
  font: 500 0.75rem/1.2 inherit;
  cursor: pointer;
}

.diary-date-picker__chip.active {
  border-color: #798a70;
  background: #798a70;
  color: #fff;
}

.diary-date-picker__calendar {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.25rem;
  min-width: 2.25rem;
  min-height: 2.25rem;
  padding: 0 0.65rem;
  border: 1px solid var(--cf-border, #e2e5e0);
  border-radius: 999px;
  background: #fff;
  color: #60665e;
  font: 600 0.72rem/1 inherit;
  cursor: pointer;
  flex-shrink: 0;
}

.diary-date-picker__calendar svg {
  width: 0.95rem;
  height: 0.95rem;
}

.diary-date-picker__calendar.active {
  border-color: #798a70;
  background: #798a70;
  color: #fff;
}

.diary-date-picker__calendar-label {
  max-width: 4.5rem;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
