// frontend/components/patients/PatientExamesWorkspace.tsx
'use client'

import { useState } from 'react'
import { FlaskConical, MoreVertical } from 'lucide-react'
import { apiFetch } from '@/lib/api'
import type { Exame, PatientUser, PatientProfile } from '@/lib/types'
import { canCompare, formatExameDate, EXAMES_LIMIT } from '@/lib/lab-exams'
import { AnimatedPopover } from '@/components/overlays'
import { ExameEditorModal } from './ExameEditorModal'
import { ExameComparisonPanel } from './ExameComparisonPanel'
import s from './PatientWorkspace.module.scss'
import sx from './PatientExamesWorkspace.module.scss'

function previewText(exame: Exame): string {
  const count = exame?.biomarkers?.length || 0
  const lab = exame?.labName ? ` · ${exame.labName}` : ''
  if (!count) return `Sem biomarcadores${lab}`
  return `${count} biomarcador(es)${lab}`
}

function formatDateTime(value?: string | null): string {
  if (!value) return '—'
  return new Date(value).toLocaleString('pt-BR', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

function statusLabel(status?: string | null): string {
  return status === 'draft' ? 'Rascunho' : 'Registrado'
}

function badgeClass(status?: string | null): string {
  return status === 'draft' ? s.draft : s.completed
}

// ── TileMenu ──────────────────────────────────────────────────────────────────

function TileMenu({ onEdit, onDelete }: { onEdit: () => void; onDelete: () => void }) {
  const [open, setOpen] = useState(false)

  return (
    <AnimatedPopover
      open={open}
      onOpenChange={setOpen}
      align="end"
      contentClassName={s.dropdown}
      trigger={
        <button type="button" className={s.menuBtn} aria-label="Ações">
          <MoreVertical size={15} />
        </button>
      }
    >
      <button
        type="button"
        className={s.dropdownItem}
        role="menuitem"
        onClick={() => { setOpen(false); onEdit() }}
      >
        Editar
      </button>
      <button
        type="button"
        className={`${s.dropdownItem} ${s.danger}`}
        role="menuitem"
        onClick={() => { setOpen(false); onDelete() }}
      >
        Excluir
      </button>
    </AnimatedPopover>
  )
}

// ── PatientExamesWorkspace ────────────────────────────────────────────────────

export type PatientExamesWorkspaceProps = {
  user: PatientUser
  profile?: PatientProfile | null
  onSaved: (updated: PatientUser) => void
}

export function PatientExamesWorkspace({ user, profile: profileProp, onSaved }: PatientExamesWorkspaceProps) {
  const profile = profileProp ?? (user?.patientProfileData as PatientProfile | undefined)
  const [listError, setListError] = useState('')
  const [saving, setSaving] = useState(false)
  const [editorOpen, setEditorOpen] = useState(false)
  const [editorSeed, setEditorSeed] = useState<Exame | null>(null)
  const [selectedIds, setSelectedIds] = useState<string[]>([])
  const [mode, setMode] = useState<'list' | 'compare'>('list')

  const exames: Exame[] = [...(
    Array.isArray(user?.patientProfileData?.exames)
      ? user.patientProfileData!.exames!
      : Array.isArray(profile?.exames)
        ? profile.exames!
        : []
  )].sort((a, b) =>
    String(b.collectedAt || b.createdAt || '').localeCompare(
      String(a.collectedAt || a.createdAt || ''),
    ),
  )

  const canCompareSelected = canCompare(selectedIds)

  function startNew() {
    if (exames.length >= EXAMES_LIMIT) {
      setListError(`Limite de ${EXAMES_LIMIT} registros de exame por paciente.`)
      return
    }
    setListError('')
    setEditorSeed(null)
    setEditorOpen(true)
  }

  function editItem(item: Exame) {
    setListError('')
    setEditorSeed(item)
    setEditorOpen(true)
  }

  function toggleSelected(id: string) {
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((v) => v !== id) : [...prev, id],
    )
  }

  function nextList(nextItem: Exame | null, removeId = ''): Exame[] {
    const source = Array.isArray(user?.patientProfileData?.exames)
      ? user.patientProfileData!.exames!
      : Array.isArray(profile?.exames)
        ? profile.exames!
        : []
    const current = [...source]
    if (removeId) return current.filter((item) => item.id !== removeId)
    if (!nextItem) return current
    const idx = current.findIndex((item) => item.id === nextItem.id)
    if (idx >= 0) { current[idx] = nextItem; return current }
    return [nextItem, ...current].slice(0, EXAMES_LIMIT)
  }

  async function patchExames(list: Exame[]): Promise<PatientUser> {
    const updated = await apiFetch<PatientUser>(`/users/${user.id}`, {
      method: 'PATCH',
      body: JSON.stringify({ patientProfile: { exames: list } }),
    })
    onSaved(updated)
    return updated
  }

  async function handleSave(data: Partial<Exame>, status: 'draft' | 'completed') {
    if (!user?.id) { setListError('Paciente não carregado.'); return }
    setSaving(true)
    setListError('')
    try {
      const item: Exame = {
        title: 'Registro de exame',
        biomarkers: [],
        ...data,
        id: data.id || crypto.randomUUID(),
        status,
        authorName: data.authorName || 'Nutricionista',
        updatedAt: new Date().toISOString(),
        createdAt: data.createdAt || new Date().toISOString(),
      }
      await patchExames(nextList(item))
      setEditorOpen(false)
      if (!selectedIds.includes(item.id)) {
        setSelectedIds((prev) => [...prev, item.id])
      }
    } catch (err: unknown) {
      setListError(
        (err as { data?: { error?: string; message?: string } })?.data?.error ||
        (err as { data?: { message?: string } })?.data?.message ||
        (err as { message?: string })?.message ||
        'Erro ao salvar exame.',
      )
    } finally {
      setSaving(false)
    }
  }

  async function removeItem(id: string) {
    if (!confirm('Excluir este registro de exame?')) return
    setListError('')
    try {
      await patchExames(nextList(null, id))
      setSelectedIds((prev) => prev.filter((v) => v !== id))
    } catch (err: unknown) {
      setListError(
        (err as { message?: string })?.message || 'Erro ao excluir.',
      )
    }
  }

  return (
    <div className={s.pawork}>
      <div className={s.head}>
        <div>
          <h2>Exames laboratoriais</h2>
          <p>{exames.length} registro(s) · compare tendências e insights clínicos</p>
        </div>
        <div className={s.actions}>
          <button
            type="button"
            className={`btn-secondary ${s.btn}`}
            disabled={!canCompareSelected}
            onClick={() => setMode('compare')}
          >
            Comparar selecionados
          </button>
          <button type="button" className={`btn-primary ${s.btn}`} onClick={startNew}>
            + Registro de exame
          </button>
        </div>
      </div>

      {listError && <p className={s.error}>{listError}</p>}

      {mode === 'compare' && canCompareSelected && (
        <div style={{ marginBottom: '0.85rem' }}>
          <ExameComparisonPanel exames={exames} selectedIds={selectedIds} />
        </div>
      )}

      {mode === 'compare' && (
        <button
          type="button"
          className={`btn-secondary ${s.btn}`}
          style={{ marginBottom: '0.85rem' }}
          onClick={() => setMode('list')}
        >
          Voltar para registros
        </button>
      )}

      {mode === 'list' && (
        <>
          {exames.length === 0 ? (
            <div className={s.empty}>
              <FlaskConical size={28} className={s.emptyIcon} />
              <h3>Centralize os exames laboratoriais</h3>
              <p>
                Registre biomarcadores com faixas de referência e compare a evolução entre consultas.
              </p>
              <button type="button" className={`btn-primary ${s.btn}`} onClick={startNew}>
                + Registro de exame
              </button>
            </div>
          ) : (
            <div className={s.list}>
              {exames.map((item) => (
                <article
                  key={item.id}
                  className={`${sx.card}${item.status === 'draft' ? ` ${s.cardDraft}` : ''}${selectedIds.includes(item.id) ? ` ${sx.selected}` : ''}`}
                >
                  <label className={sx.checkbox}>
                    <input
                      type="checkbox"
                      checked={selectedIds.includes(item.id)}
                      onChange={() => toggleSelected(item.id)}
                    />
                    <span className="sr-only">Selecionar para comparação</span>
                  </label>
                  <button type="button" className={s.cardMain} onClick={() => editItem(item)}>
                    <div className={s.cardTop}>
                      <strong className={s.cardTitle}>{item.title}</strong>
                      <span className={`${s.badge} ${badgeClass(item.status)}`}>
                        {statusLabel(item.status)}
                      </span>
                    </div>
                    <p className={s.cardPreview}>
                      {formatExameDate(item.collectedAt)} · {previewText(item)}
                    </p>
                    <small className={s.cardMeta}>
                      Atualizado {formatDateTime(item.updatedAt || item.createdAt)}
                    </small>
                  </button>
                  <div className={s.cardActions}>
                    <TileMenu onEdit={() => editItem(item)} onDelete={() => removeItem(item.id)} />
                  </div>
                </article>
              ))}
            </div>
          )}

          {exames.length > 0 && selectedIds.length === 1 && (
            <p className={sx.hint}>
              Selecione mais um registro para comparar biomarcadores lado a lado.
            </p>
          )}
        </>
      )}

      <ExameEditorModal
        open={editorOpen}
        seed={editorSeed}
        saving={saving}
        onClose={() => setEditorOpen(false)}
        onSave={handleSave}
      />
    </div>
  )
}

// frontend/components/patients/PatientExamesWorkspace.vue
<template>
  <div class="pawork">
    <header class="pawork-history-head">
      <div>
        <h2>Exames laboratoriais</h2>
        <p>{{ exames.length }} registro(s) · compare tendências e insights clínicos</p>
      </div>
      <div class="pawork-history-actions">
        <button
          type="button"
          class="btn-secondary pawork-btn"
          :disabled="!canCompareSelected"
          @click="mode = 'compare'"
        >
          Comparar selecionados
        </button>
        <button type="button" class="btn-primary pawork-btn" @click="startNew">
          + Registro de exame
        </button>
      </div>
    </header>

    <p v-if="listError" class="pawork-error">{{ listError }}</p>

    <PatientExameComparisonPanel
      v-if="mode === 'compare' && canCompareSelected"
      :exames="exames"
      :selected-ids="selectedIds"
      class="pex-workspace-compare"
    />

    <button
      v-if="mode === 'compare'"
      type="button"
      class="btn-secondary pawork-btn pex-back-list"
      @click="mode = 'list'"
    >
      Voltar para registros
    </button>

    <div v-if="mode === 'list'">
      <div v-if="!exames.length" class="pawork-empty">
        <PatientChartEmptyState
          :icon="FlaskConical"
          title="Centralize os exames laboratoriais"
          description="Registre biomarcadores com faixas de referência e compare a evolução entre consultas."
          action-label="+ Registro de exame"
          @action="startNew"
        />
      </div>

      <div v-else class="pawork-list">
        <article
          v-for="item in exames"
          :key="item.id"
          class="pawork-card"
          :class="{ 'pawork-card--draft': item.status === 'draft', 'pawork-card--selected': selectedIds.includes(item.id) }"
        >
          <label class="pex-select">
            <input
              type="checkbox"
              :checked="selectedIds.includes(item.id)"
              @change="toggleSelected(item.id)"
            >
            <span class="sr-only">Selecionar para comparação</span>
          </label>
          <button type="button" class="pawork-card-main" @click="editItem(item)">
            <div class="pawork-card-top">
              <strong>{{ item.title }}</strong>
              <span class="pawork-status" :class="`pawork-status--${item.status || 'completed'}`">
                {{ exameStatusLabel(item.status) }}
              </span>
            </div>
            <p class="pawork-card-preview">
              {{ formatExameDate(item.collectedAt) }} · {{ examePreviewText(item) }}
            </p>
            <small>Atualizado {{ formatDateTime(item.updatedAt || item.createdAt) }}</small>
          </button>
          <div class="pawork-card-actions" @click.stop>
            <SharedCfTileActionsMenu :menu-key="`exame-${item.id}`" class="pawork-card-menu">
              <button type="button" class="cf-tile-actions-item" role="menuitem" @click="editItem(item)">
                Editar
              </button>
              <button
                type="button"
                class="cf-tile-actions-item cf-tile-actions-item--danger"
                role="menuitem"
                @click="removeItem(item.id)"
              >
                Excluir
              </button>
            </SharedCfTileActionsMenu>
          </div>
        </article>
      </div>

      <p v-if="exames.length && selectedIds.length === 1" class="pex-hint">
        Selecione mais um registro para comparar biomarcadores lado a lado.
      </p>
    </div>

    <PatientExameEditorModal
      v-model:open="editorOpen"
      :seed="editorSeed"
      :saving="saving"
      @save="onSave"
    />
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { FlaskConical } from 'lucide-vue-next'
import { authFetchInit, useAuthSession } from '~/composables/useAuthSession.js'
import PatientChartEmptyState from '~/components/patients/PatientChartEmptyState.vue'
import PatientExameComparisonPanel from '~/components/patients/PatientExameComparisonPanel.vue'
import PatientExameEditorModal from '~/components/patients/PatientExameEditorModal.vue'
import { canCompare } from '~/utils/lab-exam-comparison.js'
import {
  EXAMES_LIMIT,
  examePreviewText,
  exameStatusLabel,
  formatExameDate,
  normalizeExame,
  sortExamesByDate,
} from '~/utils/lab-exams.js'

const props = defineProps({
  user: { type: Object, default: null },
  profile: { type: Object, default: () => ({}) },
})

const emit = defineEmits(['saved'])

const apiBase = useApiBase()
const { verifiedUser } = useAuthSession()

const mode = ref('list')
const listError = ref('')
const saving = ref(false)
const editorOpen = ref(false)
const editorSeed = ref(null)
const selectedIds = ref([])

const exames = computed(() => {
  const fromUser = props.user?.patientProfileData?.exames
  const fromProfile = props.profile?.exames
  const list = Array.isArray(fromUser) ? fromUser : (Array.isArray(fromProfile) ? fromProfile : [])
  return sortExamesByDate(list).reverse()
})

const canCompareSelected = computed(() => canCompare(selectedIds.value))

function formatDateTime(value) {
  if (!value) return '—'
  return new Date(value).toLocaleString('pt-BR', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

function toggleSelected(id) {
  if (selectedIds.value.includes(id)) {
    selectedIds.value = selectedIds.value.filter((item) => item !== id)
    return
  }
  selectedIds.value = [...selectedIds.value, id]
}

function startNew() {
  if (exames.value.length >= EXAMES_LIMIT) {
    listError.value = `Limite de ${EXAMES_LIMIT} registros de exame por paciente.`
    return
  }
  listError.value = ''
  editorSeed.value = { type: 'new' }
  editorOpen.value = true
}

function editItem(item) {
  if (!item?.id) return
  listError.value = ''
  editorSeed.value = { type: 'edit', item }
  editorOpen.value = true
}

function nextExamesList(nextItem, removeId = '') {
  const fromUser = props.user?.patientProfileData?.exames
  const fromProfile = props.profile?.exames
  const source = Array.isArray(fromUser) ? fromUser : fromProfile
  const current = Array.isArray(source) ? [...source] : []
  if (removeId) return current.filter((item) => item.id !== removeId)
  const idx = current.findIndex((item) => item.id === nextItem.id)
  if (idx >= 0) {
    current[idx] = nextItem
    return current
  }
  return [nextItem, ...current].slice(0, EXAMES_LIMIT)
}

async function patchExames(nextList) {
  const updated = await $fetch(`${apiBase.value}/users/${props.user.id}`, authFetchInit({
    method: 'PATCH',
    body: {
      patientProfile: {
        exames: nextList,
      },
    },
  }))
  emit('saved', updated)
  return updated
}

async function onSave(payload) {
  if (!props.user?.id) {
    listError.value = 'Paciente não carregado.'
    return
  }
  saving.value = true
  listError.value = ''
  try {
    const item = {
      ...normalizeExame(payload),
      authorName: verifiedUser.value?.name || payload.authorName || 'Nutricionista',
      updatedAt: new Date().toISOString(),
      createdAt: payload.createdAt || new Date().toISOString(),
    }
    await patchExames(nextExamesList(item))
    editorOpen.value = false
    if (!selectedIds.value.includes(item.id)) {
      selectedIds.value = [...selectedIds.value, item.id]
    }
  } catch (err) {
    listError.value = err?.data?.error || err?.data?.message || err?.message || 'Erro ao salvar exame.'
  } finally {
    saving.value = false
  }
}

async function removeItem(id) {
  if (!confirm('Excluir este registro de exame?')) return
  try {
    await patchExames(nextExamesList(null, id))
    selectedIds.value = selectedIds.value.filter((item) => item !== id)
  } catch (err) {
    listError.value = err?.data?.error || err?.message || 'Erro ao excluir.'
  }
}
</script>

<style scoped>
.pex-workspace-compare {
  margin-bottom: 0.85rem;
}

.pex-back-list {
  margin-bottom: 0.85rem;
}

.pawork-card {
  display: grid;
  grid-template-columns: auto minmax(0, 1fr) auto;
  gap: 0.35rem;
  align-items: stretch;
}

.pawork-card--selected {
  outline: 2px solid rgba(139, 150, 124, 0.35);
}

.pex-select {
  display: inline-flex;
  align-items: center;
  padding: 0 0.35rem 0 0.65rem;
}

.pex-select input {
  width: 1rem;
  height: 1rem;
}

.pex-hint {
  margin: 0.75rem 0 0;
  font-size: 0.78rem;
  color: #6b7368;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>
