// frontend/components/patients/PatientPhotosPanel.tsx
'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Camera, X } from 'lucide-react'
import { fetchFoodDiaryPhotos, type PhotoEntry } from '@/lib/patient-chart/evolucao'
import styles from './PatientPhotosPanel.module.scss'

type Props = {
  patientId: string
  compact?: boolean
  limit?: number
}

function formatDate(value?: string | null): string {
  if (!value) return ''
  const date = new Date(`${value}T12:00:00`)
  return date.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })
}

export function PatientPhotosPanel({ patientId, compact = false, limit = 60 }: Props) {
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [photos, setPhotos] = useState<PhotoEntry[]>([])
  const [lightbox, setLightbox] = useState<PhotoEntry | null>(null)

  useEffect(() => {
    setLoading(true)
    setError('')
    fetchFoodDiaryPhotos(patientId, Math.max(limit, 12))
      .then((data) => setPhotos(data))
      .catch((err) => {
        setError(
          (err as { message?: string })?.message || 'Não foi possível carregar as fotos.',
        )
        setPhotos([])
      })
      .finally(() => setLoading(false))
  }, [patientId, limit])

  const visiblePhotos = useMemo(() => photos.slice(0, limit), [photos, limit])

  // Close lightbox on Escape
  useEffect(() => {
    if (!lightbox) return
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setLightbox(null)
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [lightbox])

  // Prevent body scroll when lightbox is open
  useEffect(() => {
    if (lightbox) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
    }
    return () => {
      document.body.style.overflow = ''
    }
  }, [lightbox])

  if (loading) return <div className={styles.loading}>Carregando fotos…</div>
  if (error) return <p className={styles.error}>{error}</p>

  if (!visiblePhotos.length) {
    return (
      <div className={styles.empty}>
        <Camera className={styles.emptyIcon} aria-hidden />
        <p>Nenhuma foto de refeição registrada ainda.</p>
      </div>
    )
  }

  return (
    <div className={styles.root}>
      {compact ? (
        /* TikTok-style vertical feed */
        <div className={styles.tiktok}>
          {visiblePhotos.map((photo, index) => (
            <button
              key={photo.id}
              type="button"
              className={styles.slide}
              onClick={() => setLightbox(photo)}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={photo.imageUrl ?? ''} alt="" loading="lazy" />
              <div className={styles.slideShade} aria-hidden />
              <div className={styles.slideUi}>
                <div className={styles.slideCaption}>
                  <strong>{photo.mealLabel || photo.mealType}</strong>
                  <span>{formatDate(photo.entryDate)}</span>
                </div>
                <div className={styles.slideRail}>
                  {photo.caloriesKcal != null && (
                    <span className={styles.railPill}>
                      <small>kcal</small>
                      {Math.round(photo.caloriesKcal)}
                    </span>
                  )}
                  <span className={styles.railIndex}>
                    {index + 1}/{visiblePhotos.length}
                  </span>
                </div>
              </div>
            </button>
          ))}
        </div>
      ) : (
        /* Standard grid */
        <div className={styles.grid}>
          {visiblePhotos.map((photo) => (
            <button
              key={photo.id}
              type="button"
              className={styles.item}
              onClick={() => setLightbox(photo)}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={photo.imageUrl ?? ''} alt="" loading="lazy" />
              <span className={styles.itemMeta}>
                {photo.mealLabel || photo.mealType}
                <small>{formatDate(photo.entryDate)}</small>
              </span>
            </button>
          ))}
        </div>
      )}

      {/* Lightbox — rendered in-tree (no Teleport needed in React) */}
      {lightbox && (
        <div
          className={styles.lightbox}
          onClick={(e) => {
            if (e.target === e.currentTarget) setLightbox(null)
          }}
          role="dialog"
          aria-modal
          aria-label="Foto ampliada"
        >
          <button
            type="button"
            className={styles.closeBtn}
            aria-label="Fechar"
            onClick={() => setLightbox(null)}
          >
            <X size={18} />
          </button>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={lightbox.imageUrl ?? ''} alt="" />
          <p className={styles.lightboxMeta}>
            {lightbox.mealLabel || lightbox.mealType}
            {' · '}
            {formatDate(lightbox.entryDate)}
            {lightbox.caloriesKcal != null && (
              <> · {Math.round(lightbox.caloriesKcal)} kcal</>
            )}
          </p>
        </div>
      )}
    </div>
  )
}

// frontend/components/patients/PatientPhotosPanel.vue
<template>
  <div class="patient-photos">
    <div v-if="loading" class="patient-photos-loading">Carregando fotos…</div>
    <p v-else-if="error" class="patient-photos-error">{{ error }}</p>
    <p v-else-if="!photos.length" class="patient-photos-empty">
      Nenhuma foto de refeição registrada ainda.
    </p>
    <div v-else class="patient-photos-grid">
      <button
        v-for="photo in photos"
        :key="photo.id"
        type="button"
        class="patient-photos-item"
        @click="openLightbox(photo)"
      >
        <img :src="photo.imageUrl" alt="" loading="lazy" />
        <span class="patient-photos-meta">
          {{ photo.mealLabel || photo.mealType }}
          <small>{{ formatDate(photo.entryDate) }}</small>
        </span>
      </button>
    </div>

    <Teleport to="body">
      <div v-if="lightbox" class="patient-photos-lightbox" @click.self="lightbox = null">
        <button type="button" class="patient-photos-close" aria-label="Fechar" @click="lightbox = null">×</button>
        <img :src="lightbox.imageUrl" alt="" />
        <p class="patient-photos-lightbox-meta">
          {{ lightbox.mealLabel || lightbox.mealType }}
          · {{ formatDate(lightbox.entryDate) }}
          <span v-if="lightbox.caloriesKcal"> · {{ Math.round(lightbox.caloriesKcal) }} kcal</span>
        </p>
      </div>
    </Teleport>
  </div>
</template>

<script setup>
const props = defineProps({
  patientId: { type: String, required: true },
})

const config = useRuntimeConfig()

const loading = ref(true)
const error = ref('')
const photos = ref([])
const lightbox = ref(null)

function authHeaders() {
  const token = import.meta.client ? localStorage.getItem('auth_token') : null
  return token ? { Authorization: `Bearer ${token}` } : {}
}

function formatDate(value) {
  const date = new Date(`${value}T12:00:00`)
  return date.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })
}

function openLightbox(photo) {
  lightbox.value = photo
}

async function loadPhotos() {
  loading.value = true
  error.value = ''
  try {
    const data = await $fetch(`${config.public.apiBase}/patients/${props.patientId}/food-diary/photos`, {
      headers: authHeaders(),
      query: { limit: 60 },
    })
    photos.value = data.photos || []
  } catch (err) {
    error.value = err?.data?.message || 'Não foi possível carregar as fotos.'
    photos.value = []
  } finally {
    loading.value = false
  }
}

watch(() => props.patientId, loadPhotos, { immediate: true })
</script>

<style scoped>
.patient-photos-loading,
.patient-photos-empty,
.patient-photos-error {
  font-size: 0.88rem;
  color: #666;
}

.patient-photos-error {
  color: #c53030;
}

.patient-photos-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(140px, 1fr));
  gap: 0.75rem;
}

.patient-photos-item {
  position: relative;
  aspect-ratio: 1;
  padding: 0;
  border: 1px solid var(--admin-border, #e8ece9);
  border-radius: 12px;
  overflow: hidden;
  background: #f5f5f5;
  cursor: pointer;
}

.patient-photos-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.patient-photos-meta {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  padding: 0.35rem 0.45rem;
  background: linear-gradient(transparent, rgba(0, 0, 0, 0.72));
  color: #fff;
  font-size: 0.68rem;
  font-weight: 600;
  line-height: 1.3;
  text-align: left;
}

.patient-photos-meta small {
  display: block;
  font-weight: 500;
  opacity: 0.9;
}

.patient-photos-lightbox {
  position: fixed;
  inset: 0;
  z-index: 200;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 1.5rem;
  background: rgba(0, 0, 0, 0.88);
}

.patient-photos-lightbox img {
  max-width: min(100%, 520px);
  max-height: 70vh;
  border-radius: 12px;
  object-fit: contain;
}

.patient-photos-lightbox-meta {
  margin: 0.75rem 0 0;
  color: #fff;
  font-size: 0.88rem;
}

.patient-photos-close {
  position: absolute;
  top: 1rem;
  right: 1rem;
  width: 2.25rem;
  height: 2.25rem;
  border: none;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.15);
  color: #fff;
  font-size: 1.35rem;
  cursor: pointer;
}
</style>
