// frontend/components/patients/PatientGoalsPanel.vue
<template>
  <div class="patient-goals-readonly" :class="{ 'patient-goals-readonly--compact': compact }">
    <div v-if="loading" class="patient-goals-state">Carregando metas…</div>
    <p v-else-if="error" class="patient-goals-state patient-goals-state--error">{{ error }}</p>
    <p v-else-if="!goalRows.length" class="patient-goals-state">
      A paciente ainda não registrou metas no app.
    </p>

    <div v-else class="evo-goals">
      <article
        v-for="item in visibleGoalRows"
        :key="item.goal.id"
        class="evo-goal-card"
        :class="`evo-goal-card--${item.goal.id}`"
      >
        <header class="evo-goal-head">
          <div class="evo-goal-head-copy">
            <span class="evo-goal-icon" aria-hidden="true">
              <component :is="goalIcon(item.goal)" class="evo-goal-icon-svg" />
            </span>
            <div>
              <h3>{{ item.goal.label }}</h3>
              <p class="evo-goal-meta">
                <template v-if="item.goal.id === 'food'">
                  Semanal · {{ item.progress }} {{ item.progress === 1 ? 'dia registrado' : 'dias registrados' }}
                </template>
                <template v-else>
                  {{ frequencyLabel(item.goal.frequency) }} · {{ item.progress }} / {{ item.goal.target }} {{ item.goal.unit }}
                </template>
              </p>
            </div>
          </div>
          <span v-if="item.goal.id === 'food'" class="evo-goal-pct evo-goal-pct--count">{{ item.progress }}</span>
          <span v-else class="evo-goal-pct">{{ item.percent }}%</span>
        </header>

        <div class="evo-goal-surface">
          <div class="evo-goal-widget">
            <EvolucaoWaterBottle
              v-if="item.goal.type === 'water'"
              readonly
              :current="item.progress"
              :target="item.goal.target"
            />

            <EvolucaoFoodPlate
              v-else-if="item.goal.id === 'food'"
              readonly
              :selected-days="foodSelectedDays"
              :today-index="todayWeekdayIndex"
            />

            <EvolucaoExerciseArm
              v-else-if="item.goal.id === 'exercise'"
              readonly
              :current="item.progress"
              :target="item.goal.target"
            />

            <EvolucaoSleepChart
              v-else-if="item.goal.id === 'sleep'"
              readonly
              :target="item.goal.target"
              :schedule="sleepSchedule"
            />

            <div v-else class="evo-goal-actions evo-goal-actions--readonly">
              <span class="evo-goal-value">{{ item.progress }} / {{ item.goal.target }} {{ item.goal.unit }}</span>
            </div>
          </div>
        </div>
      </article>
    </div>

    <article v-if="nutritionTarget && !compact" class="patient-goals-targets">
      <h4>Metas nutricionais (diário)</h4>
      <div class="patient-goals-targets-grid">
        <span><strong>{{ nutritionTarget.caloriesKcal }}</strong> kcal</span>
        <span>C {{ nutritionTarget.carbsG }}g</span>
        <span>P {{ nutritionTarget.proteinG }}g</span>
        <span>G {{ nutritionTarget.fatG }}g</span>
      </div>
    </article>
  </div>
</template>

<script setup>
import { Cookie, Droplets, Dumbbell, Moon, Sparkles } from 'lucide-vue-next'
import {
  buildGoalsSummary,
  getFoodSelectedDays,
  getSleepSchedule,
  weekdayIndex,
} from '~/utils/patientGoalsProgress.js'

const props = defineProps({
  patientId: { type: String, required: true },
  nutritionTarget: { type: Object, default: null },
  compact: { type: Boolean, default: false },
  limit: { type: Number, default: 0 },
})

const config = useRuntimeConfig()

const loading = ref(true)
const error = ref('')
const goals = ref([])
const progress = ref({})

function authHeaders() {
  const token = import.meta.client ? localStorage.getItem('auth_token') : null
  return token ? { Authorization: `Bearer ${token}` } : {}
}

const goalRows = computed(() => buildGoalsSummary(goals.value, progress.value))

const visibleGoalRows = computed(() => {
  if (!props.compact || !props.limit || props.limit <= 0) return goalRows.value
  return goalRows.value.slice(0, props.limit)
})

const foodGoal = computed(() => goals.value.find((item) => item.id === 'food') || null)
const foodSelectedDays = computed(() => getFoodSelectedDays(foodGoal.value, progress.value))
const todayWeekdayIndex = computed(() => weekdayIndex())
const sleepSchedule = computed(() => getSleepSchedule(progress.value))

function goalIcon(goal) {
  if (goal.type === 'water') return Droplets
  if (goal.id === 'food') return Cookie
  if (goal.id === 'exercise') return Dumbbell
  if (goal.id === 'sleep') return Moon
  return Sparkles
}

function frequencyLabel(frequency) {
  return frequency === 'weekly' ? 'Semanal' : 'Diária'
}

async function loadGoals() {
  loading.value = true
  error.value = ''
  try {
    const data = await $fetch(`${config.public.apiBase}/patients/${props.patientId}/goals`, {
      headers: authHeaders(),
    })
    goals.value = Array.isArray(data.goals) ? data.goals : []
    progress.value = data.progress && typeof data.progress === 'object' ? data.progress : {}
  } catch (err) {
    error.value = err?.data?.message || 'Não foi possível carregar as metas.'
    goals.value = []
    progress.value = {}
  } finally {
    loading.value = false
  }
}

watch(() => props.patientId, loadGoals, { immediate: true })
</script>

<style scoped>
.patient-goals-readonly {
  display: flex;
  flex-direction: column;
  gap: 0.85rem;
}

.patient-goals-readonly--compact .evo-goals {
  gap: 0.65rem;
}

.patient-goals-readonly--compact .evo-goal-card {
  padding: 0.85rem 0.9rem 0.8rem;
}

.patient-goals-readonly--compact .evo-goal-pct {
  font-size: 1.25rem;
}

.patient-goals-state {
  font-size: 0.88rem;
  color: #666;
}

.patient-goals-state--error {
  color: #c53030;
}

.evo-goals {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.evo-goal-card {
  padding: 1rem 1.05rem 0.95rem;
  border-radius: 1.35rem;
  border: none;
  background: #f3f4f6;
  box-shadow: none;
}

.evo-goal-card--water { background: #e8f0fb; }
.evo-goal-card--food { background: #f8f0ed; }
.evo-goal-card--exercise { background: #eef0eb; }
.evo-goal-card--sleep { background: #f3f4f6; }

.evo-goal-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 0.75rem;
  margin-bottom: 0.85rem;
}

.evo-goal-head-copy {
  display: flex;
  align-items: flex-start;
  gap: 0.65rem;
  min-width: 0;
}

.evo-goal-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2.15rem;
  height: 2.15rem;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.72);
  flex-shrink: 0;
  color: var(--cf-text, #1c1816);
}

.evo-goal-card--water .evo-goal-icon { color: #4a8fc4; }
.evo-goal-card--food .evo-goal-icon { color: #9d7268; }
.evo-goal-card--exercise .evo-goal-icon { color: #5f8f58; }
.evo-goal-card--sleep .evo-goal-icon { color: #6b74b8; }

.evo-goal-icon-svg {
  width: 1rem;
  height: 1rem;
}

.evo-goal-head h3 {
  margin: 0;
  font-size: 0.95rem;
  font-weight: 700;
  letter-spacing: -0.01em;
  color: var(--cf-text, #1c1816);
}

.evo-goal-pct {
  font-size: 1.55rem;
  font-weight: 800;
  font-variant-numeric: tabular-nums;
  letter-spacing: -0.04em;
  line-height: 1;
  color: var(--cf-text, #1c1816);
}

.evo-goal-pct--count {
  font-size: 1.55rem;
}

.evo-goal-meta {
  margin: 0.18rem 0 0;
  font-size: 0.72rem;
  line-height: 1.4;
  color: rgba(28, 24, 22, 0.52);
}

.evo-goal-surface {
  padding: 0.75rem 0.65rem 0.7rem;
  border-radius: 1.1rem;
  background: rgba(255, 255, 255, 0.82);
  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.65);
}

.evo-goal-widget {
  padding: 0;
}

.evo-goal-actions--readonly {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0.35rem 0;
}

.evo-goal-value {
  font-size: 0.85rem;
  font-weight: 700;
  min-width: 4.5rem;
  text-align: center;
}

.patient-goals-targets {
  padding: 0.85rem 1rem;
  border: 1px solid var(--admin-border, #e8ece9);
  border-radius: 12px;
  background: #fafcfb;
}

.patient-goals-targets h4 {
  margin: 0 0 0.5rem;
  font-size: 0.88rem;
}

.patient-goals-targets-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 0.65rem 1rem;
  font-size: 0.82rem;
  color: #555;
}

.patient-goals-targets-grid strong {
  color: #141414;
}
</style>

// frontend/components/patients/PatientGoalsPanel.tsx
'use client'

import { useEffect, useMemo, useState } from 'react'
import { Cookie, Droplets, Dumbbell, Moon, Sparkles } from 'lucide-react'
import { fetchPatientGoals, type GoalItem, type GoalsProgress } from '@/lib/patient-chart/evolucao'
import {
  buildGoalsSummary,
  FOOD_WEEKDAYS,
  getFoodSelectedDays,
  getSleepSchedule,
  minutesToTimeLabel,
  weekdayIndex,
  type GoalRow,
} from '@/lib/patient-chart/goals-progress'
import styles from './PatientGoalsPanel.module.scss'

type NutritionTarget = {
  caloriesKcal?: number
  carbsG?: number
  proteinG?: number
  fatG?: number
}

type Props = {
  patientId: string
  nutritionTarget?: NutritionTarget | null
  compact?: boolean
  limit?: number
}

function goalIcon(goal: GoalItem) {
  if (goal.type === 'water') return Droplets
  if (goal.id === 'food') return Cookie
  if (goal.id === 'exercise') return Dumbbell
  if (goal.id === 'sleep') return Moon
  return Sparkles
}

function frequencyLabel(frequency?: string): string {
  return frequency === 'weekly' ? 'Semanal' : 'Diária'
}

function cardColorClass(goalId: string): string {
  if (goalId === 'water') return styles.cardWater
  if (goalId === 'food') return styles.cardFood
  if (goalId === 'exercise') return styles.cardExercise
  if (goalId === 'sleep') return styles.cardSleep
  return ''
}

/* ─── Inline mini-widgets ───────────────────────────────── */

function WaterWidget({ current, target }: { current: number; target: number }) {
  const pct = Math.min(100, target > 0 ? Math.round((current / target) * 100) : 0)
  return (
    <div className={styles.waterWidget}>
      <div className={styles.waterTrack}>
        <div className={styles.waterFill} style={{ height: `${pct}%` }} />
      </div>
      <span className={styles.widgetLabel}>
        {current} / {target} ml
      </span>
    </div>
  )
}

function FoodWidget({
  selectedDays,
  todayIndex,
}: {
  selectedDays: number[]
  todayIndex: number
}) {
  return (
    <div className={styles.foodWidget}>
      {FOOD_WEEKDAYS.map((wd) => (
        <div
          key={wd.index}
          className={[
            styles.foodDay,
            selectedDays.includes(wd.index) ? styles.foodDayDone : '',
            wd.index === todayIndex ? styles.foodDayToday : '',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <span className={styles.foodDayDot} />
          <span className={styles.foodDayLabel}>{wd.short}</span>
        </div>
      ))}
    </div>
  )
}

function ExerciseWidget({ current, target }: { current: number; target: number }) {
  const pct = Math.min(100, target > 0 ? Math.round((current / target) * 100) : 0)
  return (
    <div className={styles.exerciseWidget}>
      <div className={styles.exerciseTrack}>
        <div className={styles.exerciseFill} style={{ width: `${pct}%` }} />
      </div>
      <span className={styles.widgetLabel}>
        {current} / {target} sessões
      </span>
    </div>
  )
}

function SleepWidget({ bedMinutes, wakeMinutes, durationHours }: {
  bedMinutes: number
  wakeMinutes: number
  durationHours: number
}) {
  return (
    <div className={styles.sleepWidget}>
      <div className={styles.sleepRow}>
        <span className={styles.sleepIcon}>🌙</span>
        <span className={styles.sleepTime}>{minutesToTimeLabel(bedMinutes)}</span>
        <span className={styles.sleepArrow}>→</span>
        <span className={styles.sleepIcon}>☀️</span>
        <span className={styles.sleepTime}>{minutesToTimeLabel(wakeMinutes)}</span>
      </div>
      <span className={styles.widgetLabel}>{durationHours}h de sono</span>
    </div>
  )
}

function GenericWidget({ current, target, unit }: { current: number; target: number; unit?: string }) {
  return (
    <div className={styles.genericWidget}>
      <span className={styles.genericValue}>
        {current} / {target} {unit || ''}
      </span>
    </div>
  )
}

function GoalWidget({
  row,
  foodSelectedDays,
  todayWdIndex,
  progress,
}: {
  row: GoalRow
  foodSelectedDays: number[]
  todayWdIndex: number
  progress: GoalsProgress
}) {
  const { goal } = row
  if (goal.type === 'water') {
    return <WaterWidget current={row.progress} target={goal.target || 0} />
  }
  if (goal.id === 'food') {
    return <FoodWidget selectedDays={foodSelectedDays} todayIndex={todayWdIndex} />
  }
  if (goal.id === 'exercise') {
    return <ExerciseWidget current={row.progress} target={goal.target || 0} />
  }
  if (goal.id === 'sleep') {
    const schedule = getSleepSchedule(progress)
    return (
      <SleepWidget
        bedMinutes={schedule.bedMinutes}
        wakeMinutes={schedule.wakeMinutes}
        durationHours={schedule.durationHours}
      />
    )
  }
  return <GenericWidget current={row.progress} target={goal.target || 0} unit={goal.unit} />
}

/* ─── Main component ─────────────────────────────────────── */

export function PatientGoalsPanel({
  patientId,
  nutritionTarget,
  compact = false,
  limit = 0,
}: Props) {
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [goals, setGoals] = useState<GoalItem[]>([])
  const [progress, setProgress] = useState<GoalsProgress>({})

  useEffect(() => {
    setLoading(true)
    setError('')
    fetchPatientGoals(patientId)
      .then((data) => {
        setGoals(data.goals)
        setProgress(data.progress)
      })
      .catch((err) => {
        setError(
          (err as { message?: string })?.message || 'Não foi possível carregar as metas.',
        )
        setGoals([])
        setProgress({})
      })
      .finally(() => setLoading(false))
  }, [patientId])

  const goalRows = useMemo(() => buildGoalsSummary(goals, progress), [goals, progress])

  const visibleGoalRows = useMemo(
    () => (compact && limit > 0 ? goalRows.slice(0, limit) : goalRows),
    [goalRows, compact, limit],
  )

  const foodGoal = useMemo(() => goals.find((g) => g.id === 'food') || null, [goals])
  const foodSelectedDays = useMemo(
    () => getFoodSelectedDays(foodGoal, progress),
    [foodGoal, progress],
  )
  const todayWdIndex = useMemo(() => weekdayIndex(), [])

  if (loading) return <div className={styles.state}>Carregando metas…</div>
  if (error) return <p className={`${styles.state} ${styles.stateError}`}>{error}</p>
  if (!goalRows.length)
    return <p className={styles.state}>A paciente ainda não registrou metas no app.</p>

  return (
    <div className={`${styles.root} ${compact ? styles.compact : ''}`}>
      <div className={styles.goals}>
        {visibleGoalRows.map((row) => {
          const Icon = goalIcon(row.goal)
          return (
            <article
              key={row.goal.id}
              className={[styles.card, cardColorClass(row.goal.id)].filter(Boolean).join(' ')}
            >
              <header className={styles.head}>
                <div className={styles.headCopy}>
                  <span className={styles.icon} aria-hidden>
                    <Icon size={16} />
                  </span>
                  <div>
                    <h3>{row.goal.label}</h3>
                    <p className={styles.meta}>
                      {row.goal.id === 'food' ? (
                        <>
                          Semanal ·{' '}
                          {row.progress === 1
                            ? '1 dia registrado'
                            : `${row.progress} dias registrados`}
                        </>
                      ) : (
                        <>
                          {frequencyLabel(row.goal.frequency)} · {row.progress} / {row.goal.target}{' '}
                          {row.goal.unit}
                        </>
                      )}
                    </p>
                  </div>
                </div>
                <span className={`${styles.pct} ${row.goal.id === 'food' ? styles.pctCount : ''}`}>
                  {row.goal.id === 'food' ? row.progress : `${row.percent}%`}
                </span>
              </header>

              <div className={styles.surface}>
                <div className={styles.widget}>
                  <GoalWidget
                    row={row}
                    foodSelectedDays={foodSelectedDays}
                    todayWdIndex={todayWdIndex}
                    progress={progress}
                  />
                </div>
              </div>
            </article>
          )
        })}
      </div>

      {nutritionTarget && !compact && (
        <article className={styles.targetsCard}>
          <h4>Metas nutricionais (diário)</h4>
          <div className={styles.targetsGrid}>
            <span>
              <strong>{nutritionTarget.caloriesKcal}</strong> kcal
            </span>
            <span>C {nutritionTarget.carbsG}g</span>
            <span>P {nutritionTarget.proteinG}g</span>
            <span>G {nutritionTarget.fatG}g</span>
          </div>
        </article>
      )}
    </div>
  )
}
