// frontend/components/whatsapp/PollComposerModal.vue
<template>
  <Teleport to="body">
    <div v-if="open" class="poll-modal-backdrop" @click.self="$emit('cancel')">
      <div class="poll-modal-shell" role="dialog" aria-modal="true" aria-label="Criar mensagem interativa">
      <section class="poll-modal modal-card">
      <header class="poll-modal-header">
        <h3>Mensagem interativa</h3>
        <button type="button" class="poll-close-btn" aria-label="Fechar" @click="$emit('cancel')">✕</button>
      </header>

      <div class="poll-modal-body">
        <div class="modal-fields">
          <div class="field field--float">
            <label for="poll-type">Tipo</label>
            <SharedCfSelect
              id="poll-type"
              :model-value="form.type"
              :options="messageTypeOptions"
              :disabled="sending"
              @update:model-value="updateField('type', $event)"
            />
          </div>

          <div v-if="form.type !== 'pix-button'" class="field field--float">
            <label for="poll-text">Texto principal</label>
            <input
              id="poll-text"
              :value="form.text"
              type="text"
              class="cf-squircle cf-squircle--control"
              placeholder="Digite o texto principal"
              :disabled="sending"
              @input="updateField('text', $event.target.value)"
            />
          </div>

          <div v-if="form.type === 'button'" class="field field--float field--group poll-field-group">
            <label>Botões de ação</label>
            <InteractiveButtonsBuilder
              :model-value="form.choicesText"
              :disabled="sending"
              @update:model-value="updateField('choicesText', $event)"
            />
          </div>

          <div v-else-if="form.type === 'poll'" class="field field--float">
            <label for="poll-choices">Opções da enquete</label>
            <textarea
              id="poll-choices"
              :value="form.choicesText"
              class="cf-squircle cf-squircle--control"
              placeholder="Opção 1&#10;Opção 2"
              rows="4"
              :disabled="sending"
              @input="updateField('choicesText', $event.target.value)"
            />
          </div>

          <div v-if="form.type === 'carousel'" class="field field--float field--group poll-field-group">
            <label>Cartões do carrossel</label>
            <InteractiveCarouselBuilder
              :model-value="form.carouselCardsText"
              :disabled="sending"
              @update:model-value="updateField('carouselCardsText', $event)"
            />
          </div>

          <div v-if="form.type === 'list'" class="field field--float">
            <label for="poll-list-button">Texto do botão da lista</label>
            <input
              id="poll-list-button"
              :value="form.listButton"
              class="cf-squircle cf-squircle--control"
              type="text"
              placeholder="Ver opções"
              :disabled="sending"
              @input="updateField('listButton', $event.target.value)"
            />
          </div>

          <div v-if="form.type === 'button' || form.type === 'list'" class="field field--float">
            <label for="poll-footer">
              Rodapé <span class="field-optional">(opcional)</span>
            </label>
            <input
              id="poll-footer"
              :value="form.footerText"
              class="cf-squircle cf-squircle--control"
              type="text"
              placeholder="Texto de rodapé"
              :disabled="sending"
              @input="updateField('footerText', $event.target.value)"
            />
          </div>

          <div v-if="form.type === 'list'" class="field field--float field--group poll-field-group">
            <label>Itens da lista</label>
            <InteractiveListBuilder
              :model-value="form.choicesText"
              :disabled="sending"
              @update:model-value="updateField('choicesText', $event)"
            />
          </div>

          <div v-if="form.type === 'button'" class="field field--float">
            <label for="poll-image">
              Imagem do botão <span class="field-optional">(opcional)</span>
            </label>
            <input
              id="poll-image"
              :value="form.imageButton"
              class="cf-squircle cf-squircle--control"
              type="text"
              placeholder="https://..."
              :disabled="sending"
              @input="updateField('imageButton', $event.target.value)"
            />
          </div>

          <label v-if="form.type === 'poll'" class="poll-toggle-row">
            <span>Permitir várias respostas</span>
            <input
              :checked="Boolean(form.allowMultiple)"
              type="checkbox"
              :disabled="sending"
              @change="updateField('allowMultiple', $event.target.checked)"
            />
          </label>

          <template v-if="form.type === 'request-payment' || form.type === 'pix-button'">
            <div class="field field--float">
              <label for="poll-pix-type">Tipo da chave PIX</label>
              <SharedCfSelect
                id="poll-pix-type"
                :model-value="form.pixType"
                :options="pixTypeOptions"
                :disabled="sending"
                @update:model-value="updateField('pixType', $event)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-pix-key">Chave PIX</label>
              <input
                id="poll-pix-key"
                :value="form.pixKey"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="Digite a chave PIX"
                :disabled="sending"
                @input="updateField('pixKey', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-pix-name">
                Nome do recebedor <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-pix-name"
                :value="form.pixName"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="Ex: Loja Exemplo"
                :disabled="sending"
                @input="updateField('pixName', $event.target.value)"
              />
            </div>
          </template>

          <template v-if="form.type === 'request-payment'">
            <div class="field field--float">
              <label for="poll-amount">Valor (BRL)</label>
              <input
                id="poll-amount"
                :value="form.amount"
                class="cf-squircle cf-squircle--control"
                type="number"
                min="0"
                step="0.01"
                placeholder="199.90"
                :disabled="sending"
                @input="updateField('amount', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-item-name">
                Nome do item <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-item-name"
                :value="form.itemName"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="Assinatura Plano Ouro"
                :disabled="sending"
                @input="updateField('itemName', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-invoice">
                Número da fatura <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-invoice"
                :value="form.invoiceNumber"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="PED-123"
                :disabled="sending"
                @input="updateField('invoiceNumber', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-payment-link">
                Link de pagamento <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-payment-link"
                :value="form.paymentLink"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="https://pagamentos.exemplo.com/checkout/abc"
                :disabled="sending"
                @input="updateField('paymentLink', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-file-url">
                URL do arquivo <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-file-url"
                :value="form.fileUrl"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="https://cdn.exemplo.com/boleto.pdf"
                :disabled="sending"
                @input="updateField('fileUrl', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-file-name">
                Nome do arquivo <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-file-name"
                :value="form.fileName"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="boleto-123.pdf"
                :disabled="sending"
                @input="updateField('fileName', $event.target.value)"
              />
            </div>

            <div class="field field--float">
              <label for="poll-boleto">
                Linha digitável do boleto <span class="field-optional">(opcional)</span>
              </label>
              <input
                id="poll-boleto"
                :value="form.boletoCode"
                class="cf-squircle cf-squircle--control"
                type="text"
                placeholder="34191.79001..."
                :disabled="sending"
                @input="updateField('boletoCode', $event.target.value)"
              />
            </div>
          </template>
        </div>
      </div>

      <footer class="poll-modal-footer modal-actions modal-actions--single">
        <p v-if="error" class="poll-error" role="alert">{{ error }}</p>
        <button
          type="button"
          class="btn-primary"
          :disabled="sending || !canSubmit"
          @click="$emit('confirm')"
        >
          {{ sending ? 'Enviando...' : 'Enviar mensagem interativa' }}
        </button>
      </footer>
      </section>

      <aside class="poll-modal-preview" aria-label="Preview em tempo real">
        <header class="poll-preview-header">
          <h4>Teste ao vivo</h4>
          <span class="poll-preview-hint">Clique na mensagem para simular o que o paciente verá</span>
        </header>
        <div class="poll-preview-body">
          <InteractiveMessagePreview :form="form" playground />
        </div>
      </aside>
    </div>
  </div>
  </Teleport>
</template>

<script setup>
import { computed } from 'vue'
import InteractiveListBuilder from '~/components/whatsapp/InteractiveListBuilder.vue'
import InteractiveButtonsBuilder from '~/components/whatsapp/InteractiveButtonsBuilder.vue'
import InteractiveCarouselBuilder from '~/components/whatsapp/InteractiveCarouselBuilder.vue'
import InteractiveMessagePreview from '~/components/whatsapp/InteractiveMessagePreview.vue'

const props = defineProps({
  open: { type: Boolean, default: false },
  sending: { type: Boolean, default: false },
  error: { type: String, default: '' },
  form: {
    type: Object,
    default: () => ({
      type: 'poll',
      text: '',
      choicesText: '',
      footerText: '',
      listButton: 'Ver opções',
      imageButton: '',
      allowMultiple: false,
      carouselCardsText: '',
      amount: '',
      pixKey: '',
      pixType: 'EVP',
      pixName: '',
      paymentLink: '',
      fileUrl: '',
      fileName: '',
      boletoCode: '',
      invoiceNumber: '',
      itemName: ''
    })
  }
})

const emit = defineEmits(['cancel', 'confirm', 'update:form'])

const messageTypeOptions = [
  { value: 'poll', label: 'Enquete' },
  { value: 'button', label: 'Botões' },
  { value: 'list', label: 'Lista' },
  { value: 'carousel', label: 'Carrossel' },
  { value: 'request-payment', label: 'Solicitar pagamento' },
  { value: 'pix-button', label: 'Botão PIX' }
]

const pixTypeOptions = [
  { value: 'EVP', label: 'EVP' },
  { value: 'CPF', label: 'CPF' },
  { value: 'CNPJ', label: 'CNPJ' },
  { value: 'PHONE', label: 'PHONE' },
  { value: 'EMAIL', label: 'EMAIL' }
]

const sanitizeForm = (draft) => ({
  type: String(draft?.type || 'poll'),
  text: String(draft?.text || ''),
  choicesText: String(draft?.choicesText || ''),
  footerText: String(draft?.footerText || ''),
  listButton: String(draft?.listButton || 'Ver opções'),
  imageButton: String(draft?.imageButton || ''),
  allowMultiple: Boolean(draft?.allowMultiple),
  carouselCardsText: String(draft?.carouselCardsText || ''),
  amount: String(draft?.amount || ''),
  pixKey: String(draft?.pixKey || ''),
  pixType: String(draft?.pixType || 'EVP'),
  pixName: String(draft?.pixName || ''),
  paymentLink: String(draft?.paymentLink || ''),
  fileUrl: String(draft?.fileUrl || ''),
  fileName: String(draft?.fileName || ''),
  boletoCode: String(draft?.boletoCode || ''),
  invoiceNumber: String(draft?.invoiceNumber || ''),
  itemName: String(draft?.itemName || '')
})

const updateField = (key, value) => {
  const next = sanitizeForm(props.form)
  next[key] = value
  emit('update:form', next)
}

const canSubmit = computed(() => {
  const text = String(props.form?.text || '').trim()
  const options = String(props.form?.choicesText || '')
    .split('\n')
    .map((v) => String(v || '').trim())
    .filter(Boolean)
  const type = String(props.form?.type || 'poll')
  if (type !== 'pix-button' && !text) return false
  if (type === 'poll') return options.length >= 2
  if (type === 'carousel') return String(props.form?.carouselCardsText || '').trim().length > 0
  if (type === 'request-payment') return Number(props.form?.amount || 0) > 0 && String(props.form?.pixKey || '').trim().length > 0
  if (type === 'pix-button') return String(props.form?.pixKey || '').trim().length > 0
  return options.length >= 1
})
</script>

<style scoped>
.poll-modal-backdrop {
  position: fixed;
  inset: 0;
  z-index: 10080;
  background: rgba(17, 27, 33, 0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  box-sizing: border-box;
}
.poll-modal-shell {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 400px;
  align-items: stretch;
  width: min(1040px, calc(100vw - 48px));
  max-height: min(90vh, 820px);
  min-height: 0;
  border-radius: 14px;
  overflow: hidden;
  border: 1px solid #e9edef;
  box-shadow: 0 12px 40px rgba(11, 20, 26, 0.18);
  background: #fff;
}
.poll-modal {
  min-width: 0;
  min-height: 0;
  max-height: inherit;
  background: #fff;
  color: #111b21;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  border-right: 1px solid #e9edef;
}
.poll-modal-preview {
  width: 400px;
  min-width: 0;
  min-height: 0;
  max-height: inherit;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: #e5ddd5;
}
.poll-preview-header {
  flex-shrink: 0;
  padding: 14px 16px 10px;
  background: #f0f2f5;
  border-bottom: 1px solid #e9edef;
}
.poll-preview-header h4 {
  margin: 0;
  font-size: 0.9rem;
  font-weight: 600;
  color: #111b21;
}
.poll-preview-hint {
  display: block;
  margin-top: 2px;
  font-size: 0.75rem;
  color: #667781;
}
.poll-preview-body {
  flex: 1;
  min-height: 0;
  min-width: 0;
  overflow-x: hidden;
  overflow-y: auto;
  padding: 14px 16px 18px;
  -webkit-overflow-scrolling: touch;
}
.poll-preview-body :deep(.interactive-preview-header) {
  display: none;
}
.poll-preview-body :deep(.interactive-preview),
.poll-preview-body :deep(.interactive-chat-preview) {
  width: 100%;
  max-width: 100%;
  min-width: 0;
  box-sizing: border-box;
}
.poll-preview-body :deep(.interactive-bubble),
.poll-preview-body :deep(.interactive-menu-card),
.poll-preview-body :deep(.interactive-bubble--hint) {
  width: 100%;
  max-width: 100%;
  min-width: 0;
  box-sizing: border-box;
}
.poll-preview-body :deep(.interactive-menu-action-btn),
.poll-preview-body :deep(.interactive-menu-action-row),
.poll-preview-body :deep(.interactive-list-btn),
.poll-preview-body :deep(.interactive-carousel-action) {
  min-width: 0;
  max-width: 100%;
}
.poll-preview-body :deep(.interactive-menu-label),
.poll-preview-body :deep(.interactive-menu-title) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 100%;
}
.poll-preview-body :deep(.interactive-list-panel) {
  width: 100%;
  max-width: 100%;
  box-sizing: border-box;
}
.poll-preview-body :deep(.interactive-carousel) {
  max-width: 100%;
  margin: 0;
  padding: 6px 0 8px;
}
.poll-preview-body :deep(.interactive-carousel-card) {
  min-width: 160px;
  max-width: calc(100% - 8px);
  flex-shrink: 0;
}
.poll-preview-body :deep(.interactive-bubble--hint) {
  font-size: 0.78rem;
  line-height: 1.35;
  word-break: break-word;
  white-space: normal;
}
.poll-modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 16px 20px;
  background: #f0f2f5;
  border-bottom: 1px solid #e9edef;
  flex-shrink: 0;
}
.poll-modal-header h3 {
  margin: 0;
  font-size: 1.05rem;
  font-weight: 600;
  color: #111b21;
}
.poll-close-btn {
  border: none;
  background: transparent;
  color: #667781;
  cursor: pointer;
  font-size: 1.15rem;
  line-height: 1;
  padding: 4px 6px;
  border-radius: 6px;
}
.poll-close-btn:hover {
  background: rgba(11, 20, 26, 0.06);
  color: #111b21;
}
.poll-modal-body {
  padding: 0.35rem 20px 16px;
  overflow-x: hidden;
  overflow-y: auto;
  flex: 1;
  min-height: 0;
}
.poll-modal-body .modal-fields {
  margin-top: 0.15rem;
}
.poll-modal .field--group > label {
  z-index: 3;
}
.poll-modal .field--group {
  padding-top: 0.35rem;
}
.poll-field-group {
  margin-top: 0.75rem;
  padding: 1rem 0.85rem 0.85rem;
  border: 1.5px solid #e8ece9;
  border-radius: var(--cf-radius-control);
  background: #fff;
}
.poll-field-group > label {
  background: #fff;
}
.poll-modal .field-optional {
  font-weight: 500;
  color: #aaa;
}
.poll-toggle-row {
  margin-top: 0.5rem;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: 600;
  font-size: 0.9rem;
  color: #333d3b;
  padding: 12px 14px;
  background: #f4f7f6;
  border-radius: var(--cf-radius-control);
  border: 1.5px solid #e8ece9;
}
.poll-toggle-row input {
  width: 18px;
  height: 18px;
  accent-color: var(--primary, #8B967C);
}
.poll-error {
  margin: 0;
  padding: 10px 12px;
  border-radius: var(--cf-radius-control);
  background: #fce8e6;
  color: #b3261e;
  font-size: 0.86rem;
  line-height: 1.4;
  border: 1px solid #f5c6c2;
}
.poll-modal-footer {
  flex-shrink: 0;
  padding: 14px 20px 18px;
  background: #f4f7f6;
  border-top: 1px solid #e8ece9;
}
.poll-modal-footer.modal-actions--single {
  display: flex;
  flex-direction: column;
  gap: 0.65rem;
}
.poll-modal-footer.modal-actions--single .btn-primary {
  width: 100%;
}
@media (max-width: 860px) {
  .poll-modal-shell {
    grid-template-columns: 1fr;
    grid-template-rows: minmax(0, 1fr) minmax(260px, 38vh);
    width: min(560px, calc(100vw - 24px));
    max-height: min(96vh, 920px);
  }
  .poll-modal {
    border-right: none;
    border-bottom: 1px solid #e9edef;
    max-height: 58vh;
  }
  .poll-modal-preview {
    width: 100%;
    min-height: 260px;
  }
}
</style>

<style>
/* Teleport para body — herda o mesmo padrão dos modais do painel (.modal-overlay) */
.poll-modal-backdrop .poll-modal.modal-card .modal-fields {
  display: flex;
  flex-direction: column;
  gap: 0.85rem;
}

.poll-modal-backdrop .poll-modal.modal-card .field--float {
  position: relative;
  margin-top: 0.35rem;
}

.poll-modal-backdrop .poll-modal.modal-card .field--float > label {
  position: absolute;
  top: -0.58rem;
  left: 0.78rem;
  margin: 0;
  padding: 0 0.4rem;
  background: #fff;
  z-index: 2;
  font-size: 0.76rem;
  font-weight: 700;
  color: #444;
  line-height: 1;
  pointer-events: none;
}

.poll-modal-backdrop .poll-modal.modal-card .field input,
.poll-modal-backdrop .poll-modal.modal-card .field textarea {
  width: 100%;
  padding: 0.85rem 0.9rem;
  border: 1.5px solid #e8ece9;
  border-radius: var(--cf-radius-control);
  font-family: inherit;
  font-size: 0.9rem;
  box-sizing: border-box;
  background: #fff;
  color: #1a2e24;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}

.poll-modal-backdrop .poll-modal.modal-card .field textarea {
  min-height: 6.5rem;
  resize: vertical;
  line-height: 1.45;
}

.poll-modal-backdrop .poll-modal.modal-card .field--float input,
.poll-modal-backdrop .poll-modal.modal-card .field--float textarea {
  padding-top: 0.95rem;
}

.poll-modal-backdrop .poll-modal.modal-card .field input:focus,
.poll-modal-backdrop .poll-modal.modal-card .field textarea:focus {
  outline: none;
  border-color: #b8d4b4;
  box-shadow: 0 0 0 3px rgba(45, 90, 39, 0.08);
}

.poll-modal-backdrop .poll-modal.modal-card .field input:disabled,
.poll-modal-backdrop .poll-modal.modal-card .field textarea:disabled {
  background: #f4f7f6;
  color: #8696a0;
}

.poll-modal-backdrop .poll-modal.modal-card .field--float .cf-select {
  width: 100%;
}

.poll-modal-backdrop .poll-field-group > label {
  background: #fff;
}

.poll-modal-backdrop .btn-builder-field > label,
.poll-modal-backdrop .list-builder-field > label,
.poll-modal-backdrop .carousel-field > label {
  background: #f4f7f6;
}

.poll-modal-backdrop .field--group .btn-builder,
.poll-modal-backdrop .field--group .list-builder,
.poll-modal-backdrop .field--group .carousel-builder {
  margin-top: 0.15rem;
}

@supports (corner-shape: squircle) {
  .poll-modal-backdrop .poll-modal.modal-card .field input,
  .poll-modal-backdrop .poll-modal.modal-card .field textarea,
  .poll-modal-backdrop .poll-modal.modal-card .btn-primary,
  .poll-modal-backdrop .poll-modal.modal-card .btn-secondary {
    corner-shape: squircle;
  }
}
</style>

// frontend/components/whatsapp/interactive/PollComposerModal.tsx
// @ts-nocheck
'use client'
import { useState } from 'react'
import type { PollForm } from '@/lib/whatsapp/groups'
import { defaultPollForm } from '@/lib/whatsapp/groups'

interface Props {
  open: boolean
  sending?: boolean
  error?: string
  onCancel: () => void
  onConfirm: (form: PollForm) => void
}

const MESSAGE_TYPE_OPTIONS = [
  { value: 'poll', label: 'Enquete' },
  { value: 'button', label: 'Botões' },
  { value: 'list', label: 'Lista' },
  { value: 'carousel', label: 'Carrossel' },
  { value: 'request-payment', label: 'Solicitar pagamento' },
  { value: 'pix-button', label: 'Botão PIX' },
]

const PIX_TYPE_OPTIONS = ['EVP', 'CPF', 'CNPJ', 'PHONE', 'EMAIL']

export function PollComposerModal({ open, sending, error, onCancel, onConfirm }: Props) {
  const [form, setForm] = useState<PollForm>(defaultPollForm)

  const update = (key: keyof PollForm, value: unknown) => {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  const canSubmit = (() => {
    const text = form.text.trim()
    const options = form.choicesText.split('\n').map((v) => v.trim()).filter(Boolean)
    if (form.type !== 'pix-button' && !text) return false
    if (form.type === 'poll') return options.length >= 2
    if (form.type === 'carousel') return form.carouselCardsText.trim().length > 0
    if (form.type === 'request-payment') return Number(form.amount) > 0 && form.pixKey.trim().length > 0
    if (form.type === 'pix-button') return form.pixKey.trim().length > 0
    return options.length >= 1
  })()

  if (!open) return null

  return (
    <div style={backdropStyle} onClick={onCancel}>
      <div style={shellStyle} onClick={(e) => e.stopPropagation()}>
        {/* Form side */}
        <section style={formSideStyle}>
          <header style={headerStyle}>
            <h3 style={{ margin: 0, fontSize: '1.05rem', fontWeight: 600, color: '#111b21' }}>Mensagem interativa</h3>
            <button onClick={onCancel} style={closeBtnStyle}>✕</button>
          </header>

          <div style={{ flex: 1, minHeight: 0, overflow: 'auto', padding: '14px 20px 16px' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>

              {/* Type */}
              <FloatField label="Tipo">
                <select value={form.type} onChange={(e) => update('type', e.target.value)} disabled={sending} style={selectStyle}>
                  {MESSAGE_TYPE_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
                </select>
              </FloatField>

              {/* Main text */}
              {form.type !== 'pix-button' && (
                <FloatField label="Texto principal">
                  <input
                    value={form.text}
                    onChange={(e) => update('text', e.target.value)}
                    placeholder="Digite o texto principal"
                    disabled={sending}
                    style={inputStyle}
                  />
                </FloatField>
              )}

              {/* Poll choices */}
              {form.type === 'poll' && (
                <FloatField label="Opções da enquete">
                  <textarea
                    value={form.choicesText}
                    onChange={(e) => update('choicesText', e.target.value)}
                    placeholder={'Opção 1\nOpção 2'}
                    rows={4}
                    disabled={sending}
                    style={{ ...inputStyle, height: 'auto', resize: 'vertical', lineHeight: 1.45, paddingTop: '0.95rem' }}
                  />
                </FloatField>
              )}

              {/* Poll allow multiple */}
              {form.type === 'poll' && (
                <label style={toggleRowStyle}>
                  <span>Permitir várias respostas</span>
                  <input
                    type="checkbox"
                    checked={Boolean(form.allowMultiple)}
                    onChange={(e) => update('allowMultiple', e.target.checked)}
                    disabled={sending}
                    style={{ width: 18, height: 18, accentColor: '#8B967C' }}
                  />
                </label>
              )}

              {/* Buttons */}
              {form.type === 'button' && (
                <FloatField label="Botões de ação">
                  <textarea
                    value={form.choicesText}
                    onChange={(e) => update('choicesText', e.target.value)}
                    placeholder={'Botão 1\nBotão 2\nBotão 3'}
                    rows={3}
                    disabled={sending}
                    style={{ ...inputStyle, height: 'auto', resize: 'vertical', paddingTop: '0.95rem' }}
                  />
                </FloatField>
              )}

              {/* Button image */}
              {form.type === 'button' && (
                <FloatField label="Imagem do botão (opcional)">
                  <input
                    value={form.imageButton}
                    onChange={(e) => update('imageButton', e.target.value)}
                    placeholder="https://..."
                    disabled={sending}
                    style={inputStyle}
                  />
                </FloatField>
              )}

              {/* List button text */}
              {form.type === 'list' && (
                <FloatField label="Texto do botão da lista">
                  <input
                    value={form.listButton}
                    onChange={(e) => update('listButton', e.target.value)}
                    placeholder="Ver opções"
                    disabled={sending}
                    style={inputStyle}
                  />
                </FloatField>
              )}

              {/* List items */}
              {form.type === 'list' && (
                <FloatField label="Itens da lista">
                  <textarea
                    value={form.choicesText}
                    onChange={(e) => update('choicesText', e.target.value)}
                    placeholder={'Item 1\nItem 2\nItem 3'}
                    rows={4}
                    disabled={sending}
                    style={{ ...inputStyle, height: 'auto', resize: 'vertical', paddingTop: '0.95rem' }}
                  />
                </FloatField>
              )}

              {/* Footer */}
              {(form.type === 'button' || form.type === 'list') && (
                <FloatField label="Rodapé (opcional)">
                  <input
                    value={form.footerText}
                    onChange={(e) => update('footerText', e.target.value)}
                    placeholder="Texto de rodapé"
                    disabled={sending}
                    style={inputStyle}
                  />
                </FloatField>
              )}

              {/* Carousel */}
              {form.type === 'carousel' && (
                <FloatField label="Cartões do carrossel (JSON ou texto)">
                  <textarea
                    value={form.carouselCardsText}
                    onChange={(e) => update('carouselCardsText', e.target.value)}
                    placeholder="Cartão 1\nCartão 2"
                    rows={4}
                    disabled={sending}
                    style={{ ...inputStyle, height: 'auto', resize: 'vertical', paddingTop: '0.95rem' }}
                  />
                </FloatField>
              )}

              {/* PIX fields */}
              {(form.type === 'request-payment' || form.type === 'pix-button') && (
                <>
                  <FloatField label="Tipo da chave PIX">
                    <select value={form.pixType} onChange={(e) => update('pixType', e.target.value)} disabled={sending} style={selectStyle}>
                      {PIX_TYPE_OPTIONS.map((o) => <option key={o} value={o}>{o}</option>)}
                    </select>
                  </FloatField>
                  <FloatField label="Chave PIX">
                    <input value={form.pixKey} onChange={(e) => update('pixKey', e.target.value)} placeholder="Digite a chave PIX" disabled={sending} style={inputStyle} />
                  </FloatField>
                  <FloatField label="Nome do recebedor (opcional)">
                    <input value={form.pixName} onChange={(e) => update('pixName', e.target.value)} placeholder="Ex: Loja Exemplo" disabled={sending} style={inputStyle} />
                  </FloatField>
                </>
              )}

              {form.type === 'request-payment' && (
                <>
                  <FloatField label="Valor (BRL)">
                    <input type="number" min="0" step="0.01" value={form.amount} onChange={(e) => update('amount', e.target.value)} placeholder="199.90" disabled={sending} style={inputStyle} />
                  </FloatField>
                  <FloatField label="Nome do item (opcional)">
                    <input value={form.itemName} onChange={(e) => update('itemName', e.target.value)} placeholder="Assinatura Plano Ouro" disabled={sending} style={inputStyle} />
                  </FloatField>
                  <FloatField label="Número da fatura (opcional)">
                    <input value={form.invoiceNumber} onChange={(e) => update('invoiceNumber', e.target.value)} placeholder="PED-123" disabled={sending} style={inputStyle} />
                  </FloatField>
                  <FloatField label="Link de pagamento (opcional)">
                    <input value={form.paymentLink} onChange={(e) => update('paymentLink', e.target.value)} placeholder="https://pagamentos..." disabled={sending} style={inputStyle} />
                  </FloatField>
                </>
              )}

            </div>
          </div>

          <footer style={{ padding: '14px 20px 18px', background: '#f4f7f6', borderTop: '1px solid #e8ece9', flexShrink: 0, display: 'flex', flexDirection: 'column', gap: '.65rem' }}>
            {error && (
              <p style={{ margin: 0, padding: '10px 12px', borderRadius: 8, background: '#fce8e6', color: '#b3261e', fontSize: '.86rem', border: '1px solid #f5c6c2' }}>
                {error}
              </p>
            )}
            <button
              onClick={() => onConfirm(form)}
              disabled={sending || !canSubmit}
              style={{ ...confirmBtnStyle, opacity: (sending || !canSubmit) ? .55 : 1 }}
            >
              {sending ? 'Enviando...' : 'Enviar mensagem interativa'}
            </button>
          </footer>
        </section>

        {/* Preview side */}
        <aside style={previewSideStyle}>
          <header style={{ flexShrink: 0, padding: '14px 16px 10px', background: '#f0f2f5', borderBottom: '1px solid #e9edef' }}>
            <h4 style={{ margin: 0, fontSize: '.9rem', fontWeight: 600, color: '#111b21' }}>Teste ao vivo</h4>
            <span style={{ display: 'block', marginTop: 2, fontSize: '.75rem', color: '#667781' }}>
              Prévia da mensagem interativa
            </span>
          </header>
          <div style={{ flex: 1, overflow: 'auto', padding: '14px 16px 18px' }}>
            <PollPreview form={form} />
          </div>
        </aside>
      </div>
    </div>
  )
}

// ─── Preview ──────────────────────────────────────────────────────────────────

function PollPreview({ form }: { form: PollForm }) {
  const bubbleStyle: React.CSSProperties = {
    background: '#fff', borderRadius: 8, padding: '8px 10px', maxWidth: '100%',
    boxShadow: '0 1px 2px rgba(0,0,0,.12)', marginBottom: 8, fontSize: '.88rem', color: '#111b21',
  }

  if (form.type === 'poll') {
    const options = form.choicesText.split('\n').map((v) => v.trim()).filter(Boolean)
    return (
      <div>
        <div style={bubbleStyle}>
          {form.text && <p style={{ margin: '0 0 8px', fontWeight: 500 }}>{form.text}</p>}
          {options.length === 0 ? (
            <p style={{ margin: 0, color: '#8696a0', fontSize: '.82rem' }}>Adicione opções acima</p>
          ) : options.map((opt, i) => (
            <div key={i} style={{ padding: '6px 0', borderBottom: i < options.length - 1 ? '1px solid #f0f2f5' : 'none', cursor: 'pointer' }}>
              <span style={{ display: 'inline-block', width: 16, height: 16, borderRadius: '50%', border: '1.5px solid #25d366', marginRight: 8, verticalAlign: 'middle' }} />
              {opt}
            </div>
          ))}
        </div>
      </div>
    )
  }

  if (form.type === 'button') {
    const btns = form.choicesText.split('\n').map((v) => v.trim()).filter(Boolean)
    return (
      <div style={bubbleStyle}>
        {form.text && <p style={{ margin: '0 0 8px' }}>{form.text}</p>}
        {btns.map((btn, i) => (
          <div key={i} style={{ textAlign: 'center', padding: '8px 0', borderTop: '1px solid #e9edef', color: '#008069', fontWeight: 500, cursor: 'pointer' }}>{btn}</div>
        ))}
      </div>
    )
  }

  if (form.type === 'list') {
    return (
      <div style={bubbleStyle}>
        {form.text && <p style={{ margin: '0 0 8px' }}>{form.text}</p>}
        <div style={{ textAlign: 'center', padding: '8px 0', borderTop: '1px solid #e9edef', color: '#008069', fontWeight: 500, cursor: 'pointer' }}>
          {form.listButton || 'Ver opções'}
        </div>
      </div>
    )
  }

  if (form.type === 'pix-button') {
    return (
      <div style={bubbleStyle}>
        <p style={{ margin: '0 0 4px', fontWeight: 600, color: '#008069' }}>💠 Pagamento via PIX</p>
        <p style={{ margin: 0, fontSize: '.82rem', color: '#667781' }}>Chave: {form.pixKey || '—'}</p>
      </div>
    )
  }

  if (form.type === 'request-payment') {
    return (
      <div style={bubbleStyle}>
        <p style={{ margin: '0 0 4px', fontWeight: 600 }}>{form.text || 'Solicitação de pagamento'}</p>
        <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#008069' }}>R$ {form.amount || '0,00'}</p>
        <p style={{ margin: 0, fontSize: '.78rem', color: '#667781' }}>Chave PIX: {form.pixKey || '—'}</p>
      </div>
    )
  }

  return (
    <div style={bubbleStyle}>
      <p style={{ margin: 0, color: '#667781', fontSize: '.86rem' }}>Tipo: {form.type}</p>
      {form.text && <p style={{ margin: '6px 0 0' }}>{form.text}</p>}
    </div>
  )
}

// ─── FloatField helper ────────────────────────────────────────────────────────

function FloatField({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ position: 'relative', marginTop: '.35rem' }}>
      <span style={{
        position: 'absolute', top: '-.42rem', left: '.78rem', background: '#fff',
        zIndex: 2, fontSize: '.76rem', fontWeight: 700, color: '#444',
        lineHeight: 1, padding: '0 .4rem', pointerEvents: 'none',
      }}>
        {label}
      </span>
      {children}
    </div>
  )
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const backdropStyle: React.CSSProperties = {
  position: 'fixed', inset: 0, zIndex: 10080, background: 'rgba(17,27,33,.45)',
  display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, boxSizing: 'border-box',
}

const shellStyle: React.CSSProperties = {
  display: 'grid', gridTemplateColumns: 'minmax(0,1fr) 380px', alignItems: 'stretch',
  width: 'min(1040px,calc(100vw - 48px))', maxHeight: 'min(90vh,820px)', minHeight: 0,
  borderRadius: 14, overflow: 'hidden', border: '1px solid #e9edef',
  boxShadow: '0 12px 40px rgba(11,20,26,.18)', background: '#fff',
}

const formSideStyle: React.CSSProperties = {
  minWidth: 0, minHeight: 0, maxHeight: 'inherit', background: '#fff',
  color: '#111b21', display: 'flex', flexDirection: 'column', overflow: 'hidden',
  borderRight: '1px solid #e9edef',
}

const previewSideStyle: React.CSSProperties = {
  width: 380, minWidth: 0, minHeight: 0, maxHeight: 'inherit',
  display: 'flex', flexDirection: 'column', overflow: 'hidden', background: '#e5ddd5',
}

const headerStyle: React.CSSProperties = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12,
  padding: '16px 20px', background: '#f0f2f5', borderBottom: '1px solid #e9edef', flexShrink: 0,
}

const closeBtnStyle: React.CSSProperties = {
  border: 'none', background: 'transparent', color: '#667781', cursor: 'pointer', fontSize: '1.15rem', padding: '4px 6px', borderRadius: 6,
}

const inputStyle: React.CSSProperties = {
  width: '100%', padding: '.85rem .9rem', border: '1.5px solid #e8ece9', borderRadius: 8,
  fontFamily: 'inherit', fontSize: '.9rem', boxSizing: 'border-box',
  background: '#fff', color: '#1a2e24', outline: 'none',
}

const selectStyle: React.CSSProperties = {
  ...inputStyle, height: 48, padding: '.85rem .9rem',
}

const toggleRowStyle: React.CSSProperties = {
  marginTop: '.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
  fontWeight: 600, fontSize: '.9rem', color: '#333d3b', padding: '12px 14px',
  background: '#f4f7f6', borderRadius: 8, border: '1.5px solid #e8ece9', cursor: 'pointer',
}

const confirmBtnStyle: React.CSSProperties = {
  width: '100%', height: 44, border: 'none', borderRadius: 8, fontWeight: 600,
  fontSize: '.95rem', cursor: 'pointer', background: '#25d366', color: '#04130a',
}
