// frontend/components/ui/CfDateInput.tsx
"use client";

import { useEffect, useId, useMemo, useState } from "react";
import { Calendar, ChevronLeft, ChevronRight } from "lucide-react";
import { AnimatedPopover } from "@/components/overlays";
import styles from "./CfDateInput.module.scss";

const WEEKDAYS = ["D", "S", "T", "Q", "Q", "S", "S"];
const MONTHS = [
  "janeiro",
  "fevereiro",
  "março",
  "abril",
  "maio",
  "junho",
  "julho",
  "agosto",
  "setembro",
  "outubro",
  "novembro",
  "dezembro",
];

function parseIso(value?: string | null) {
  if (!value) return null;
  const [year, month, day] = value.split("-").map(Number);
  if (!year || !month || !day) return null;
  return new Date(year, month - 1, day);
}

function toIsoDate(date: Date) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

function formatDisplay(value?: string | null, placeholder = "dd/mm/aaaa") {
  const date = parseIso(value);
  if (!date) return placeholder;
  return date.toLocaleDateString("pt-BR");
}

function maskDigits(digits: string) {
  if (digits.length <= 2) return digits;
  if (digits.length <= 4) return `${digits.slice(0, 2)}/${digits.slice(2)}`;
  return `${digits.slice(0, 2)}/${digits.slice(2, 4)}/${digits.slice(4)}`;
}

function parseBrazilianToIso(display: string) {
  const match = display.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
  if (!match) return null;
  const day = Number(match[1]);
  const month = Number(match[2]);
  const year = Number(match[3]);
  if (month < 1 || month > 12 || day < 1 || day > 31 || year < 1000)
    return null;
  const date = new Date(year, month - 1, day);
  if (
    date.getFullYear() !== year ||
    date.getMonth() !== month - 1 ||
    date.getDate() !== day
  ) {
    return null;
  }
  return toIsoDate(date);
}

type Props = {
  value?: string;
  onChange?: (value: string) => void;
  id?: string;
  min?: string;
  max?: string;
  required?: boolean;
  disabled?: boolean;
  placeholder?: string;
  /** Texto digitável + botão de calendário (padrão admin) */
  editable?: boolean;
};

export function CfDateInput({
  value = "",
  onChange,
  id: idProp,
  min,
  max,
  required = false,
  disabled = false,
  placeholder = "dd/mm/aaaa",
  editable = true,
}: Props) {
  const autoId = useId();
  const id = idProp || autoId;
  const [open, setOpen] = useState(false);
  const [textValue, setTextValue] = useState(() =>
    value ? formatDisplay(value, "") : "",
  );
  const [textFocused, setTextFocused] = useState(false);
  const now = new Date();
  const [viewYear, setViewYear] = useState(now.getFullYear());
  const [viewMonth, setViewMonth] = useState(now.getMonth());

  const todayIso = toIsoDate(now);

  useEffect(() => {
    if (!textFocused) setTextValue(value ? formatDisplay(value, "") : "");
  }, [value, textFocused]);

  function isDisabled(iso: string) {
    if (min && iso < min) return true;
    if (max && iso > max) return true;
    return false;
  }

  function syncViewToValue() {
    const date = parseIso(value) || new Date();
    setViewYear(date.getFullYear());
    setViewMonth(date.getMonth());
  }

  function emit(next: string) {
    onChange?.(next);
  }

  function selectDate(iso: string) {
    if (isDisabled(iso)) return;
    emit(iso);
    setTextValue(formatDisplay(iso, ""));
    setOpen(false);
  }

  const cells = useMemo(() => {
    const firstOfMonth = new Date(viewYear, viewMonth, 1);
    const startOffset = firstOfMonth.getDay();
    const daysInMonth = new Date(viewYear, viewMonth + 1, 0).getDate();
    const list: Array<{
      key: string;
      day: number;
      iso: string;
      inMonth: boolean;
      isToday: boolean;
      isSelected: boolean;
      disabled: boolean;
      label: string;
    }> = [];

    for (let i = 0; i < 42; i += 1) {
      const dayIndex = i - startOffset + 1;
      const date = new Date(viewYear, viewMonth, dayIndex);
      const inMonth = dayIndex >= 1 && dayIndex <= daysInMonth;
      const iso = toIsoDate(date);
      list.push({
        key: `${viewYear}-${viewMonth}-${i}`,
        day: date.getDate(),
        iso,
        inMonth,
        isToday: iso === todayIso,
        isSelected: iso === value,
        disabled: isDisabled(iso),
        label: date.toLocaleDateString("pt-BR", {
          weekday: "long",
          day: "numeric",
          month: "long",
          year: "numeric",
        }),
      });
    }
    return list;
  }, [viewYear, viewMonth, value, todayIso, min, max]);

  const panel = (
    <div className={styles.panelInner}>
      <div className={styles.panelHead}>
        <button
          type="button"
          className={styles.nav}
          aria-label="Mês anterior"
          onClick={() => {
            if (viewMonth === 0) {
              setViewMonth(11);
              setViewYear((y) => y - 1);
            } else setViewMonth((m) => m - 1);
          }}
        >
          <ChevronLeft size={16} />
        </button>
        <div className={styles.panelTitle}>
          {MONTHS[viewMonth]} de {viewYear}
        </div>
        <button
          type="button"
          className={styles.nav}
          aria-label="Próximo mês"
          onClick={() => {
            if (viewMonth === 11) {
              setViewMonth(0);
              setViewYear((y) => y + 1);
            } else setViewMonth((m) => m + 1);
          }}
        >
          <ChevronRight size={16} />
        </button>
      </div>

      <div className={styles.weekdays} aria-hidden>
        {WEEKDAYS.map((d, i) => (
          <span key={`${d}-${i}`}>{d}</span>
        ))}
      </div>

      <div className={styles.grid} role="grid">
        {cells.map((cell) => (
          <button
            key={cell.key}
            type="button"
            role="gridcell"
            className={[
              styles.day,
              !cell.inMonth ? styles.dayOutside : "",
              cell.isToday ? styles.dayToday : "",
              cell.isSelected ? styles.daySelected : "",
            ]
              .filter(Boolean)
              .join(" ")}
            disabled={cell.disabled}
            aria-label={cell.label}
            aria-selected={cell.isSelected}
            onClick={() => selectDate(cell.iso)}
          >
            {cell.day}
          </button>
        ))}
      </div>

      <div className={styles.panelFoot}>
        {!required ? (
          <button
            type="button"
            className={styles.footBtn}
            onClick={() => {
              emit("");
              setTextValue("");
              setOpen(false);
            }}
          >
            Limpar
          </button>
        ) : (
          <span aria-hidden />
        )}
        <button
          type="button"
          className={`${styles.footBtn} ${styles.footBtnPrimary}`}
          onClick={() => selectDate(todayIso)}
        >
          Hoje
        </button>
      </div>
    </div>
  );

  const calendarBtn = (
    <button
      type="button"
      className={`${styles.calendarBtn} cf-date-calendar-btn`}
      disabled={disabled}
      aria-label="Abrir calendário"
      aria-expanded={open}
      aria-haspopup="dialog"
      onClick={() => {
        if (disabled) return;
        if (!open) syncViewToValue();
      }}
    >
      <Calendar className={styles.icon} aria-hidden size={17} />
    </button>
  );

  if (editable) {
    return (
      <div
        className={[
          "cf-date-input",
          styles.root,
          open ? styles.open : "",
          disabled ? styles.disabled : "",
        ]
          .filter(Boolean)
          .join(" ")}
      >
        <div
          className={[
            styles.trigger,
            styles.triggerEditable,
            textFocused || open ? styles.triggerFocused : "",
            "cf-squircle",
            "cf-squircle--control",
            "cf-date-input-trigger",
          ]
            .filter(Boolean)
            .join(" ")}
        >
          <input
            id={id}
            type="text"
            className={`${styles.text} cf-date-input-text`}
            inputMode="numeric"
            autoComplete="bday"
            placeholder={placeholder}
            disabled={disabled}
            value={textValue}
            maxLength={10}
            aria-label="Data"
            onFocus={() => setTextFocused(true)}
            onBlur={() => {
              setTextFocused(false);
              if (!textValue.trim()) {
                if (!required) emit("");
                return;
              }
              const iso = parseBrazilianToIso(textValue);
              if (iso && !isDisabled(iso)) {
                emit(iso);
                setTextValue(formatDisplay(iso, ""));
                return;
              }
              setTextValue(value ? formatDisplay(value, "") : "");
            }}
            onChange={(e) => {
              const digits = e.target.value.replace(/\D/g, "").slice(0, 8);
              const masked = maskDigits(digits);
              setTextValue(masked);
              if (digits.length === 8) {
                const iso = parseBrazilianToIso(masked);
                if (iso && !isDisabled(iso)) emit(iso);
              } else if (!digits.length) {
                emit("");
              }
            }}
          />
          <AnimatedPopover
            open={open}
            onOpenChange={(next) => {
              if (disabled) return;
              if (next) syncViewToValue();
              setOpen(next);
            }}
            trigger={calendarBtn}
            contentClassName={styles.panel}
            side="bottom"
            align="end"
            sideOffset={6}
          >
            {panel}
          </AnimatedPopover>
        </div>
      </div>
    );
  }

  return (
    <div
      className={[
        "cf-date-input",
        styles.root,
        open ? styles.open : "",
        disabled ? styles.disabled : "",
      ]
        .filter(Boolean)
        .join(" ")}
    >
      <AnimatedPopover
        open={open}
        onOpenChange={(next) => {
          if (disabled) return;
          if (next) syncViewToValue();
          setOpen(next);
        }}
        trigger={
          <button
            id={id}
            type="button"
            className={`${styles.trigger} cf-squircle cf-squircle--control`}
            disabled={disabled}
            aria-expanded={open}
            aria-haspopup="dialog"
          >
            <Calendar className={styles.icon} aria-hidden size={17} />
            <span
              className={`${styles.value} ${!value ? styles.valuePlaceholder : ""}`}
            >
              {formatDisplay(value, placeholder)}
            </span>
          </button>
        }
        contentClassName={styles.panel}
        side="bottom"
        align="start"
        sideOffset={6}
      >
        {panel}
      </AnimatedPopover>
    </div>
  );
}

// frontend/components/shared/CfDateInput.vue
<template>
  <div
    ref="rootRef"
    class="cf-date-input"
    :class="{
      'cf-date-input--open': open,
      'cf-date-input--disabled': disabled,
      'cf-date-input--editable': editable,
    }"
  >
    <div
      v-if="editable"
      class="cf-date-input-trigger cf-date-input-trigger--editable cf-squircle cf-squircle--control"
      :class="{ 'cf-date-input-trigger--focused': textFocused }"
    >
      <input
        :id="id"
        type="text"
        class="cf-date-input-text"
        inputmode="numeric"
        autocomplete="bday"
        :placeholder="placeholder"
        :disabled="disabled"
        :value="textValue"
        maxlength="10"
        aria-label="Data"
        @input="onTextInput"
        @blur="onTextBlur"
        @focus="textFocused = true"
      >
      <button
        type="button"
        class="cf-date-calendar-btn"
        :disabled="disabled"
        aria-label="Abrir calendário"
        :aria-expanded="open"
        aria-haspopup="dialog"
        @click="toggle"
      >
        <Calendar class="cf-date-input-icon" aria-hidden="true" />
      </button>
    </div>

    <button
      v-else
      :id="id"
      type="button"
      class="cf-date-input-trigger cf-squircle cf-squircle--control"
      :disabled="disabled"
      :aria-expanded="open"
      aria-haspopup="dialog"
      @click="toggle"
    >
      <Calendar class="cf-date-input-icon" aria-hidden="true" />
      <span class="cf-date-input-value" :class="{ 'cf-date-input-value--placeholder': !modelValue }">
        {{ displayValue }}
      </span>
    </button>

    <Teleport to="body">
      <div
        v-if="open"
        ref="panelRef"
        class="cf-date-panel cf-squircle cf-squircle--control"
        role="dialog"
        aria-label="Selecionar data"
        :style="panelStyle"
      >
        <div class="cf-date-panel-head">
          <button type="button" class="cf-date-nav" aria-label="Mês anterior" @click="prevMonth">
            <ChevronLeft class="cf-date-nav-icon" />
          </button>

          <div class="cf-date-panel-title">
            {{ monthLabel }}
          </div>

          <button type="button" class="cf-date-nav" aria-label="Próximo mês" @click="nextMonth">
            <ChevronRight class="cf-date-nav-icon" />
          </button>
        </div>

        <div class="cf-date-weekdays" aria-hidden="true">
          <span v-for="day in weekdays" :key="day">{{ day }}</span>
        </div>

        <div class="cf-date-grid" role="grid">
          <button
            v-for="cell in calendarCells"
            :key="cell.key"
            type="button"
            role="gridcell"
            class="cf-date-day"
            :class="{
              'cf-date-day--outside': !cell.inMonth,
              'cf-date-day--today': cell.isToday,
              'cf-date-day--selected': cell.isSelected,
              'cf-date-day--disabled': cell.disabled,
            }"
            :disabled="cell.disabled"
            :aria-label="cell.label"
            :aria-selected="cell.isSelected"
            @click="selectDate(cell.iso)"
          >
            {{ cell.day }}
          </button>
        </div>

        <div class="cf-date-panel-foot">
          <button v-if="!required" type="button" class="cf-date-foot-btn" @click="clearDate">
            Limpar
          </button>
          <span v-else aria-hidden="true" />
          <button type="button" class="cf-date-foot-btn cf-date-foot-btn--primary" @click="selectToday">
            Hoje
          </button>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup>
import { Calendar, ChevronLeft, ChevronRight } from 'lucide-vue-next'

const props = defineProps({
  modelValue: {
    type: String,
    default: '',
  },
  id: {
    type: String,
    default: undefined,
  },
  min: {
    type: String,
    default: undefined,
  },
  max: {
    type: String,
    default: undefined,
  },
  required: {
    type: Boolean,
    default: false,
  },
  disabled: {
    type: Boolean,
    default: false,
  },
  placeholder: {
    type: String,
    default: 'dd/mm/aaaa',
  },
  editable: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits(['update:modelValue'])

const weekdays = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S']
const monthNames = [
  'janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho',
  'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro',
]

const open = ref(false)
const rootRef = ref(null)
const panelRef = ref(null)
const textValue = ref('')
const textFocused = ref(false)
const panelStyle = ref({})
const viewYear = ref(new Date().getFullYear())
const viewMonth = ref(new Date().getMonth())

const displayValue = computed(() => {
  if (!props.modelValue) return props.placeholder
  return formatDisplay(props.modelValue)
})

const monthLabel = computed(() => {
  const name = monthNames[viewMonth.value] || ''
  return `${name} de ${viewYear.value}`
})

const todayIso = computed(() => toIsoDate(new Date()))

const calendarCells = computed(() => {
  const firstOfMonth = new Date(viewYear.value, viewMonth.value, 1)
  const startOffset = firstOfMonth.getDay()
  const daysInMonth = new Date(viewYear.value, viewMonth.value + 1, 0).getDate()
  const cells = []

  for (let i = 0; i < 42; i += 1) {
    const dayIndex = i - startOffset + 1
    const date = new Date(viewYear.value, viewMonth.value, dayIndex)
    const inMonth = dayIndex >= 1 && dayIndex <= daysInMonth
    const iso = toIsoDate(date)

    cells.push({
      key: `${viewYear.value}-${viewMonth.value}-${i}`,
      day: date.getDate(),
      iso,
      inMonth,
      isToday: iso === todayIso.value,
      isSelected: iso === props.modelValue,
      disabled: isDisabled(iso),
      label: date.toLocaleDateString('pt-BR', {
        weekday: 'long',
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      }),
    })
  }

  return cells
})

function parseIso(value) {
  if (!value) return null
  const [year, month, day] = value.split('-').map(Number)
  if (!year || !month || !day) return null
  return new Date(year, month - 1, day)
}

function toIsoDate(date) {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const d = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${d}`
}

function formatDisplay(value) {
  const date = parseIso(value)
  if (!date) return props.placeholder
  return date.toLocaleDateString('pt-BR')
}

function maskDigits(digits) {
  if (digits.length <= 2) return digits
  if (digits.length <= 4) return `${digits.slice(0, 2)}/${digits.slice(2)}`
  return `${digits.slice(0, 2)}/${digits.slice(2, 4)}/${digits.slice(4)}`
}

function parseBrazilianToIso(display) {
  const match = display.match(/^(\d{2})\/(\d{2})\/(\d{4})$/)
  if (!match) return null

  const day = Number(match[1])
  const month = Number(match[2])
  const year = Number(match[3])
  if (month < 1 || month > 12 || day < 1 || day > 31 || year < 1000) return null

  const date = new Date(year, month - 1, day)
  if (
    date.getFullYear() !== year
    || date.getMonth() !== month - 1
    || date.getDate() !== day
  ) {
    return null
  }

  return toIsoDate(date)
}

function syncTextFromModel() {
  textValue.value = props.modelValue ? formatDisplay(props.modelValue) : ''
}

function onTextInput(event) {
  const digits = event.target.value.replace(/\D/g, '').slice(0, 8)
  textValue.value = maskDigits(digits)
  event.target.value = textValue.value

  if (digits.length === 8) {
    const iso = parseBrazilianToIso(textValue.value)
    if (iso && !isDisabled(iso)) {
      emit('update:modelValue', iso)
      return
    }
  }

  if (!digits.length) {
    emit('update:modelValue', '')
  }
}

function onTextBlur() {
  textFocused.value = false

  if (!textValue.value.trim()) {
    if (!props.required) emit('update:modelValue', '')
    return
  }

  const iso = parseBrazilianToIso(textValue.value)
  if (iso && !isDisabled(iso)) {
    emit('update:modelValue', iso)
    textValue.value = formatDisplay(iso)
    return
  }

  textValue.value = props.modelValue ? formatDisplay(props.modelValue) : ''
}

function isDisabled(iso) {
  if (props.min && iso < props.min) return true
  if (props.max && iso > props.max) return true
  return false
}

function syncViewToValue() {
  const date = parseIso(props.modelValue) || new Date()
  viewYear.value = date.getFullYear()
  viewMonth.value = date.getMonth()
}

function updatePanelPosition() {
  const root = rootRef.value
  if (!root) return

  const rect = root.getBoundingClientRect()
  const panelHeight = 360
  const gap = 6
  const spaceBelow = window.innerHeight - rect.bottom
  const openAbove = spaceBelow < panelHeight && rect.top > panelHeight

  panelStyle.value = {
    position: 'fixed',
    left: `${Math.max(12, Math.min(rect.left, window.innerWidth - rect.width - 12))}px`,
    width: `${Math.min(Math.max(rect.width, 300), 320)}px`,
    top: openAbove ? `${rect.top - panelHeight - gap}px` : `${rect.bottom + gap}px`,
    zIndex: 12000,
  }
}

function close() {
  open.value = false
}

function toggle() {
  if (props.disabled) return
  open.value = !open.value
  if (open.value) {
    syncViewToValue()
    nextTick(() => updatePanelPosition())
  }
}

function selectDate(iso) {
  if (isDisabled(iso)) return
  emit('update:modelValue', iso)
  if (props.editable) {
    textValue.value = formatDisplay(iso)
  }
  close()
}

function clearDate() {
  if (props.required) return
  emit('update:modelValue', '')
  if (props.editable) textValue.value = ''
  close()
}

function selectToday() {
  const iso = todayIso.value
  if (isDisabled(iso)) return
  emit('update:modelValue', iso)
  if (props.editable) {
    textValue.value = formatDisplay(iso)
  }
  close()
}

function prevMonth() {
  if (viewMonth.value === 0) {
    viewMonth.value = 11
    viewYear.value -= 1
  } else {
    viewMonth.value -= 1
  }
}

function nextMonth() {
  if (viewMonth.value === 11) {
    viewMonth.value = 0
    viewYear.value += 1
  } else {
    viewMonth.value += 1
  }
}

function onDocumentClick(event) {
  if (!open.value) return
  const target = event.target
  if (rootRef.value?.contains(target) || panelRef.value?.contains(target)) return
  close()
}

function onKeydown(event) {
  if (event.key === 'Escape') close()
}

watch(() => props.modelValue, () => {
  if (open.value) syncViewToValue()
  if (props.editable && !textFocused.value) syncTextFromModel()
})

watch(
  () => props.editable,
  (value) => {
    if (value) syncTextFromModel()
  },
  { immediate: true },
)

onMounted(() => {
  document.addEventListener('click', onDocumentClick)
  document.addEventListener('keydown', onKeydown)
  window.addEventListener('resize', updatePanelPosition)
  window.addEventListener('scroll', updatePanelPosition, true)
})

onBeforeUnmount(() => {
  document.removeEventListener('click', onDocumentClick)
  document.removeEventListener('keydown', onKeydown)
  window.removeEventListener('resize', updatePanelPosition)
  window.removeEventListener('scroll', updatePanelPosition, true)
})
</script>

<style scoped>
.cf-date-input {
  position: relative;
  width: 100%;
}

.cf-date-input-trigger {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  width: 100%;
  min-height: 3rem;
  padding: 0.85rem 0.9rem;
  border: 1.5px solid #e8ece9;
  background: #fff;
  font-family: inherit;
  text-align: left;
  cursor: pointer;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
  box-sizing: border-box;
  max-width: 100%;
  min-width: 0;
}

.cf-date-input-trigger--editable {
  padding: 0;
  gap: 0;
  cursor: default;
}

.cf-date-input-trigger--editable.cf-date-input-trigger--focused,
.cf-date-input--open .cf-date-input-trigger--editable {
  border-color: #b8d4b4;
  box-shadow: 0 0 0 3px rgba(45, 90, 39, 0.08);
}

.cf-date-input-text {
  flex: 1;
  min-width: 0;
  width: 100%;
  border: none;
  background: transparent;
  padding: 0.9rem 0.35rem 0.9rem 1rem;
  font-family: inherit;
  font-size: 1rem;
  font-weight: 500;
  color: var(--cf-text, #1a2e24);
  outline: none;
}

.cf-date-input-text::placeholder {
  color: #9aa8a2;
}

.cf-date-input-text:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.cf-date-calendar-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  width: 3rem;
  height: 100%;
  min-height: 3rem;
  border: none;
  background: transparent;
  color: #8a9a92;
  cursor: pointer;
  appearance: none;
  -webkit-appearance: none;
  -webkit-tap-highlight-color: transparent;
}

.cf-date-calendar-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.cf-date-calendar-btn:focus-visible {
  outline: 2px solid #9fc499;
  outline-offset: -2px;
}

.field--float .cf-date-input-trigger {
  padding-top: 0.95rem;
}

.cf-date-input-trigger:hover:not(:disabled) {
  border-color: #d4e5d1;
}

.cf-date-input-trigger:focus-visible {
  outline: none;
  border-color: #b8d4b4;
  box-shadow: 0 0 0 3px rgba(45, 90, 39, 0.08);
}

.cf-date-input--open .cf-date-input-trigger {
  border-color: #b8d4b4;
  box-shadow: 0 0 0 3px rgba(45, 90, 39, 0.08);
}

.cf-date-input-trigger:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.cf-date-input-icon {
  width: 1.05rem;
  height: 1.05rem;
  flex-shrink: 0;
  color: #8a9a92;
}

.cf-date-input--open .cf-date-input-icon,
.cf-date-input-trigger:focus-visible .cf-date-input-icon {
  color: #8B967C;
}

.cf-date-input-value {
  flex: 1;
  min-width: 0;
  font-size: 0.9rem;
  font-weight: 500;
  color: #1a2e24;
}

.cf-date-input-value--placeholder {
  color: #9aa8a2;
}

.cf-date-panel {
  overflow: hidden;
  border: 1px solid #e2e8e4;
  background: #fff;
  padding: 0.85rem 0.85rem 0.7rem;
  box-shadow:
    0 4px 6px rgba(26, 46, 36, 0.04),
    0 14px 32px rgba(26, 46, 36, 0.12);
}

.cf-date-panel-head {
  display: grid;
  grid-template-columns: 2rem 1fr 2rem;
  align-items: center;
  gap: 0.35rem;
  margin-bottom: 0.75rem;
}

.cf-date-panel-title {
  text-align: center;
  font-size: 0.88rem;
  font-weight: 700;
  color: #1a2e24;
  text-transform: capitalize;
  line-height: 1.2;
}

.cf-date-nav {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 2rem;
  height: 2rem;
  border: none;
  border-radius: var(--cf-radius-icon, 0.875rem);
  background: #f4f8f3;
  color: #8B967C;
  cursor: pointer;
  transition: background 0.12s ease;
}

.cf-date-nav:hover {
  background: #eaf3e8;
}

.cf-date-nav:focus-visible {
  outline: 2px solid #9fc499;
  outline-offset: 1px;
}

.cf-date-nav-icon {
  width: 1rem;
  height: 1rem;
}

.cf-date-weekdays {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 0.15rem;
  margin-bottom: 0.35rem;
}

.cf-date-weekdays span {
  text-align: center;
  font-size: 0.68rem;
  font-weight: 700;
  letter-spacing: 0.04em;
  color: #8a9a92;
}

.cf-date-grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 0.15rem;
}

.cf-date-day {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  aspect-ratio: 1;
  border: none;
  border-radius: var(--cf-radius-icon, 0.875rem);
  background: transparent;
  color: #1a2e24;
  font-family: inherit;
  font-size: 0.82rem;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.12s ease, color 0.12s ease;
}

.cf-date-day:hover:not(:disabled) {
  background: #f4f8f3;
}

.cf-date-day--outside {
  color: #7a8a82;
  font-weight: 500;
}

.cf-date-day--outside:hover:not(:disabled) {
  background: #f0f4f1;
  color: #5c6b64;
}

.cf-date-day--today:not(.cf-date-day--selected) {
  color: #8B967C;
  font-weight: 700;
  box-shadow: inset 0 0 0 1.5px #cfe3cb;
}

.cf-date-day--selected {
  background: #8B967C;
  color: #fff;
  font-weight: 700;
}

.cf-date-day--selected:hover:not(:disabled) {
  background: #3a6f34;
}

.cf-date-day--disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.cf-date-day--outside.cf-date-day--disabled {
  opacity: 0.55;
  color: #a3aea8;
}

.cf-date-day:focus-visible {
  outline: 2px solid #9fc499;
  outline-offset: 1px;
}

.cf-date-panel-foot {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  margin-top: 0.7rem;
  padding-top: 0.65rem;
  border-top: 1px solid #eef2ef;
}

.cf-date-foot-btn {
  border: none;
  background: transparent;
  color: #5c6b64;
  font-family: inherit;
  font-size: 0.8rem;
  font-weight: 700;
  padding: 0.35rem 0.5rem;
  border-radius: var(--cf-radius-pill);
  cursor: pointer;
  transition: color 0.12s ease, background 0.12s ease;
}

.cf-date-foot-btn:hover {
  color: #8B967C;
  background: #f4f8f3;
}

.cf-date-foot-btn--primary {
  color: #8B967C;
}

.cf-date-foot-btn:focus-visible {
  outline: 2px solid #9fc499;
  outline-offset: 2px;
}

@supports (corner-shape: squircle) {
  .cf-date-input-trigger.cf-squircle--control,
  .cf-date-panel.cf-squircle--control {
    corner-shape: squircle;
  }

  .cf-date-day {
    corner-shape: squircle;
  }
}
</style>
