// frontend2/pages/agenda.vue
<template>
  <NuxtLayout name="dashboard">
    <div class="agenda-page admin-shell">
      <AgendaGoogleCalendar
        ref="calendarRef"
        :loading="loading"
        :load-error="loadError"
        :appointments="appointments"
        :anchor-date="anchorDate"
        :search-query="searchQuery"
        @update:anchor-date="onAnchorDateChange"
        @update:search-query="searchQuery = $event"
        @update:view-mode="calendarViewMode = $event"
        @open-appointment="openEditModal"
        @schedule-slot="openSchedulePopover"
        @clear-selection="closeSchedulePopover"
        @search-submit="focusFirstSearchMatch"
        @new-appointment="openCreateModal"
      />

      <section v-if="searchResults.length" class="agenda-search-results admin-shell-card">
        <header class="agenda-search-results__head">
          <h2>Resultados da busca</h2>
          <span>{{ searchResults.length }} encontrado(s)</span>
        </header>
        <ul class="agenda-list">
          <li v-for="item in searchResults" :key="`search-${item.id}`">
            <button type="button" class="agenda-item" @click="jumpToAppointment(item)">
              <time>{{ formatAgendaDateTime(item.startsAt) }}</time>
              <div class="agenda-item__copy">
                <strong>{{ item.patientName }}</strong>
                <span>{{ item.title }}</span>
              </div>
              <ChevronRight class="agenda-item__arrow" aria-hidden="true" />
            </button>
          </li>
        </ul>
      </section>

      <AgendaSchedulePopover
        :open="popoverOpen"
        :anchor="popoverAnchor"
        :slot-data="popoverSlot"
        :patients="patients"
        :saving="popoverSaving"
        :error="popoverError"
        @close="closeSchedulePopover"
        @save="saveFromPopover"
        @expand="expandPopoverToModal"
      />

      <AgendaAppointmentModal
        :open="modalOpen"
        :patients="patients"
        :appointment="editingAppointment"
        :default-date="selectedDate"
        :prefill-patient-id="schedulePrefill.patientId"
        :prefill-starts-at="schedulePrefill.startsAt"
        :prefill-duration-min="schedulePrefill.durationMin"
        :saving="modalSaving"
        :error="modalError"
        @close="closeModal"
        @save="saveAppointment"
        @delete="deleteCurrentAppointment"
      />
    </div>
  </NuxtLayout>
</template>

<script setup>
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue'
import { ChevronRight } from 'lucide-vue-next'
import { authHeaders, verifyAuthSession } from '~/composables/useAuthSession.js'
import { useAdminAgendaTopbar } from '~/composables/useAdminAgendaTopbar.js'
import { useAgenda } from '~/composables/useAgenda.js'
import AgendaAppointmentModal from '~/components/agenda/AgendaAppointmentModal.vue'
import AgendaGoogleCalendar from '~/components/agenda/AgendaGoogleCalendar.vue'
import AgendaSchedulePopover from '~/components/agenda/AgendaSchedulePopover.vue'
import {
  addDays,
  endOfMonth,
  endOfWeek,
  formatAgendaDateTime,
  parseDateKey,
  startOfMonth,
  startOfWeek,
  toDateKey,
} from '~/utils/agenda-calendar.js'

const apiBase = useApiBase()
const route = useRoute()
const {
  fetchAppointments,
  searchAppointments,
  createAppointment,
  updateAppointment,
  deleteAppointment,
} = useAgenda()
const { refreshAdminAgendaTopbar } = useAdminAgendaTopbar()

const loading = ref(true)
const loadError = ref('')
const appointments = ref([])
const patients = ref([])
const searchQuery = ref('')
const searchResults = ref([])
const anchorDate = ref(new Date())
const selectedDayKey = ref(toDateKey(new Date()))
const calendarViewMode = ref('week')

const modalOpen = ref(false)
const modalSaving = ref(false)
const modalError = ref('')
const editingAppointment = ref(null)
const schedulePrefill = ref({ patientId: '', startsAt: '', durationMin: 60 })

const popoverOpen = ref(false)
const popoverSaving = ref(false)
const popoverError = ref('')
const popoverAnchor = ref({ x: 0, y: 0, width: 0, height: 0 })
const popoverSlot = ref({ dayKey: '', startsAt: '', durationMin: 60, endMinutes: null, patientId: '' })
const calendarRef = ref(null)

const selectedDate = computed(() => parseDateKey(selectedDayKey.value) || new Date())

async function loadPatients() {
  const data = await $fetch(`${apiBase.value}/users`, { headers: authHeaders() })
  patients.value = Array.isArray(data)
    ? data.filter((user) => user.role === 'PACIENTE')
    : []
}

function getRangeForView() {
  if (calendarViewMode.value === 'day') {
    const day = anchorDate.value
    const start = new Date(day)
    start.setHours(0, 0, 0, 0)
    const end = addDays(start, 1)
    return { start, end }
  }
  if (calendarViewMode.value === 'month') {
    return {
      start: startOfMonth(anchorDate.value),
      end: addDays(endOfMonth(anchorDate.value), 1),
    }
  }
  return {
    start: startOfWeek(anchorDate.value, 0),
    end: addDays(endOfWeek(anchorDate.value, 0), 1),
  }
}

async function loadAppointmentsRange() {
  loading.value = true
  loadError.value = ''
  try {
    const { start, end } = getRangeForView()
    const data = await fetchAppointments({
      from: start.toISOString(),
      to: end.toISOString(),
    })
    appointments.value = data?.appointments || []
  } catch {
    loadError.value = 'Não foi possível carregar a agenda.'
    appointments.value = []
  } finally {
    loading.value = false
  }
}

async function runSearch() {
  const q = searchQuery.value.trim()
  if (!q) {
    searchResults.value = []
    return
  }
  try {
    const data = await searchAppointments(q, 12)
    searchResults.value = data?.appointments || []
  } catch {
    searchResults.value = []
  }
}

function onAnchorDateChange(date) {
  anchorDate.value = date
  selectedDayKey.value = toDateKey(date)
}

function focusFirstSearchMatch() {
  void runSearch()
  if (searchResults.value[0]) jumpToAppointment(searchResults.value[0])
}

function jumpToAppointment(item) {
  if (!item?.startsAt) return
  const date = new Date(item.startsAt)
  anchorDate.value = date
  selectedDayKey.value = toDateKey(date)
  calendarViewMode.value = 'day'
  searchQuery.value = ''
  searchResults.value = []
}

function openCreateModal() {
  closeSchedulePopover()
  editingAppointment.value = null
  schedulePrefill.value = { patientId: '', startsAt: '', durationMin: 60 }
  modalError.value = ''
  modalOpen.value = true
}

function openSchedulePopover(slot) {
  if (!slot?.startsAt) return
  editingAppointment.value = null
  modalOpen.value = false
  popoverSlot.value = {
    dayKey: slot.dayKey || '',
    startsAt: slot.startsAt,
    durationMin: slot.quickClick ? 60 : (Number(slot.durationMin) || 30),
    endMinutes: slot.endMinutes ?? null,
    patientId: slot.patientId || '',
  }
  popoverAnchor.value = slot.anchor || { x: 0, y: 0, width: 0, height: 40 }
  if (slot.dayKey) selectedDayKey.value = slot.dayKey
  popoverError.value = ''
  popoverOpen.value = true
}

function closeSchedulePopover() {
  popoverOpen.value = false
  popoverError.value = ''
  calendarRef.value?.clearSelectionPreview?.()
}

function expandPopoverToModal(formData = {}) {
  schedulePrefill.value = {
    patientId: formData.patientId || popoverSlot.value.patientId || '',
    startsAt: popoverSlot.value.startsAt || '',
    durationMin: Number(formData.durationMin ?? popoverSlot.value.durationMin) || 60,
  }
  if (popoverSlot.value.dayKey) selectedDayKey.value = popoverSlot.value.dayKey
  closeSchedulePopover()
  modalError.value = ''
  modalOpen.value = true
}

async function saveFromPopover(payload) {
  popoverSaving.value = true
  popoverError.value = ''
  try {
    await createAppointment(payload)
    closeSchedulePopover()
    await loadAppointmentsRange()
    refreshAdminAgendaTopbar()
  } catch (err) {
    popoverError.value = err?.data?.message || 'Não foi possível salvar o agendamento.'
  } finally {
    popoverSaving.value = false
  }
}

function openScheduleModal(slot) {
  openSchedulePopover(slot)
}

function openEditModal(item) {
  closeSchedulePopover()
  editingAppointment.value = item
  schedulePrefill.value = { patientId: '', startsAt: '', durationMin: 60 }
  modalError.value = ''
  modalOpen.value = true
}

function closeModal() {
  modalOpen.value = false
  editingAppointment.value = null
  schedulePrefill.value = { patientId: '', startsAt: '', durationMin: 60 }
  modalError.value = ''
}

async function saveAppointment(payload) {
  modalSaving.value = true
  modalError.value = ''
  try {
    if (editingAppointment.value?.id) {
      await updateAppointment(editingAppointment.value.id, payload)
    } else {
      await createAppointment(payload)
    }
    closeModal()
    await loadAppointmentsRange()
    refreshAdminAgendaTopbar()
  } catch (err) {
    modalError.value = err?.data?.message || 'Não foi possível salvar o agendamento.'
  } finally {
    modalSaving.value = false
  }
}

async function deleteCurrentAppointment() {
  if (!editingAppointment.value?.id) return
  modalSaving.value = true
  modalError.value = ''
  try {
    await deleteAppointment(editingAppointment.value.id)
    closeModal()
    await loadAppointmentsRange()
    refreshAdminAgendaTopbar()
  } catch (err) {
    modalError.value = err?.data?.message || 'Não foi possível excluir o agendamento.'
  } finally {
    modalSaving.value = false
  }
}

let searchTimer = null
watch(searchQuery, (value) => {
  clearTimeout(searchTimer)
  searchTimer = setTimeout(() => {
    void runSearch()
  }, 260)
})

watch([anchorDate, calendarViewMode], () => {
  void loadAppointmentsRange()
})

onMounted(async () => {
  await verifyAuthSession({ requiredRole: 'NUTRICIONISTA' })
  if (route.query.day) {
    const date = parseDateKey(String(route.query.day))
    if (date) {
      anchorDate.value = date
      selectedDayKey.value = toDateKey(date)
      calendarViewMode.value = 'day'
    }
  }
  await Promise.all([loadPatients(), loadAppointmentsRange()])
})

onBeforeUnmount(() => {
  clearTimeout(searchTimer)
})
</script>

<style scoped>
.agenda-page {
  display: grid;
  gap: 1rem;
  padding-bottom: 1rem;
}

.agenda-search-results {
  padding: 1rem 1.1rem;
  border: 1px solid var(--admin-border, #e8ece9);
  border-radius: var(--cf-radius-control);
  background: #fff;
}

.agenda-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: grid;
  gap: 0.45rem;
}

.agenda-item {
  display: grid;
  grid-template-columns: auto minmax(0, 1fr) auto;
  gap: 0.75rem;
  align-items: center;
  width: 100%;
  padding: 0.75rem 0.85rem;
  border: 1px solid var(--admin-border, #e8ece9);
  border-radius: var(--cf-radius-control);
  background: #fff;
  text-align: left;
  cursor: pointer;
  transition: background 0.15s ease, border-color 0.15s ease;
}

.agenda-item:hover {
  background: rgba(139, 150, 124, 0.08);
  border-color: rgba(139, 150, 124, 0.35);
}

.agenda-item time {
  font-size: 0.8125rem;
  font-weight: 600;
  color: var(--admin-primary, #8b967c);
  white-space: nowrap;
}

.agenda-item__copy {
  min-width: 0;
}

.agenda-item__copy strong {
  display: block;
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--admin-ink, #141414);
}

.agenda-item__copy span {
  display: block;
  margin-top: 0.12rem;
  font-size: 0.75rem;
  color: var(--admin-muted, #66706e);
}

.agenda-item__arrow {
  width: 1rem;
  height: 1rem;
  color: #9ca3af;
}

.agenda-search-results__head {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 0.75rem;
  margin-bottom: 0.75rem;
}

.agenda-search-results__head h2 {
  margin: 0;
  font-size: 0.9375rem;
  font-weight: 600;
}

.agenda-search-results__head span {
  font-size: 0.75rem;
  color: var(--admin-muted, #66706e);
}
</style>

// frontend/app/(admin)/agenda/page.tsx
'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { ChevronRight } from 'lucide-react'
import { ApiError } from '@/lib/api'
import type { AuthUser } from '@/lib/types'
import {
  type AgendaAppointment,
  addDays,
  createAgendaAppointment,
  deleteAgendaAppointment,
  endOfWeek,
  fetchAgendaAppointments,
  fetchPatientsForAgenda,
  formatAgendaTime,
  startOfDay,
  startOfWeek,
  updateAgendaAppointment,
} from '@/lib/agenda'
import {
  AgendaCalendar,
  type AgendaViewMode,
  type ScheduleSlot,
} from '@/components/agenda/AgendaCalendar'
import {
  AgendaAppointmentModal,
  type AgendaSavePayload,
} from '@/components/agenda/AgendaAppointmentModal'
import styles from './agenda.module.scss'

function formatAgendaDateTime(iso: string) {
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return '—'
  return date.toLocaleString('pt-BR', {
    weekday: 'short',
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  })
}

export default function AgendaPage() {
  const [loading, setLoading] = useState(true)
  const [loadError, setLoadError] = useState('')
  const [appointments, setAppointments] = useState<AgendaAppointment[]>([])
  const [patients, setPatients] = useState<AuthUser[]>([])
  const [anchorDate, setAnchorDate] = useState(() => new Date())
  const [viewMode, setViewMode] = useState<AgendaViewMode>('week')
  const [searchQuery, setSearchQuery] = useState('')
  const [searchResults, setSearchResults] = useState<AgendaAppointment[]>([])

  const [modalOpen, setModalOpen] = useState(false)
  const [modalSaving, setModalSaving] = useState(false)
  const [modalError, setModalError] = useState('')
  const [editing, setEditing] = useState<AgendaAppointment | null>(null)
  const [prefill, setPrefill] = useState<{
    patientId?: string
    startsAt?: string
    durationMin?: number
  }>({})

  const range = useMemo(() => {
    if (viewMode === 'day') {
      const start = startOfDay(anchorDate)
      return { start, end: addDays(start, 1) }
    }
    return {
      start: startOfWeek(anchorDate, 0),
      end: addDays(endOfWeek(anchorDate, 0), 1),
    }
  }, [anchorDate, viewMode])

  const loadAppointments = useCallback(async () => {
    setLoading(true)
    setLoadError('')
    try {
      const data = await fetchAgendaAppointments({
        from: range.start.toISOString(),
        to: range.end.toISOString(),
      })
      setAppointments(data.appointments || [])
    } catch (err) {
      const message =
        err instanceof ApiError
          ? err.message
          : err instanceof Error
            ? err.message
            : 'Falha ao carregar a agenda.'
      setLoadError(message)
      setAppointments([])
    } finally {
      setLoading(false)
    }
  }, [range.start, range.end])

  useEffect(() => {
    void loadAppointments()
  }, [loadAppointments])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      try {
        const list = await fetchPatientsForAgenda()
        if (!cancelled) setPatients(list)
      } catch {
        if (!cancelled) setPatients([])
      }
    })()
    return () => {
      cancelled = true
    }
  }, [])

  function openCreateModal() {
    setEditing(null)
    setPrefill({})
    setModalError('')
    setModalOpen(true)
  }

  function openEditModal(item: AgendaAppointment) {
    setEditing(item)
    setPrefill({})
    setModalError('')
    setModalOpen(true)
  }

  function openFromSlot(slot: ScheduleSlot) {
    setEditing(null)
    setPrefill({
      startsAt: slot.startsAt,
      durationMin: slot.durationMin,
    })
    setModalError('')
    setModalOpen(true)
  }

  function closeModal() {
    if (modalSaving) return
    setModalOpen(false)
    setEditing(null)
    setModalError('')
  }

  async function saveAppointment(payload: AgendaSavePayload) {
    setModalSaving(true)
    setModalError('')
    try {
      if (editing?.id) {
        await updateAgendaAppointment(editing.id, {
          patientId: payload.patientId,
          patientName: payload.patientName,
          title: payload.title,
          startsAt: payload.startsAt,
          durationMin: payload.durationMin,
          notes: payload.notes || null,
        })
      } else {
        await createAgendaAppointment({
          patientId: payload.patientId,
          patientName: payload.patientName,
          title: payload.title,
          startsAt: payload.startsAt,
          durationMin: payload.durationMin,
          notes: payload.notes || null,
        })
      }
      setModalOpen(false)
      setEditing(null)
      await loadAppointments()
    } catch (err) {
      setModalError(
        err instanceof Error ? err.message : 'Não foi possível salvar o agendamento.',
      )
    } finally {
      setModalSaving(false)
    }
  }

  async function deleteCurrent() {
    if (!editing?.id) return
    if (!window.confirm('Excluir este agendamento?')) return
    setModalSaving(true)
    setModalError('')
    try {
      await deleteAgendaAppointment(editing.id)
      setModalOpen(false)
      setEditing(null)
      await loadAppointments()
    } catch (err) {
      setModalError(
        err instanceof Error ? err.message : 'Não foi possível excluir o agendamento.',
      )
    } finally {
      setModalSaving(false)
    }
  }

  function runSearch() {
    const q = searchQuery.trim().toLowerCase()
    if (!q) {
      setSearchResults([])
      return
    }
    const results = appointments
      .filter((item) => {
        const name = (item.patientName || '').toLowerCase()
        const title = (item.title || '').toLowerCase()
        const notes = (item.notes || '').toLowerCase()
        return name.includes(q) || title.includes(q) || notes.includes(q)
      })
      .slice(0, 20)
    setSearchResults(results)
  }

  function jumpToAppointment(item: AgendaAppointment) {
    setAnchorDate(new Date(item.startsAt))
    setViewMode('day')
    openEditModal(item)
  }

  return (
    <div className={`admin-shell ${styles.page}`}>
      <AgendaCalendar
        loading={loading}
        loadError={loadError}
        appointments={appointments}
        anchorDate={anchorDate}
        searchQuery={searchQuery}
        viewMode={viewMode}
        onAnchorChange={setAnchorDate}
        onSearchChange={setSearchQuery}
        onSearchSubmit={runSearch}
        onViewModeChange={setViewMode}
        onNewAppointment={openCreateModal}
        onOpenAppointment={openEditModal}
        onScheduleSlot={openFromSlot}
      />

      {searchResults.length > 0 ? (
        <section className={`admin-shell-card ${styles.searchResults}`}>
          <header className={styles.searchHead}>
            <h2>Resultados da busca</h2>
            <span>{searchResults.length} encontrado(s)</span>
          </header>
          <ul className={styles.searchList}>
            {searchResults.map((item) => (
              <li key={item.id}>
                <button type="button" className={styles.searchItem} onClick={() => jumpToAppointment(item)}>
                  <time>
                    {formatAgendaDateTime(item.startsAt)} · {formatAgendaTime(item.startsAt)}
                  </time>
                  <div>
                    <strong>{item.patientName}</strong>
                    <span>{item.title}</span>
                  </div>
                  <ChevronRight size={16} aria-hidden />
                </button>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <AgendaAppointmentModal
        open={modalOpen}
        patients={patients}
        appointment={editing}
        defaultDate={anchorDate}
        prefill={prefill}
        saving={modalSaving}
        error={modalError}
        onClose={closeModal}
        onSave={saveAppointment}
        onDelete={editing ? deleteCurrent : undefined}
      />
    </div>
  )
}
