// frontend/components/whatsapp/WhatsappBroadcastCreateModal.tsx
'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { Check, ChevronRight, Loader, X } from 'lucide-react'
import {
  BROADCAST_DELAY_PRESETS,
  BROADCAST_FLOW_OPTIONS,
  filterDispatchContactsBySearch,
  filterDispatchContactsBySegment,
  type BroadcastFormPayload,
  type DelayPreset,
  type DispatchContact,
  type SegmentFilter,
} from '@/lib/whatsapp/dispatch-contacts'
import styles from './WhatsappBroadcastCreateModal.module.scss'

// ─── Types ────────────────────────────────────────────────────────────────────

interface WhatsappLabel {
  id: string
  name: string
  colorHex: string
}

interface Props {
  open: boolean
  contacts: DispatchContact[]
  selectedIds: string[]
  searchQuery: string
  loadingContacts: boolean
  submitting: boolean
  labels?: WhatsappLabel[]
  onClose: () => void
  onToggleContact: (id: string) => void
  onUpdateSearchQuery: (q: string) => void
  onResetSelection: () => void
  onSubmit: (payload: BroadcastFormPayload) => void
}

interface FormState {
  info: string
  flowId: string
  text: string
  delayMode: 'smart' | 'manual'
  delayPreset: string
  manualDelaySeconds: number
  scheduleLater: boolean
  scheduledAt: string
}

const defaultForm = (): FormState => ({
  info: '',
  flowId: 'text',
  text: '',
  delayMode: 'smart',
  delayPreset: 'very_short',
  manualDelaySeconds: 20,
  scheduleLater: false,
  scheduledAt: '',
})

// ─── Helpers ──────────────────────────────────────────────────────────────────

function scheduleMinValue(): string {
  const now = new Date()
  const y = now.getFullYear()
  const m = String(now.getMonth() + 1).padStart(2, '0')
  const d = String(now.getDate()).padStart(2, '0')
  const h = String(now.getHours()).padStart(2, '0')
  const min = String(now.getMinutes()).padStart(2, '0')
  return `${y}-${m}-${d}T${h}:${min}`
}

function resolveDelayRange(form: FormState): { delayMin: number; delayMax: number } {
  if (form.delayMode === 'manual') {
    const seconds = Math.max(1, form.manualDelaySeconds || 1)
    return { delayMin: seconds, delayMax: seconds }
  }
  const preset: DelayPreset =
    BROADCAST_DELAY_PRESETS.find((p) => p.id === form.delayPreset) ?? BROADCAST_DELAY_PRESETS[0]
  return { delayMin: preset.min, delayMax: preset.max }
}

// ─── Component ────────────────────────────────────────────────────────────────

export function WhatsappBroadcastCreateModal({
  open,
  contacts,
  selectedIds,
  searchQuery,
  loadingContacts,
  submitting,
  labels = [],
  onClose,
  onToggleContact,
  onUpdateSearchQuery,
  onResetSelection,
  onSubmit,
}: Props) {
  const [form, setForm] = useState<FormState>(defaultForm)
  const [segmentFilters, setSegmentFilters] = useState<SegmentFilter[]>([])
  const [applyFiltersTogether, setApplyFiltersTogether] = useState(true)
  const [showContacts, setShowContacts] = useState(false)
  const [filterMenuOpen, setFilterMenuOpen] = useState(false)
  const [labelPickerOpen, setLabelPickerOpen] = useState(false)
  const [appliedSearch, setAppliedSearch] = useState('')
  const filterMenuRef = useRef<HTMLDivElement>(null)
  const filterMenuAltRef = useRef<HTMLDivElement>(null)

  const resetForm = useCallback(() => {
    setForm(defaultForm())
    setSegmentFilters([])
    setApplyFiltersTogether(true)
    setShowContacts(false)
    setFilterMenuOpen(false)
    setLabelPickerOpen(false)
    setAppliedSearch('')
  }, [])

  useEffect(() => {
    if (open) resetForm()
  }, [open, resetForm])

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      const refs = [filterMenuRef.current, filterMenuAltRef.current].filter(Boolean)
      if (refs.some((r) => r?.contains(e.target as Node))) return
      setFilterMenuOpen(false)
      setLabelPickerOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [])

  const segmentedContacts = filterDispatchContactsBySegment(contacts, segmentFilters, applyFiltersTogether)
  const pickerPool = segmentFilters.length ? segmentedContacts : contacts
  const filteredContacts = filterDispatchContactsBySearch(pickerPool, appliedSearch)

  const selectedSet = new Set(selectedIds)
  const allowedIds = new Set(pickerPool.map((c) => c.id))
  const recipientCount = selectedIds.filter((id) => allowedIds.has(id)).length

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    const { delayMin, delayMax } = resolveDelayRange(form)
    const recipientJids = pickerPool
      .filter((c) => selectedSet.has(c.id))
      .map((c) => c.jid)
      .filter(Boolean)

    onSubmit({
      info: form.info.trim(),
      text: form.text.trim(),
      flowId: form.flowId,
      delayMin,
      delayMax,
      scheduleLater: form.scheduleLater,
      scheduledAt: form.scheduledAt,
      segmentFilters: [...segmentFilters],
      applyFiltersTogether,
      recipientJids,
    })
  }

  const addLabelFilter = (label: WhatsappLabel) => {
    if (!label?.id) return
    if (segmentFilters.some((f) => f.type === 'label' && f.labelId === label.id)) return
    setSegmentFilters((prev) => [
      ...prev,
      { id: `label-${label.id}-${Date.now()}`, type: 'label', labelId: label.id, labelName: label.name },
    ])
    setFilterMenuOpen(false)
    setLabelPickerOpen(false)
    onResetSelection()
  }

  const removeFilter = (id: string) => {
    setSegmentFilters((prev) => prev.filter((f) => f.id !== id))
    onResetSelection()
  }

  const resetFilters = () => {
    setSegmentFilters([])
    setFilterMenuOpen(false)
    setLabelPickerOpen(false)
    onResetSelection()
  }

  if (!open) return null

  return (
    <div className={styles.overlay} onMouseDown={(e) => { if (e.target === e.currentTarget) onClose() }}>
      <div className={styles.modal} role="dialog" aria-labelledby="broadcast-modal-title">
        <header className={styles.header}>
          <h2 id="broadcast-modal-title">Criar Transmissão</h2>
          <button type="button" className={styles.closeBtn} aria-label="Fechar" onClick={onClose}>
            <X />
          </button>
        </header>

        <form className={styles.body} onSubmit={handleSubmit}>
          <div className={styles.columns}>
            {/* ── Painel Configurações ── */}
            <section className={`${styles.panel} ${styles.panelSettings}`}>
              <div className={styles.fields}>
                <div className={styles.fieldFloat}>
                  <label htmlFor="bc-name">Nome</label>
                  <input
                    id="bc-name"
                    type="text"
                    className={`${styles.input} ${styles.withLabel}`}
                    placeholder="Nome"
                    required
                    value={form.info}
                    onChange={(e) => setForm((f) => ({ ...f, info: e.target.value }))}
                  />
                </div>

                <div className={styles.fieldFloat}>
                  <label htmlFor="bc-flow">Fluxo</label>
                  <select
                    id="bc-flow"
                    className={`${styles.select} ${styles.withLabel}`}
                    value={form.flowId}
                    onChange={(e) => setForm((f) => ({ ...f, flowId: e.target.value }))}
                  >
                    {BROADCAST_FLOW_OPTIONS.map((opt) => (
                      <option key={opt.id} value={opt.id}>{opt.label}</option>
                    ))}
                  </select>
                </div>

                {form.flowId === 'text' && (
                  <div className={styles.fieldFloat}>
                    <label htmlFor="bc-message">Mensagem</label>
                    <textarea
                      id="bc-message"
                      className={`${styles.textarea} ${styles.withLabel}`}
                      rows={3}
                      placeholder="Digite a mensagem da transmissão..."
                      required
                      value={form.text}
                      onChange={(e) => setForm((f) => ({ ...f, text: e.target.value }))}
                    />
                  </div>
                )}

                <div className={styles.delayField}>
                  <span className={styles.delayTitle}>Atraso</span>

                  <div className={styles.delayModeRow}>
                    <label className={styles.radio}>
                      <input
                        type="radio"
                        value="smart"
                        checked={form.delayMode === 'smart'}
                        onChange={() => setForm((f) => ({ ...f, delayMode: 'smart' }))}
                      />
                      <span>Atraso inteligente</span>
                    </label>
                    <label className={styles.radio}>
                      <input
                        type="radio"
                        value="manual"
                        checked={form.delayMode === 'manual'}
                        onChange={() => setForm((f) => ({ ...f, delayMode: 'manual' }))}
                      />
                      <span>Atraso manual</span>
                    </label>
                  </div>

                  <p className={styles.helpText}>
                    Defina o atraso com o qual sua transmissão funcionará. Quanto maior o atraso,
                    menos provável que seja confundida com spam, mas transmissões grandes podem levar mais tempo.
                  </p>

                  {form.delayMode === 'smart' ? (
                    <div>
                      {BROADCAST_DELAY_PRESETS.map((preset) => (
                        <label key={preset.id} className={`${styles.radio} ${styles.radioBlock}`}>
                          <input
                            type="radio"
                            value={preset.id}
                            checked={form.delayPreset === preset.id}
                            onChange={() => setForm((f) => ({ ...f, delayPreset: preset.id }))}
                          />
                          <span>{preset.label}</span>
                        </label>
                      ))}
                    </div>
                  ) : (
                    <div className={styles.manualDelay}>
                      <input
                        type="number"
                        min={1}
                        max={600}
                        className={`${styles.input} ${styles.manualDelayInput}`}
                        value={form.manualDelaySeconds}
                        onChange={(e) => setForm((f) => ({ ...f, manualDelaySeconds: Number(e.target.value) }))}
                        required
                      />
                      <span className={styles.manualDelaySuffix}>Segundos</span>
                    </div>
                  )}
                </div>
              </div>
            </section>

            {/* ── Painel Segmentação ── */}
            <section className={`${styles.panel} ${styles.panelSegment}`}>
              <div className={styles.segHead}>
                <h3>Segmentação</h3>
                <button
                  type="button"
                  className={styles.segLink}
                  onClick={() => setShowContacts((v) => !v)}
                >
                  {showContacts ? 'Ocultar pacientes' : 'Mostrar pacientes'}
                </button>
              </div>

              <p className={styles.segCount}>
                Pacientes que receberão esta transmissão:{' '}
                <strong>{recipientCount}</strong>
              </p>

              {segmentFilters.length > 0 && (
                <div className={styles.segToolbar}>
                  <div ref={filterMenuAltRef} className={styles.filterMenuWrap}>
                    <button
                      type="button"
                      className={styles.filterAdd}
                      onClick={(e) => { e.stopPropagation(); setFilterMenuOpen((v) => !v); setLabelPickerOpen(false) }}
                    >
                      Adicionar filtro
                    </button>
                    {filterMenuOpen && (
                      <FilterMenu
                        labels={labels}
                        labelPickerOpen={labelPickerOpen}
                        onOpenLabelPicker={() => setLabelPickerOpen(true)}
                        onAddLabel={addLabelFilter}
                        styles={styles}
                      />
                    )}
                  </div>

                  <label className={`${styles.toggle} ${applyFiltersTogether ? styles.toggleChecked : ''}`}>
                    <input
                      type="checkbox"
                      checked={applyFiltersTogether}
                      onChange={(e) => setApplyFiltersTogether(e.target.checked)}
                    />
                    <span className={styles.toggleTrack} aria-hidden="true" />
                    <span>Aplicar filtros juntos</span>
                  </label>

                  <button type="button" className={styles.resetBtn} onClick={resetFilters}>
                    <X />
                    Redefinir tudo
                  </button>
                </div>
              )}

              {segmentFilters.length > 0 && (
                <div className={styles.filterTags}>
                  {segmentFilters.map((f) => (
                    <span key={f.id} className={styles.filterTag}>
                      {f.type === 'label' ? `Etiqueta: ${f.labelName}` : f.labelName}
                      <button type="button" aria-label="Remover filtro" onClick={() => removeFilter(f.id)}>×</button>
                    </span>
                  ))}
                </div>
              )}

              {showContacts ? (
                <div>
                  <div className={styles.contactSearch}>
                    <input
                      type="text"
                      className={styles.contactSearchInput}
                      placeholder="Buscar contato..."
                      value={searchQuery}
                      onChange={(e) => onUpdateSearchQuery(e.target.value)}
                      onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); setAppliedSearch(searchQuery.trim()) } }}
                    />
                    <button
                      type="button"
                      className={styles.filterAdd}
                      onClick={() => setAppliedSearch(searchQuery.trim())}
                    >
                      Buscar
                    </button>
                  </div>
                  <ContactList
                    contacts={filteredContacts}
                    selectedSet={selectedSet}
                    loading={loadingContacts}
                    onToggle={onToggleContact}
                    styles={styles}
                  />
                </div>
              ) : segmentFilters.length === 0 ? (
                <div className={styles.segEmpty}>
                  <p>Adicionar filtros para refinar seu público</p>
                  <div ref={filterMenuRef} className={styles.filterMenuWrap}>
                    <button
                      type="button"
                      className={`${styles.filterAdd} ${styles.filterAddDashed}`}
                      onClick={(e) => { e.stopPropagation(); setFilterMenuOpen((v) => !v); setLabelPickerOpen(false) }}
                    >
                      Adicionar filtro
                    </button>
                    {filterMenuOpen && (
                      <FilterMenu
                        labels={labels}
                        labelPickerOpen={labelPickerOpen}
                        onOpenLabelPicker={() => setLabelPickerOpen(true)}
                        onAddLabel={addLabelFilter}
                        styles={styles}
                      />
                    )}
                  </div>
                </div>
              ) : null}
            </section>
          </div>

          {/* ── Footer ── */}
          <footer className={styles.footer}>
            <label className={styles.scheduleCheck}>
              <input
                type="checkbox"
                checked={form.scheduleLater}
                onChange={(e) => setForm((f) => ({ ...f, scheduleLater: e.target.checked }))}
              />
              <span>Definir hora e executar depois</span>
            </label>

            <div className={styles.footerRight}>
              {form.scheduleLater && (
                <div className={styles.scheduleField}>
                  <label htmlFor="bc-scheduled-at">Agendar para</label>
                  <input
                    id="bc-scheduled-at"
                    type="datetime-local"
                    className={styles.scheduleInput}
                    min={scheduleMinValue()}
                    value={form.scheduledAt}
                    onChange={(e) => setForm((f) => ({ ...f, scheduledAt: e.target.value }))}
                  />
                </div>
              )}
              <button
                type="submit"
                className={styles.submitBtn}
                disabled={submitting || recipientCount === 0}
              >
                {submitting && <Loader className={styles.spin} />}
                Iniciar agora
              </button>
            </div>
          </footer>
        </form>
      </div>
    </div>
  )
}

// ─── Sub-components ───────────────────────────────────────────────────────────

interface FilterMenuProps {
  labels: WhatsappLabel[]
  labelPickerOpen: boolean
  onOpenLabelPicker: () => void
  onAddLabel: (label: WhatsappLabel) => void
  styles: Record<string, string>
}

function FilterMenu({ labels, labelPickerOpen, onOpenLabelPicker, onAddLabel, styles }: FilterMenuProps) {
  return (
    <div className={styles.filterMenu}>
      <p className={styles.filterMenuSection}>Adicionar filtros</p>
      <button
        type="button"
        className={styles.filterMenuItem}
        onClick={(e) => { e.stopPropagation(); onOpenLabelPicker() }}
      >
        Etiqueta
        <ChevronRight />
      </button>
      {['Sequências', 'Telefone', 'Data criação', 'Campo personalizado'].map((item) => (
        <button
          key={item}
          type="button"
          className={styles.filterMenuItem}
          disabled
        >
          {item}
          <ChevronRight />
        </button>
      ))}
      {labelPickerOpen && (
        <div className={`${styles.submenu} ${styles.submenuOpen}`}>
          {labels.length === 0 ? (
            <p className={styles.submenuEmpty}>Nenhuma etiqueta cadastrada.</p>
          ) : (
            labels.map((label) => (
              <button
                key={label.id}
                type="button"
                className={styles.submenuItem}
                onClick={(e) => { e.stopPropagation(); onAddLabel(label) }}
              >
                <span className={styles.submenuDot} style={{ background: label.colorHex }} />
                {label.name}
              </button>
            ))
          )}
        </div>
      )}
    </div>
  )
}

interface ContactListProps {
  contacts: DispatchContact[]
  selectedSet: Set<string>
  loading: boolean
  onToggle: (id: string) => void
  styles: Record<string, string>
}

function ContactList({ contacts, selectedSet, loading, onToggle, styles }: ContactListProps) {
  if (loading) {
    return (
      <div className={styles.contactsLoading}>
        <Loader className={styles.spin} style={{ width: 18, height: 18 }} />
        Carregando contatos...
      </div>
    )
  }
  if (contacts.length === 0) {
    return <div className={styles.contactsEmpty}>Nenhum contato encontrado.</div>
  }
  return (
    <div className={styles.contactList}>
      {contacts.map((contact) => {
        const selected = selectedSet.has(contact.id)
        const initial = String(contact.name || '?').charAt(0).toUpperCase()
        return (
          <div
            key={contact.id}
            className={`${styles.contactItem} ${selected ? styles.contactItemSelected : ''}`}
            onClick={() => onToggle(contact.id)}
          >
            <div className={styles.contactAvatar}>
              {contact.avatarUrl ? (
                <img src={contact.avatarUrl} alt={contact.name} />
              ) : (
                <span>{initial}</span>
              )}
            </div>
            <div className={styles.contactMeta}>
              <strong>{contact.name}</strong>
              <small>{contact.displayNumber}</small>
            </div>
            <div className={`${styles.contactCheck} ${selected ? styles.contactCheckSelected : ''}`}>
              {selected && <Check />}
            </div>
          </div>
        )
      })}
    </div>
  )
}

// frontend/components/whatsapp/WhatsappBroadcastCreateModal.vue
<template>
  <div v-if="modelValue" class="broadcast-modal-overlay" @click.self="$emit('update:modelValue', false)">
    <div class="broadcast-modal modal-card" role="dialog" aria-labelledby="broadcast-modal-title">
      <header class="broadcast-modal__header">
        <h2 id="broadcast-modal-title">Criar Transmissão</h2>
        <button type="button" class="broadcast-modal__close" aria-label="Fechar" @click="$emit('update:modelValue', false)">
          <X class="broadcast-modal__close-icon" />
        </button>
      </header>

      <form class="broadcast-modal__body" @submit.prevent="onSubmit">
        <div class="broadcast-modal__columns">
          <section class="broadcast-modal__panel broadcast-modal__panel--settings">
            <div class="modal-fields">
              <div class="field field--float">
                <label for="broadcast-name">Nome</label>
                <input
                  id="broadcast-name"
                  v-model="form.info"
                  type="text"
                  class="cf-squircle cf-squircle--control"
                  placeholder="Nome"
                  required
                >
              </div>

              <div class="field field--float">
                <label for="broadcast-flow">Fluxo</label>
                <SharedCfSelect
                  id="broadcast-flow"
                  v-model="form.flowId"
                  :options="flowSelectOptions"
                />
              </div>

              <div v-if="form.flowId === 'text'" class="field field--float">
                <label for="broadcast-message">Mensagem</label>
                <textarea
                  id="broadcast-message"
                  v-model="form.text"
                  class="cf-squircle cf-squircle--control"
                  rows="3"
                  placeholder="Digite a mensagem da transmissão..."
                  required
                />
              </div>

              <div class="field broadcast-delay-field">
                <span class="broadcast-delay-field__title">Atraso</span>

                <div class="broadcast-radio-row broadcast-delay-mode-row">
                  <label class="broadcast-radio">
                    <input v-model="form.delayMode" type="radio" value="smart">
                    <span>Atraso inteligente</span>
                  </label>
                  <label class="broadcast-radio">
                    <input v-model="form.delayMode" type="radio" value="manual">
                    <span>Atraso manual</span>
                  </label>
                </div>

                <p class="broadcast-help">
                  Defina o atraso de tempo com o qual sua transmissão funcionará. Quanto maior o atraso,
                  menos provável que sua transmissão seja confundida com spam, mas transmissões grandes
                  podem levar muito tempo.
                </p>

                <div v-if="form.delayMode === 'smart'" class="broadcast-delay-list">
                  <label v-for="preset in delayPresets" :key="preset.id" class="broadcast-radio broadcast-radio--block">
                    <input v-model="form.delayPreset" type="radio" :value="preset.id">
                    <span>{{ preset.label }}</span>
                  </label>
                </div>

                <div v-else class="broadcast-manual-delay">
                  <input
                    id="broadcast-delay-seconds"
                    v-model.number="form.manualDelaySeconds"
                    type="number"
                    min="1"
                    max="600"
                    class="cf-squircle cf-squircle--control broadcast-manual-delay__input"
                    required
                  >
                  <span class="broadcast-manual-delay__suffix">Segundos</span>
                </div>
              </div>
            </div>
          </section>

          <section class="broadcast-modal__panel broadcast-modal__panel--segment">
            <div class="broadcast-segment__head">
              <h3>Segmentação</h3>
              <button type="button" class="broadcast-link" @click="showUsersPanel = !showUsersPanel">
                {{ showUsersPanel ? 'Ocultar pacientes' : 'Mostrar pacientes' }}
              </button>
            </div>

            <p class="broadcast-segment__count">
              Pacientes que receberão esta transmissão: <strong>{{ recipientCount }}</strong>
            </p>

            <div v-if="segmentFilters.length" class="broadcast-segment__toolbar">
              <div ref="filterMenuRootAlt" class="broadcast-filter-menu-wrap">
                <button type="button" class="broadcast-filter-add" @click.stop="toggleFilterMenu">
                  Adicionar filtro
                </button>
                <div v-if="filterMenuOpen" class="broadcast-filter-menu">
                  <p class="broadcast-filter-menu__section">Adicionar filtros</p>
                  <button type="button" class="broadcast-filter-menu__item" @click.stop="openLabelPicker">
                    Etiqueta
                    <ChevronRight class="broadcast-filter-menu__chev" />
                  </button>
                  <div v-if="labelPickerOpen" class="broadcast-filter-submenu broadcast-filter-submenu--open">
                    <button
                      v-for="label in labelOptions"
                      :key="label.id"
                      type="button"
                      class="broadcast-filter-submenu__item"
                      @click.stop="addLabelFilter(label)"
                    >
                      <span class="broadcast-filter-submenu__dot" :style="{ background: label.colorHex }" />
                      {{ label.name }}
                    </button>
                    <p v-if="!labelOptions.length" class="broadcast-filter-submenu__empty">Nenhuma etiqueta cadastrada.</p>
                  </div>
                </div>
              </div>

              <label class="broadcast-toggle">
                <input v-model="applyFiltersTogether" type="checkbox">
                <span class="broadcast-toggle__track" aria-hidden="true" />
                <span>Aplicar filtros juntos</span>
              </label>

              <button type="button" class="broadcast-reset" @click="resetFilters">
                <X class="broadcast-reset__icon" aria-hidden="true" />
                Redefinir tudo
              </button>
            </div>

            <div v-if="segmentFilters.length" class="broadcast-filter-tags">
              <span v-for="filter in segmentFilters" :key="filter.id" class="broadcast-filter-tag">
                {{ filterLabel(filter) }}
                <button type="button" aria-label="Remover filtro" @click="removeFilter(filter.id)">×</button>
              </span>
            </div>

            <div v-if="showUsersPanel" class="broadcast-users-panel">
              <WhatsappContactPicker
                :contacts="filteredPickerContacts"
                :selected-ids="selectedIds"
                :search-query="searchQuery"
                :loading="loadingContacts"
                @toggle="$emit('toggle-contact', $event)"
                @update:search-query="$emit('update:search-query', $event)"
                @search="applyPickerSearch"
              />
            </div>

            <div v-else-if="!segmentFilters.length" class="broadcast-segment__empty">
              <p>Adicionar filtros para refinar seu público</p>
              <div ref="filterMenuRoot" class="broadcast-filter-menu-wrap">
                <button type="button" class="broadcast-filter-add broadcast-filter-add--dashed" @click.stop="toggleFilterMenu">
                  Adicionar filtro
                </button>

                <div v-if="filterMenuOpen" class="broadcast-filter-menu">
                  <button type="button" class="broadcast-filter-menu__item is-disabled" disabled>
                    Pesquisas salvas
                    <ChevronRight class="broadcast-filter-menu__chev" />
                  </button>
                  <p class="broadcast-filter-menu__section">Adicionar filtros</p>
                  <button
                    type="button"
                    class="broadcast-filter-menu__item"
                    @mouseenter="hoveredFilter = 'label'"
                    @click.stop="openLabelPicker"
                  >
                    Etiqueta
                    <ChevronRight class="broadcast-filter-menu__chev" />
                  </button>
                  <button
                    v-for="item in disabledFilterItems"
                    :key="item"
                    type="button"
                    class="broadcast-filter-menu__item is-disabled"
                    disabled
                  >
                    {{ item }}
                    <ChevronRight class="broadcast-filter-menu__chev" />
                  </button>

                  <div
                    v-if="hoveredFilter === 'label' || labelPickerOpen"
                    class="broadcast-filter-submenu"
                  >
                    <button
                      v-for="label in labelOptions"
                      :key="label.id"
                      type="button"
                      class="broadcast-filter-submenu__item"
                      @click.stop="addLabelFilter(label)"
                    >
                      <span class="broadcast-filter-submenu__dot" :style="{ background: label.colorHex }" />
                      {{ label.name }}
                    </button>
                    <p v-if="!labelOptions.length" class="broadcast-filter-submenu__empty">Nenhuma etiqueta cadastrada.</p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        <footer class="broadcast-modal__footer">
          <label class="broadcast-schedule-check">
            <input v-model="form.scheduleLater" type="checkbox">
            <span>Definir hora e executar depois</span>
          </label>

          <div class="broadcast-modal__footer-right">
            <div v-if="form.scheduleLater" class="field field--float broadcast-schedule-field">
              <label for="broadcast-scheduled-at">Agendar para</label>
              <SharedCfDateTimeInput
                id="broadcast-scheduled-at"
                v-model="form.scheduledAt"
                :min="scheduleMinValue"
                placeholder="dd/mm/aaaa às hh:mm"
              />
            </div>
            <button type="submit" class="btn btn-primary" :disabled="submitting || recipientCount === 0">
              <Loader v-if="submitting" class="spin icon-small" />
              Iniciar agora
            </button>
          </div>
        </footer>
      </form>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { ChevronRight, Loader, X } from 'lucide-vue-next'
import WhatsappContactPicker from '~/components/whatsapp/WhatsappContactPicker.vue'
import {
  BROADCAST_DELAY_PRESETS,
  BROADCAST_FLOW_OPTIONS,
  filterDispatchContactsBySearch,
  filterDispatchContactsBySegment,
} from '~/composables/whatsapp/useWhatsappDispatchContacts.js'
import { loadWhatsappLabels, whatsappLabelsById, whatsappLabelsOrder } from '~/composables/whatsapp/useWhatsappLabels.js'

const props = defineProps({
  modelValue: { type: Boolean, default: false },
  contacts: { type: Array, default: () => [] },
  selectedIds: { type: Array, default: () => [] },
  searchQuery: { type: String, default: '' },
  loadingContacts: { type: Boolean, default: false },
  submitting: { type: Boolean, default: false },
})

const emit = defineEmits([
  'update:modelValue',
  'submit',
  'toggle-contact',
  'update:search-query',
  'reset-selection',
])

const delayPresets = BROADCAST_DELAY_PRESETS
const flowSelectOptions = BROADCAST_FLOW_OPTIONS.map(({ id, label }) => ({ value: id, label }))

const disabledFilterItems = [
  'Sequências',
  'Telefone',
  'Primeiro nome',
  'Sobrenome',
  'Nome completo',
  'Campanha',
  'Data criação',
  'Código de Área',
  'ID do Paciente',
  'Campo personalizado',
]

const form = ref({
  info: '',
  flowId: 'text',
  text: '',
  delayMode: 'smart',
  delayPreset: 'very_short',
  manualDelaySeconds: 20,
  scheduleLater: false,
  scheduledAt: '',
})

const segmentFilters = ref([])
const applyFiltersTogether = ref(true)
const showUsersPanel = ref(false)
const appliedPickerSearch = ref('')
const filterMenuOpen = ref(false)
const labelPickerOpen = ref(false)
const hoveredFilter = ref('')
const filterMenuRoot = ref(null)
const filterMenuRootAlt = ref(null)

const scheduleMinValue = computed(() => {
  const now = new Date()
  const y = now.getFullYear()
  const m = String(now.getMonth() + 1).padStart(2, '0')
  const d = String(now.getDate()).padStart(2, '0')
  const h = String(now.getHours()).padStart(2, '0')
  const min = String(now.getMinutes()).padStart(2, '0')
  return `${y}-${m}-${d}T${h}:${min}`
})

const labelOptions = computed(() =>
  whatsappLabelsOrder.value
    .map((id) => whatsappLabelsById.value?.[id])
    .filter(Boolean),
)

const segmentedContacts = computed(() =>
  filterDispatchContactsBySegment(props.contacts, segmentFilters.value, applyFiltersTogether.value),
)

const segmentContactsForPicker = computed(() => {
  if (segmentFilters.value.length) return segmentedContacts.value
  return props.contacts
})

const filteredPickerContacts = computed(() =>
  filterDispatchContactsBySearch(segmentContactsForPicker.value, appliedPickerSearch.value),
)

const recipientCount = computed(() => {
  const allowed = new Set(segmentContactsForPicker.value.map((item) => item.id))
  return props.selectedIds.filter((id) => allowed.has(id)).length
})

const applyPickerSearch = () => {
  appliedPickerSearch.value = props.searchQuery.trim()
}

const filterLabel = (filter) => {
  if (filter.type === 'label') return `Etiqueta: ${filter.labelName}`
  return filter.labelName || 'Filtro'
}

const resolveDelayRange = () => {
  if (form.value.delayMode === 'manual') {
    const seconds = Math.max(1, Number(form.value.manualDelaySeconds) || 1)
    return { delayMin: seconds, delayMax: seconds }
  }
  const preset = delayPresets.find((item) => item.id === form.value.delayPreset) || delayPresets[0]
  return { delayMin: preset.min, delayMax: preset.max }
}

const toggleFilterMenu = () => {
  filterMenuOpen.value = !filterMenuOpen.value
  labelPickerOpen.value = false
}

const openLabelPicker = () => {
  labelPickerOpen.value = true
  filterMenuOpen.value = true
  hoveredFilter.value = 'label'
}

const addLabelFilter = (label) => {
  if (!label?.id) return
  const exists = segmentFilters.value.some((item) => item.type === 'label' && item.labelId === label.id)
  if (exists) return
  segmentFilters.value.push({
    id: `label-${label.id}-${Date.now()}`,
    type: 'label',
    labelId: label.id,
    labelName: label.name,
  })
  filterMenuOpen.value = false
  labelPickerOpen.value = false
  hoveredFilter.value = ''
  emit('reset-selection')
}

const removeFilter = (id) => {
  segmentFilters.value = segmentFilters.value.filter((item) => item.id !== id)
  emit('reset-selection')
}

const resetFilters = () => {
  segmentFilters.value = []
  filterMenuOpen.value = false
  labelPickerOpen.value = false
  emit('reset-selection')
}

const buildRecipientJids = () => {
  const pool = segmentContactsForPicker.value
  const selected = new Set(props.selectedIds)
  return pool.filter((item) => selected.has(item.id)).map((item) => item.jid).filter(Boolean)
}

const onSubmit = () => {
  const { delayMin, delayMax } = resolveDelayRange()
  emit('submit', {
    info: form.value.info.trim(),
    text: form.value.text.trim(),
    flowId: form.value.flowId,
    delayMin,
    delayMax,
    scheduleLater: form.value.scheduleLater,
    scheduledAt: form.value.scheduledAt,
    segmentFilters: [...segmentFilters.value],
    applyFiltersTogether: applyFiltersTogether.value,
    recipientJids: buildRecipientJids(),
  })
}

const resetForm = () => {
  form.value = {
    info: '',
    flowId: 'text',
    text: '',
    delayMode: 'smart',
    delayPreset: 'very_short',
    manualDelaySeconds: 20,
    scheduleLater: false,
    scheduledAt: '',
  }
  segmentFilters.value = []
  applyFiltersTogether.value = true
  showUsersPanel.value = false
  appliedPickerSearch.value = ''
  filterMenuOpen.value = false
  labelPickerOpen.value = false
}

const onDocumentClick = (event) => {
  const roots = [filterMenuRoot.value, filterMenuRootAlt.value].filter(Boolean)
  if (roots.some((root) => root.contains(event.target))) return
  filterMenuOpen.value = false
  labelPickerOpen.value = false
  hoveredFilter.value = ''
}

watch(
  () => props.modelValue,
  (open) => {
    if (open) {
      resetForm()
      void loadWhatsappLabels({ force: false })
    }
  },
)

onMounted(() => {
  document.addEventListener('click', onDocumentClick)
})

onUnmounted(() => {
  document.removeEventListener('click', onDocumentClick)
})
</script>
