// frontend/components/checkin/CheckinTypeformFlow.tsx
'use client'

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'
import { ArrowRight, Check, ChevronUp, Loader2 } from 'lucide-react'
import {
  normalizeFlowStep,
  type FlowStep,
  type StepApiPayload,
} from '@/lib/checkin-step-schema'
import { FoodMoodPicker } from './FoodMoodPicker'
import styles from './CheckinTypeformFlow.module.scss'

type Props = {
  steps?: Array<Partial<StepApiPayload> & Record<string, unknown>>
  preview?: boolean
  initialStepIndex?: number
  saving?: boolean
  submitted?: boolean
  error?: string
  onStepChange?: (index: number) => void
  onSubmit?: (answers: Record<string, unknown>) => void
}

function formatStepperValue(value: unknown) {
  const n = Number(value ?? 0)
  if (!Number.isFinite(n)) return '0'
  const rounded = Math.round(n * 100) / 100
  if (rounded % 1 === 0) return String(rounded)
  return rounded
    .toFixed(2)
    .replace(/0$/, '')
    .replace(/\.$/, '')
    .replace('.', ',')
}

function stepperConfigForStep(step: FlowStep) {
  const min = Number(step.min)
  const max = Number(step.max)
  const increment = Number(step.step)
  return {
    min: Number.isFinite(min) ? min : 0,
    max: Number.isFinite(max) ? max : 5,
    step: Number.isFinite(increment) && increment > 0 ? increment : 0.25,
    defaultValue: Number.isFinite(Number(step.defaultValue)) ? Number(step.defaultValue) : 0,
    unit: step.unit || '',
  }
}

export function CheckinTypeformFlow({
  steps = [],
  preview = false,
  initialStepIndex = 0,
  saving = false,
  submitted = false,
  error = '',
  onStepChange,
  onSubmit,
}: Props) {
  const flowSteps = useMemo(
    () => (steps.length ? steps : []).map((step, index) => normalizeFlowStep(step, index)),
    [steps],
  )

  const [form, setForm] = useState<Record<string, unknown>>({})
  const [stepIndex, setStepIndex] = useState(0)
  const [submitLocked, setSubmitLocked] = useState(false)
  const textRef = useRef<HTMLTextAreaElement | null>(null)
  const prevStepIdsRef = useRef('')

  const currentStep = flowSteps[stepIndex] || flowSteps[0]
  const stepType = currentStep?.type || 'text'
  const isLastStep = stepIndex === Math.max(0, flowSteps.length - 1)
  const progressPct = flowSteps.length
    ? Math.round(((stepIndex + 1) / flowSteps.length) * 100)
    : 0

  const scaleMin = Math.max(0, Number(currentStep?.min) || 1)
  const scaleMax = Math.max(scaleMin, Number(currentStep?.max) || 5)
  const scaleRange = useMemo(() => {
    const values: number[] = []
    for (let n = scaleMin; n <= scaleMax; n += 1) values.push(n)
    return values
  }, [scaleMin, scaleMax])

  const stepperConfig = useMemo(
    () => (currentStep ? stepperConfigForStep(currentStep) : { min: 0, max: 5, step: 0.25, defaultValue: 0, unit: '' }),
    [currentStep],
  )

  const stepperHint = useMemo(() => {
    const { step } = stepperConfig
    if (stepType === 'water') {
      const label = step % 1 === 0 ? `${step} L` : `${String(step).replace('.', ',')} L`
      return `+${label} por toque`
    }
    if (stepType === 'number') {
      const unit = currentStep?.unit ? ` ${currentStep.unit}` : ''
      return `+${formatStepperValue(step)}${unit} por toque`
    }
    return ''
  }, [stepperConfig, stepType, currentStep?.unit])

  const choiceOptions = useMemo(() => {
    const raw = currentStep?.options
    if (!Array.isArray(raw)) return [] as Array<{ value: string; label: string }>
    return raw.map((item, index) => {
      if (typeof item === 'string') return { value: item, label: item }
      const obj = item as { value?: string; label?: string }
      const value = obj?.value ?? obj?.label ?? `opt_${index}`
      return { value: String(value), label: String(obj?.label ?? value) }
    })
  }, [currentStep?.options])

  const showFootOkButton =
    stepType !== 'text' && (stepType === 'water' || stepType === 'number' || isLastStep)

  const canAdvance = useMemo(() => {
    if (!currentStep) return false
    const value = form[currentStep.id]
    if (stepType === 'food' || stepType === 'exercise' || stepType === 'scale' || stepType === 'choice') {
      return value != null
    }
    if (stepType === 'water' || stepType === 'number') {
      return Number(value) >= stepperConfig.min
    }
    if (stepType === 'text') return String(value || '').trim().length > 0
    return false
  }, [currentStep, form, stepType, stepperConfig.min])

  const actionLocked = saving || submitted || submitLocked
  const submitActionDisabled = actionLocked || (!preview && !canAdvance)

  const okLabel = saving ? 'Salvando...' : isLastStep ? 'Responder' : 'Avançar'
  const okHint = saving ? 'Enviando...' : isLastStep ? 'concluir' : 'continuar'

  const waterUnitLabel = useMemo(() => {
    const value = Number(form[currentStep?.id ?? ''] ?? 0)
    if (stepType === 'water') return value === 1 ? 'litro' : 'litros'
    return currentStep?.unit?.trim() || ''
  }, [form, currentStep, stepType])

  const initForm = useCallback(
    (keepId?: string) => {
      const next: Record<string, unknown> = {}
      for (const step of flowSteps) {
        if (step.type === 'water' || step.type === 'number') {
          next[step.id] = Number.isFinite(Number(step.defaultValue))
            ? Number(step.defaultValue)
            : stepperConfigForStep(step).defaultValue
        } else {
          next[step.id] = null
        }
      }
      setForm(next)
      setSubmitLocked(false)
      if (preview) {
        const fromId = keepId ? flowSteps.findIndex((s) => s.id === keepId) : -1
        const fromProp = Math.min(
          Math.max(0, initialStepIndex),
          Math.max(0, flowSteps.length - 1),
        )
        setStepIndex(fromId >= 0 ? fromId : fromProp)
      } else {
        setStepIndex(0)
      }
    },
    [flowSteps, preview, initialStepIndex],
  )

  useEffect(() => {
    const ids = flowSteps.map((s) => `${s.id}:${s.type}`).join('|')
    if (ids === prevStepIdsRef.current) return
    const previousId = flowSteps[stepIndex]?.id
    prevStepIdsRef.current = ids
    if (saving || submitted) return
    initForm(previousId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [flowSteps, saving, submitted, initForm])

  useEffect(() => {
    if (!preview) return
    const next = Math.min(Math.max(0, initialStepIndex), Math.max(0, flowSteps.length - 1))
    setStepIndex((cur) => (cur === next ? cur : next))
  }, [initialStepIndex, preview, flowSteps.length])

  useEffect(() => {
    if (preview) onStepChange?.(stepIndex)
  }, [stepIndex, preview, onStepChange])

  const resizeTextAnswer = useCallback(() => {
    const el = textRef.current
    if (!el) return
    const value = String(el.value ?? '').trim()
    if (preview && !value) {
      el.style.height = ''
      return
    }
    const style = getComputedStyle(el)
    const fontSize = Number.parseFloat(style.fontSize) || 16
    const lineHeight = Number.parseFloat(style.lineHeight) || fontSize * 1.4
    const padBottom = Number.parseFloat(style.paddingBottom) || 0
    const minHeight = lineHeight + padBottom + 3
    el.style.height = 'auto'
    el.style.height = `${Math.ceil(Math.max(minHeight, el.scrollHeight + 3))}px`
  }, [preview])

  useEffect(() => {
    resizeTextAnswer()
  }, [stepIndex, stepType, form, resizeTextAnswer])

  function nextStep() {
    if (!canAdvance || stepIndex >= flowSteps.length - 1) return
    setStepIndex((i) => i + 1)
  }

  function prevStep() {
    if (stepIndex > 0) setStepIndex((i) => i - 1)
  }

  function submitNow() {
    if (preview) return
    if (saving || submitted || submitLocked) return
    if (!canAdvance) return
    setSubmitLocked(true)
    onSubmit?.(form)
  }

  function handleOk() {
    if (!canAdvance || saving || submitted || submitLocked) return
    if (isLastStep) {
      if (preview) return
      submitNow()
      return
    }
    nextStep()
  }

  function selectValue(id: string, value: unknown, advance = false) {
    if (saving || submitted || submitLocked) return
    setForm((prev) => ({ ...prev, [id]: value }))
    if (isLastStep) {
      if (!preview) window.setTimeout(() => submitNow(), 280)
      return
    }
    if (advance) {
      window.setTimeout(() => {
        setStepIndex((i) => Math.min(i + 1, flowSteps.length - 1))
      }, 320)
    }
  }

  function selectScale(value: number) {
    if (!currentStep) return
    selectValue(currentStep.id, value, true)
  }

  function adjustStepper(delta: number) {
    if (!currentStep) return
    const { min, max } = stepperConfig
    setForm((prev) => {
      const current = Number(prev[currentStep.id] || 0)
      const next = Math.round((current + delta) * 100) / 100
      return { ...prev, [currentStep.id]: Math.max(min, Math.min(max, next)) }
    })
  }

  if (submitted) {
    return (
      <div className={styles.success}>
        <div className={styles.successCircle}>
          <Check className={styles.successIcon} aria-hidden />
        </div>
        <h2 className={styles.successTitle}>Enviado com sucesso!</h2>
        <p className={styles.successText}>
          Suas respostas foram registradas. Redirecionando para o início…
        </p>
      </div>
    )
  }

  if (!flowSteps.length || !currentStep) {
    return null
  }

  return (
    <div className={`${styles.checkin} ${preview ? styles.preview : ''}`}>
      <div
        className={styles.progress}
        role="progressbar"
        aria-valuenow={progressPct}
        aria-valuemin={0}
        aria-valuemax={100}
      >
        <div className={styles.progressFill} style={{ width: `${progressPct}%` }} />
      </div>

      <header className={styles.top}>
        <span className={styles.counter}>
          {stepIndex + 1} / {flowSteps.length}
        </span>
      </header>

      <main className={styles.main}>
        <section
          key={currentStep.id}
          className={`${styles.step} ${stepType === 'text' ? styles.stepText : ''}`}
        >
          <h1 className={styles.question}>{currentStep.question}</h1>
          {currentStep.hint ? <p className={styles.hint}>{currentStep.hint}</p> : null}

          <div className={styles.answer}>
            {stepType === 'food' ? (
              <FoodMoodPicker
                value={typeof form[currentStep.id] === 'number' ? (form[currentStep.id] as number) : null}
                onChange={(v) => selectValue(currentStep.id, v, true)}
              />
            ) : null}

            {stepType === 'water' || stepType === 'number' ? (
              <div className={styles.water}>
                <div className={styles.waterControl}>
                  <button
                    type="button"
                    className={styles.waterBtn}
                    aria-label={`Diminuir ${formatStepperValue(stepperConfig.step)}`}
                    onClick={() => adjustStepper(-stepperConfig.step)}
                  >
                    −
                  </button>
                  <div className={styles.waterValue}>
                    <strong>{formatStepperValue(form[currentStep.id])}</strong>
                    {waterUnitLabel ? <span>{waterUnitLabel}</span> : null}
                  </div>
                  <button
                    type="button"
                    className={styles.waterBtn}
                    aria-label={`Aumentar ${formatStepperValue(stepperConfig.step)}`}
                    onClick={() => adjustStepper(stepperConfig.step)}
                  >
                    +
                  </button>
                </div>
                {stepperHint ? <p className={styles.waterHint}>{stepperHint}</p> : null}
              </div>
            ) : null}

            {stepType === 'exercise' ? (
              <div className={styles.choices}>
                <button
                  type="button"
                  className={`${styles.choice} ${form[currentStep.id] === true ? styles.choiceSelected : ''}`}
                  onClick={() => selectValue(currentStep.id, true, true)}
                >
                  <span className={styles.choiceLabel}>{currentStep.yesLabel}</span>
                  <span className={styles.choiceCheck} aria-hidden>
                    <Check size={12} strokeWidth={3} />
                  </span>
                </button>
                <button
                  type="button"
                  className={`${styles.choice} ${form[currentStep.id] === false ? styles.choiceSelected : ''}`}
                  onClick={() => selectValue(currentStep.id, false, true)}
                >
                  <span className={styles.choiceLabel}>{currentStep.noLabel}</span>
                  <span className={styles.choiceCheck} aria-hidden>
                    <Check size={12} strokeWidth={3} />
                  </span>
                </button>
              </div>
            ) : null}

            {stepType === 'scale' ? (
              <div className={styles.stars} role="group" aria-label={currentStep.question}>
                {scaleRange.map((n) => (
                  <button
                    key={n}
                    type="button"
                    className={`${styles.star} ${(Number(form[currentStep.id]) || 0) >= n ? styles.starFilled : ''}`}
                    aria-label={`${n} ${n === 1 ? 'estrela' : 'estrelas'}`}
                    aria-pressed={(Number(form[currentStep.id]) || 0) >= n}
                    onClick={() => selectScale(n)}
                  >
                    ★
                  </button>
                ))}
              </div>
            ) : null}

            {stepType === 'choice' ? (
              <div className={styles.choices}>
                {choiceOptions.map((option) => (
                  <button
                    key={option.value}
                    type="button"
                    className={`${styles.choice} ${form[currentStep.id] === option.value ? styles.choiceSelected : ''}`}
                    onClick={() => selectValue(currentStep.id, option.value, true)}
                  >
                    <span className={styles.choiceLabel}>{option.label}</span>
                    <span className={styles.choiceCheck} aria-hidden>
                      <Check size={12} strokeWidth={3} />
                    </span>
                  </button>
                ))}
              </div>
            ) : null}

            {stepType === 'text' ? (
              <div className={styles.text}>
                <div className={styles.textField}>
                  <textarea
                    ref={textRef}
                    rows={1}
                    className={styles.textarea}
                    placeholder={currentStep.placeholder}
                    value={String(form[currentStep.id] ?? '')}
                    onChange={(e) => {
                      setForm((prev) => ({ ...prev, [currentStep.id]: e.target.value }))
                      resizeTextAnswer()
                    }}
                  />
                </div>
                <button
                  type="button"
                  className={styles.submit}
                  disabled={submitActionDisabled}
                  onClick={handleOk}
                >
                  {saving ? <Loader2 className={styles.spin} size={12} aria-hidden /> : null}
                  <span>{okLabel}</span>
                </button>
              </div>
            ) : null}
          </div>
        </section>
      </main>

      {stepIndex > 0 || showFootOkButton ? (
        <footer
          className={`${styles.foot} ${stepIndex > 0 && showFootOkButton ? styles.footSplit : ''}`}
        >
          {stepIndex > 0 ? (
            <button
              type="button"
              className={styles.back}
              aria-label="Voltar"
              onClick={prevStep}
            >
              <ChevronUp size={14} aria-hidden />
              <span>Voltar</span>
            </button>
          ) : null}

          {showFootOkButton ? (
            <div className={styles.footOk}>
              <button
                type="button"
                className={styles.ok}
                disabled={submitActionDisabled}
                aria-label={okLabel}
                onClick={handleOk}
              >
                {saving ? (
                  <Loader2 className={styles.spin} size={16} aria-hidden />
                ) : !isLastStep ? (
                  <ArrowRight size={16} aria-hidden />
                ) : (
                  <Check size={16} aria-hidden />
                )}
              </button>
              <span className={styles.okHint}>{okHint}</span>
            </div>
          ) : null}
        </footer>
      ) : null}

      {preview && isLastStep && canAdvance ? (
        <p className={styles.previewNote}>Fim da prévia — no app o paciente envia aqui.</p>
      ) : null}

      {error ? <p className={styles.error}>{error}</p> : null}
    </div>
  )
}

// frontend/components/checkin/CheckinTypeformFlow.vue
<template>
  <div class="typeform-checkin">
    <div
      class="typeform-progress"
      role="progressbar"
      :aria-valuenow="progressPct"
      aria-valuemin="0"
      aria-valuemax="100"
    >
      <div class="typeform-progress-fill" :style="{ width: `${progressPct}%` }" />
    </div>

    <header class="typeform-top">
      <button
        v-if="stepIndex > 0"
        type="button"
        class="typeform-back"
        aria-label="Voltar"
        @click="prevStep"
      >
        <ChevronUp aria-hidden="true" />
      </button>
      <span v-else class="typeform-back-spacer" aria-hidden="true" />
      <span class="typeform-counter">{{ stepIndex + 1 }} / {{ flowSteps.length }}</span>
    </header>

    <main class="typeform-main">
      <Transition name="typeform-slide" mode="out-in">
        <section :key="currentStep.id" class="typeform-step">
          <p class="typeform-kicker">{{ currentStep.label }}</p>
          <h1 class="typeform-question">{{ currentStep.question }}</h1>
          <p v-if="currentStep.hint" class="typeform-hint">{{ currentStep.hint }}</p>

          <div class="typeform-answer">
            <CheckinFoodMoodPicker
              v-if="stepType === 'food'"
              :model-value="form[currentStep.id]"
              @update:model-value="(v) => selectValue(currentStep.id, v, true)"
            />

            <div v-else-if="stepType === 'water'" class="typeform-water">
              <div class="typeform-water-control">
                <button
                  type="button"
                  class="typeform-water-btn"
                  aria-label="Remover 0,25 litro"
                  @click="adjustWater(-WATER_STEP_L)"
                >
                  −
                </button>
                <div class="typeform-water-value">
                  <strong>{{ formatWaterLiters(form[currentStep.id]) }}</strong>
                  <span>{{ waterUnitLabel }}</span>
                </div>
                <button
                  type="button"
                  class="typeform-water-btn"
                  aria-label="Adicionar 0,25 litro"
                  @click="adjustWater(WATER_STEP_L)"
                >
                  +
                </button>
              </div>
              <p class="typeform-water-hint">+0,25 L por toque</p>
            </div>

            <div v-else-if="stepType === 'exercise'" class="typeform-choices">
              <button
                type="button"
                class="typeform-choice"
                :class="{ 'typeform-choice--selected': form[currentStep.id] === true }"
                @click="selectValue(currentStep.id, true, true)"
              >
                <span class="typeform-choice-label">Sim, pratiquei hoje</span>
              </button>
              <button
                type="button"
                class="typeform-choice"
                :class="{ 'typeform-choice--selected': form[currentStep.id] === false }"
                @click="selectValue(currentStep.id, false, true)"
              >
                <span class="typeform-choice-label">Não pratiquei hoje</span>
              </button>
            </div>

            <div
              v-else-if="stepType === 'scale'"
              class="typeform-stars"
              role="group"
              :aria-label="currentStep.label"
            >
              <button
                v-for="n in scaleMax"
                :key="n"
                type="button"
                class="typeform-star"
                :class="{ 'typeform-star--filled': (form[currentStep.id] || 0) >= n }"
                :aria-label="`${n} ${n === 1 ? 'estrela' : 'estrelas'}`"
                :aria-pressed="(form[currentStep.id] || 0) >= n"
                @click="selectScale(n)"
              >
                ★
              </button>
            </div>

            <div v-else-if="stepType === 'choice'" class="typeform-choices">
              <button
                v-for="option in choiceOptions"
                :key="option.value"
                type="button"
                class="typeform-choice"
                :class="{ 'typeform-choice--selected': form[currentStep.id] === option.value }"
                @click="selectValue(currentStep.id, option.value, true)"
              >
                <span class="typeform-choice-label">{{ option.label }}</span>
              </button>
            </div>

            <div v-else class="typeform-text">
              <textarea
                v-model="form[currentStep.id]"
                rows="4"
                class="typeform-textarea"
                :placeholder="currentStep.hint || 'Digite sua resposta...'"
              />
            </div>
          </div>
        </section>
      </Transition>
    </main>

    <footer v-if="showOkButton" class="typeform-foot">
      <button
        type="button"
        class="typeform-ok"
        :disabled="!canAdvance || saving"
        :aria-label="okLabel"
        @click="handleOk"
      >
        <ArrowRight v-if="!isLastStep && !saving" aria-hidden="true" />
        <Check v-else-if="!saving" aria-hidden="true" />
      </button>
      <span class="typeform-ok-hint">{{ okHint }}</span>
    </footer>

    <p v-if="error" class="typeform-error">{{ error }}</p>
    <NuxtLink v-if="showHistoryLink && stepIndex === 0" to="/check-in/historico" class="typeform-history-link">
      Ver histórico
    </NuxtLink>
  </div>
</template>

<script setup>
import { ArrowRight, Check, ChevronUp } from 'lucide-vue-next'
import { CHECKIN_DEFAULT_STEPS } from '~/utils/checkin-default-steps'

const props = defineProps({
  steps: { type: Array, default: () => CHECKIN_DEFAULT_STEPS },
  saving: { type: Boolean, default: false },
  error: { type: String, default: '' },
  showHistoryLink: { type: Boolean, default: false },
})

const emit = defineEmits(['submit'])

const WATER_STEP_L = 0.25
const WATER_MAX_L = 5
const WATER_DEFAULT_L = 2

const form = reactive({})
const stepIndex = ref(0)

const flowSteps = computed(() => {
  const list = props.steps?.length ? props.steps : CHECKIN_DEFAULT_STEPS
  return list.map((step, index) => ({
    id: step.id || `step_${index + 1}`,
    type: step.type || step.id || 'text',
    label: step.label || `Pergunta ${index + 1}`,
    question: step.question || '',
    hint: step.hint || '',
    min: step.min ?? 1,
    max: step.max ?? 5,
    options: step.options,
  }))
})

const currentStep = computed(() => flowSteps.value[stepIndex.value] || flowSteps.value[0])
const stepType = computed(() => currentStep.value.type)
const isLastStep = computed(() => stepIndex.value === flowSteps.value.length - 1)
const progressPct = computed(() => Math.round(((stepIndex.value + 1) / flowSteps.value.length) * 100))
const scaleMax = computed(() => Math.max(1, Number(currentStep.value.max) || 5))

const choiceOptions = computed(() => {
  const raw = currentStep.value.options
  if (!Array.isArray(raw)) return []
  return raw.map((item, index) => {
    if (typeof item === 'string') return { value: item, label: item }
    const value = item?.value ?? item?.label ?? `opt_${index}`
    return { value, label: item?.label ?? String(value) }
  })
})

const showOkButton = computed(() => stepType.value === 'water' || stepType.value === 'text')

const canAdvance = computed(() => {
  const id = currentStep.value.id
  const type = stepType.value
  const value = form[id]
  if (type === 'food' || type === 'exercise' || type === 'scale' || type === 'choice') {
    return value != null
  }
  if (type === 'water') return Number(value) >= 0
  if (type === 'text') return String(value || '').trim().length > 0
  return false
})

const okLabel = computed(() => {
  if (props.saving) return 'Salvando'
  if (isLastStep.value) return 'Concluir check-in'
  return 'Continuar'
})

const okHint = computed(() => (props.saving ? 'Salvando...' : 'continuar'))

const waterUnitLabel = computed(() => {
  const value = Number(form[currentStep.value.id] ?? 0)
  return value === 1 ? 'litro' : 'litros'
})

function formatWaterLiters(value) {
  const liters = Number(value ?? 0)
  if (!Number.isFinite(liters)) return '0'
  const rounded = Math.round(liters * 100) / 100
  if (rounded % 1 === 0) return String(rounded)
  return rounded.toFixed(2).replace(/0$/, '').replace(/\.$/, '').replace('.', ',')
}

function adjustWater(delta) {
  const id = currentStep.value.id
  const next = Math.round(((form[id] || 0) + delta) * 100) / 100
  form[id] = Math.max(0, Math.min(WATER_MAX_L, next))
}

function initForm() {
  for (const key of Object.keys(form)) delete form[key]
  for (const step of flowSteps.value) {
    form[step.id] = step.type === 'water' ? WATER_DEFAULT_L : null
  }
  stepIndex.value = 0
}

watch(flowSteps, initForm, { immediate: true, deep: true })

function buildPayload() {
  const payload = {}
  for (const step of flowSteps.value) {
    payload[step.id] = form[step.id]
  }
  return payload
}

function prevStep() {
  if (stepIndex.value > 0) stepIndex.value -= 1
}

function nextStep() {
  if (!canAdvance.value || stepIndex.value >= flowSteps.value.length - 1) return
  stepIndex.value += 1
}

function submitNow() {
  if (props.saving) return
  emit('submit', buildPayload())
}

function handleOk() {
  if (!canAdvance.value || props.saving) return
  if (isLastStep.value) {
    submitNow()
    return
  }
  nextStep()
}

function autoAdvance() {
  if (props.saving || isLastStep.value || !canAdvance.value) return
  window.setTimeout(() => {
    if (canAdvance.value) nextStep()
  }, 320)
}

function selectValue(id, value, advance = false) {
  form[id] = value
  if (isLastStep.value) {
    window.setTimeout(submitNow, 320)
    return
  }
  if (advance) autoAdvance()
}

function selectScale(value) {
  form[currentStep.value.id] = value
  if (isLastStep.value) {
    window.setTimeout(submitNow, 320)
    return
  }
  autoAdvance()
}

function onKeydown(event) {
  if (event.key !== 'Enter') return
  if (!showOkButton.value) return
  event.preventDefault()
  handleOk()
}

onMounted(() => {
  window.addEventListener('keydown', onKeydown)
})

onUnmounted(() => {
  window.removeEventListener('keydown', onKeydown)
})
</script>

<style scoped>
.typeform-checkin {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
  padding: 0 1.35rem 0.5rem;
  box-sizing: border-box;
  background: var(--cf-bg);
}

.typeform-progress {
  position: sticky;
  top: 0;
  z-index: 10;
  height: 3px;
  margin: 0 -1.35rem;
  background: var(--cf-track);
}

.typeform-progress-fill {
  height: 100%;
  background: var(--cf-pink);
  transition: width 0.35s ease;
}

.typeform-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1.1rem 0 0.25rem;
}

.typeform-back-spacer {
  width: 2rem;
  height: 2rem;
}

.typeform-back {
  width: 2rem;
  height: 2rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border: none;
  border-radius: 6px;
  background: transparent;
  color: var(--cf-text-muted);
  cursor: pointer;
}

.typeform-back :deep(svg) {
  width: 1.15rem;
  height: 1.15rem;
}

.typeform-back:active {
  background: var(--cf-track);
}

.typeform-counter {
  font-size: 0.75rem;
  font-weight: 600;
  color: var(--cf-text-muted);
  font-variant-numeric: tabular-nums;
}

.typeform-main {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem 0;
  min-height: 0;
  overflow-y: auto;
}

.typeform-step {
  width: 100%;
  max-width: 26rem;
  margin-inline: auto;
  text-align: center;
}

.typeform-kicker {
  margin: 0 0 0.85rem;
  font-size: 0.8rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--cf-pink-dark);
  text-align: center;
}

.typeform-question {
  margin: 0 0 1rem;
  font-size: clamp(1.65rem, 6vw, 2rem);
  font-weight: 700;
  letter-spacing: -0.03em;
  line-height: 1.18;
  color: var(--cf-text);
  text-wrap: balance;
  text-align: center;
}

.typeform-hint {
  margin: 0 auto 2rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.55;
  color: var(--cf-text-muted);
  max-width: 32ch;
  text-align: center;
}

.typeform-choices {
  display: flex;
  flex-direction: column;
  gap: 0.55rem;
}

.typeform-choice {
  display: flex;
  align-items: center;
  gap: 0.85rem;
  width: 100%;
  min-height: 3.25rem;
  padding: 0.85rem 1rem;
  border: 1.5px solid var(--cf-border);
  border-radius: 4px;
  background: var(--cf-surface);
  font-family: inherit;
  text-align: left;
  cursor: pointer;
  transition: border-color 0.15s ease, background 0.15s ease, transform 0.12s ease;
}

.typeform-choice:active {
  transform: scale(0.995);
}

.typeform-choice--selected {
  border-color: var(--cf-pink);
  background: var(--cf-pink-soft);
}

.typeform-choice-label {
  font-size: 0.92rem;
  font-weight: 600;
  letter-spacing: 0.01em;
  color: var(--cf-text);
  line-height: 1.35;
}

.typeform-stars {
  display: flex;
  justify-content: center;
  gap: 0.55rem;
  padding: 0.35rem 0;
}

.typeform-star {
  border: none;
  background: none;
  font-size: 2.35rem;
  color: var(--cf-track);
  cursor: pointer;
  line-height: 1;
  padding: 0.2rem;
  transition: transform 0.12s ease, color 0.12s ease;
}

.typeform-star--filled {
  color: #e8a54b;
}

.typeform-star:active {
  transform: scale(0.9);
}

.typeform-water-control {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 1.5rem;
  padding: 0.25rem 0;
}

.typeform-water-value {
  text-align: center;
  min-width: 5rem;
}

.typeform-water-btn {
  width: 2.75rem;
  height: 2.75rem;
  border: 1.5px solid var(--cf-border);
  border-radius: 4px;
  background: var(--cf-surface);
  color: var(--cf-text);
  font-size: 1.35rem;
  font-weight: 500;
  font-family: inherit;
  cursor: pointer;
}

.typeform-water-btn:active {
  background: var(--cf-track);
}

.typeform-water-value strong {
  display: block;
  font-size: 3rem;
  font-weight: 700;
  letter-spacing: -0.04em;
  color: var(--cf-text);
  line-height: 1;
  font-variant-numeric: tabular-nums;
}

.typeform-water-value span {
  display: block;
  margin-top: 0.35rem;
  font-size: 0.9rem;
  font-weight: 500;
  color: var(--cf-text-muted);
}

.typeform-water-hint {
  margin: 0.75rem 0 0;
  font-size: 0.78rem;
  color: var(--cf-text-muted);
}

.typeform-textarea {
  width: 100%;
  min-height: 7rem;
  padding: 0.85rem 1rem;
  border: 1.5px solid var(--cf-border);
  border-radius: 8px;
  background: var(--cf-surface);
  font-family: inherit;
  font-size: 1rem;
  line-height: 1.5;
  color: var(--cf-text);
  resize: vertical;
  box-sizing: border-box;
}

.typeform-foot {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 0.65rem;
  width: 100%;
  padding: 0.75rem 0 0.25rem;
  margin-top: auto;
}

.typeform-ok-hint {
  order: 2;
  font-size: 0.82rem;
  font-weight: 500;
  color: var(--cf-text-muted);
}

.typeform-ok {
  order: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 3rem;
  height: 3rem;
  border: none;
  border-radius: 4px;
  background: var(--cf-pink);
  color: #fff;
  cursor: pointer;
  transition: background 0.15s ease, opacity 0.15s ease, transform 0.12s ease;
}

.typeform-ok :deep(svg) {
  width: 1.25rem;
  height: 1.25rem;
  stroke-width: 2.5;
}

.typeform-ok:active:not(:disabled) {
  transform: scale(0.96);
  background: var(--cf-pink-dark);
}

.typeform-ok:disabled {
  opacity: 0.35;
  cursor: not-allowed;
}

.typeform-error {
  margin: 0.5rem 0 0;
  font-size: 0.82rem;
  font-weight: 600;
  color: var(--pa-red, #d64545);
  text-align: center;
}

.typeform-history-link {
  display: block;
  margin-top: 0.75rem;
  text-align: center;
  font-size: 0.78rem;
  font-weight: 600;
  color: var(--cf-pink-dark);
  text-decoration: none;
}

.typeform-slide-enter-active,
.typeform-slide-leave-active {
  transition: opacity 0.28s ease, transform 0.28s ease;
}

.typeform-slide-enter-from {
  opacity: 0;
  transform: translateY(18px);
}

.typeform-slide-leave-to {
  opacity: 0;
  transform: translateY(-12px);
}

@media (prefers-reduced-motion: reduce) {
  .typeform-progress-fill,
  .typeform-slide-enter-active,
  .typeform-slide-leave-active,
  .typeform-choice,
  .typeform-star,
  .typeform-ok {
    transition: none;
  }

  .typeform-slide-enter-from,
  .typeform-slide-leave-to,
  .typeform-choice:active,
  .typeform-star:active,
  .typeform-ok:active:not(:disabled) {
    transform: none;
  }
}
</style>
