// frontend/pages/setup/nutricionista.vue
<template>
  <div class="setup-page">
    <main class="setup-card">
      <h1>Setup Inicial do Nutricionista</h1>
      <p class="subtitle">
        Esta página funciona apenas uma vez. Após o primeiro cadastro, ela será desativada.
      </p>

      <div v-if="loadingStatus" class="status">Verificando status do setup...</div>

      <div v-else-if="!setupEnabled" class="status status--disabled">
        Setup já utilizado. Já existe um nutricionista cadastrado.
      </div>

      <form v-else class="form" @submit.prevent="handleSubmit">
        <label class="field">
          <span>Nome</span>
          <input v-model="form.name" type="text" required placeholder="Nome do nutricionista" />
        </label>

        <label class="field">
          <span>E-mail</span>
          <input v-model="form.email" type="email" required placeholder="nutri@exemplo.com" />
        </label>

        <label class="field">
          <span>Senha</span>
          <input v-model="form.password" type="password" required minlength="6" placeholder="Mínimo 6 caracteres" />
        </label>

        <label class="field">
          <span>Chave de setup</span>
          <input
            v-model="setupKey"
            type="text"
            placeholder="Obrigatória em produção"
          />
        </label>

        <button class="btn" type="submit" :disabled="submitting">
          {{ submitting ? "Criando..." : "Criar nutricionista" }}
        </button>

        <p v-if="error" class="message message--error">{{ error }}</p>
        <p v-if="success" class="message message--success">{{ success }}</p>
      </form>
    </main>
  </div>
</template>

<script setup>
definePageMeta({
  layout: false
})

const config = useRuntimeConfig()
const apiBase = `${config.public.apiBase}/auth`

const loadingStatus = ref(true)
const setupEnabled = ref(false)
const submitting = ref(false)
const error = ref("")
const success = ref("")
const setupKey = ref("")

const form = reactive({
  name: "",
  email: "",
  password: ""
})

const fetchStatus = async () => {
  loadingStatus.value = true
  try {
    const response = await $fetch(`${apiBase}/setup/nutricionista/status`)
    setupEnabled.value = Boolean(response?.enabled)
  } catch (err) {
    error.value = "Não foi possível validar o status do setup."
    setupEnabled.value = false
  } finally {
    loadingStatus.value = false
  }
}

const handleSubmit = async () => {
  error.value = ""
  success.value = ""
  submitting.value = true

  try {
    await $fetch(`${apiBase}/setup/nutricionista`, {
      method: "POST",
      body: form,
      headers: setupKey.value ? { "x-setup-key": setupKey.value } : undefined
    })

    success.value = "Nutricionista criado com sucesso. Esta página foi desativada."
    setupEnabled.value = false
    form.name = ""
    form.email = ""
    form.password = ""
  } catch (err: any) {
    error.value = err?.data?.message || "Não foi possível criar o nutricionista."
  } finally {
    submitting.value = false
  }
}

onMounted(fetchStatus)
</script>

<style scoped>
.setup-page {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 24px;
  background: #f4f7f5;
}

.setup-card {
  width: 100%;
  max-width: 460px;
  background: #fff;
  border: 1px solid #e4e9e6;
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 8px 30px rgba(12, 30, 20, 0.08);
}

h1 {
  margin: 0 0 8px;
  color: #163225;
  font-size: 1.4rem;
}

.subtitle {
  margin: 0 0 20px;
  color: #4d5e55;
  font-size: 0.95rem;
}

.form {
  display: grid;
  gap: 12px;
}

.field {
  display: grid;
  gap: 6px;
}

.field span {
  font-size: 0.88rem;
  color: #2c4337;
  font-weight: 600;
}

.field input {
  width: 100%;
  border: 1px solid #d5ddd8;
  border-radius: 10px;
  padding: 10px 12px;
  font-size: 0.95rem;
  color: #1b2a23;
  outline: none;
}

.field input:focus {
  border-color: #2e6749;
  box-shadow: 0 0 0 3px rgba(46, 103, 73, 0.12);
}

.btn {
  margin-top: 4px;
  border: none;
  border-radius: 10px;
  padding: 11px 12px;
  background: #2e6749;
  color: #fff;
  font-weight: 700;
  cursor: pointer;
}

.btn:disabled {
  opacity: 0.65;
  cursor: not-allowed;
}

.status {
  padding: 12px;
  border-radius: 10px;
  background: #eef3f0;
  color: #2f4a3d;
}

.status--disabled {
  background: #f5efef;
  color: #6f2a2a;
}

.message {
  margin: 2px 0 0;
  font-size: 0.9rem;
}

.message--error {
  color: #b23333;
}

.message--success {
  color: #2e6749;
}
</style>

// frontend/app/(auth)/setup/nutricionista/page.tsx
'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { ApiError } from '@/lib/api'
import {
  createSetupNutricionista,
  fetchSetupNutricionistaStatus,
} from '@/lib/auth-password'
import styles from './setup.module.scss'

export default function SetupNutricionistaPage() {
  const [loadingStatus, setLoadingStatus] = useState(true)
  const [setupEnabled, setSetupEnabled] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [setupKey, setSetupKey] = useState('')

  useEffect(() => {
    let alive = true
    ;(async () => {
      setLoadingStatus(true)
      try {
        const response = await fetchSetupNutricionistaStatus()
        if (!alive) return
        setSetupEnabled(Boolean(response?.enabled))
      } catch {
        if (!alive) return
        setError('Não foi possível validar o status do setup.')
        setSetupEnabled(false)
      } finally {
        if (alive) setLoadingStatus(false)
      }
    })()
    return () => {
      alive = false
    }
  }, [])

  async function onSubmit(e: FormEvent) {
    e.preventDefault()
    setError('')
    setSuccess('')
    setSubmitting(true)

    try {
      await createSetupNutricionista(
        { name: name.trim(), email: email.trim(), password },
        setupKey.trim() || undefined,
      )
      setSuccess('Nutricionista criado com sucesso. Esta página foi desativada.')
      setSetupEnabled(false)
      setName('')
      setEmail('')
      setPassword('')
      setSetupKey('')
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message || 'Não foi possível criar o nutricionista.')
      } else {
        setError(
          err instanceof Error ? err.message : 'Não foi possível criar o nutricionista.',
        )
      }
    } finally {
      setSubmitting(false)
    }
  }

  const formDisabled = !setupEnabled || submitting || Boolean(success)

  return (
    <div className={styles.page}>
      <main className={styles.card}>
        <h1 className={styles.title}>Setup Inicial do Nutricionista</h1>
        <p className={styles.subtitle}>
          Esta página funciona apenas uma vez. Após o primeiro cadastro, ela será desativada.
        </p>

        {loadingStatus ? <div className={styles.status}>Verificando status do setup...</div> : null}

        {!loadingStatus && !setupEnabled && !success ? (
          <div className={styles.statusDisabled}>
            Setup já utilizado. Já existe um nutricionista cadastrado.
          </div>
        ) : null}

        {!loadingStatus && (setupEnabled || success) ? (
          <form className={styles.form} onSubmit={onSubmit}>
            <label className={styles.field}>
              <span>Nome</span>
              <input
                type="text"
                required
                placeholder="Nome do nutricionista"
                value={name}
                onChange={(e) => setName(e.target.value)}
                disabled={formDisabled}
              />
            </label>

            <label className={styles.field}>
              <span>E-mail</span>
              <input
                type="email"
                required
                placeholder="nutri@exemplo.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                disabled={formDisabled}
              />
            </label>

            <label className={styles.field}>
              <span>Senha</span>
              <input
                type="password"
                required
                minLength={6}
                placeholder="Mínimo 6 caracteres"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={formDisabled}
              />
            </label>

            <label className={styles.field}>
              <span>Chave de setup</span>
              <input
                type="text"
                placeholder="Obrigatória em produção"
                value={setupKey}
                onChange={(e) => setSetupKey(e.target.value)}
                disabled={formDisabled}
              />
            </label>

            <button className={styles.btn} type="submit" disabled={formDisabled || !setupEnabled}>
              {submitting ? 'Criando...' : 'Criar nutricionista'}
            </button>

            {error ? <p className={styles.messageError}>{error}</p> : null}
            {success ? <p className={styles.messageSuccess}>{success}</p> : null}
          </form>
        ) : null}

        {!loadingStatus && error && !setupEnabled && !success ? (
          <p className={styles.messageError}>{error}</p>
        ) : null}

        <p className={styles.loginLink}>
          <Link href="/login">Ir para o login</Link>
        </p>
      </main>
    </div>
  )
}
