// frontend/app/(admin)/comunidade/page.tsx
'use client'

import { useCallback, useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { X } from 'lucide-react'
import { CommunityFeed, type CommunityTab, type PostTypeChip } from '@/components/community/CommunityFeed'
import { ApiError } from '@/lib/api'
import { getCachedUser } from '@/lib/auth'
import {
  addPostComment,
  createCommunityPost,
  deleteCommunityPost,
  fetchCommunityPosts,
  formatCommunityDistance,
  togglePostLike,
  type CommunityPost,
} from '@/lib/community'
import styles from './comunidade.module.scss'

export default function ComunidadePage() {
  const [posts, setPosts] = useState<CommunityPost[]>([])
  const [newPostContent, setNewPostContent] = useState('')
  const [loading, setLoading] = useState(false)
  const [expandedComments, setExpandedComments] = useState<string[]>([])
  const [openMenuPostId, setOpenMenuPostId] = useState<string | null>(null)
  const [likingPostId, setLikingPostId] = useState<string | null>(null)
  const [activeTab, setActiveTab] = useState<CommunityTab>('feed')
  const [activePostType, setActivePostType] = useState<PostTypeChip>('achievement')
  const [selectedImage, setSelectedImage] = useState<File | null>(null)
  const [previewUrl, setPreviewUrl] = useState('')
  const [lightboxUrl, setLightboxUrl] = useState('')
  const [userId, setUserId] = useState('')
  const [userInitial, setUserInitial] = useState('N')
  const [error, setError] = useState('')

  const loadPosts = useCallback(async () => {
    try {
      const data = await fetchCommunityPosts()
      setPosts(data)
      setError('')
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Erro ao carregar posts.')
    }
  }, [])

  useEffect(() => {
    const user = getCachedUser()
    if (user) {
      setUserId(user.id)
      setUserInitial((user.name?.trim().charAt(0) || 'N').toUpperCase())
    } else {
      try {
        setUserId(localStorage.getItem('user_id') || '')
        const name = localStorage.getItem('user_name') || ''
        setUserInitial((name.trim().charAt(0) || 'N').toUpperCase())
      } catch {
        /* ignore */
      }
    }
    void loadPosts()
  }, [loadPosts])

  useEffect(() => {
    function closeMenu() {
      setOpenMenuPostId(null)
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        setLightboxUrl('')
        document.body.style.overflow = ''
        setOpenMenuPostId(null)
      }
    }
    document.addEventListener('click', closeMenu)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('click', closeMenu)
      document.removeEventListener('keydown', onKey)
      document.body.style.overflow = ''
    }
  }, [])

  useEffect(() => {
    return () => {
      if (previewUrl) URL.revokeObjectURL(previewUrl)
    }
  }, [previewUrl])

  function clearPostImage() {
    setSelectedImage(null)
    if (previewUrl) URL.revokeObjectURL(previewUrl)
    setPreviewUrl('')
  }

  function onPostImageSelect(file: File | null) {
    if (!file) return
    if (!file.type.startsWith('image/')) {
      alert('Selecione uma imagem (JPG, PNG, WEBP ou GIF).')
      return
    }
    if (file.size > 8 * 1024 * 1024) {
      alert('A imagem deve ter no máximo 8MB.')
      return
    }
    if (previewUrl) URL.revokeObjectURL(previewUrl)
    setSelectedImage(file)
    setPreviewUrl(URL.createObjectURL(file))
  }

  async function handleCreatePost() {
    if (!newPostContent.trim() && !selectedImage) return
    setLoading(true)
    try {
      await createCommunityPost(newPostContent.trim(), selectedImage)
      setNewPostContent('')
      clearPostImage()
      await loadPosts()
    } catch (err) {
      alert(err instanceof ApiError ? err.message : 'Erro ao publicar post.')
    } finally {
      setLoading(false)
    }
  }

  async function handleToggleLike(post: CommunityPost) {
    if (likingPostId === post.id) return
    setLikingPostId(post.id)
    try {
      const result = await togglePostLike(post.id)
      setPosts((prev) =>
        prev.map((p) =>
          p.id === post.id ? { ...p, likes: result.likes, likedByMe: result.likedByMe } : p,
        ),
      )
    } catch (err) {
      alert(err instanceof ApiError ? err.message : 'Erro ao curtir publicação.')
    } finally {
      setLikingPostId(null)
    }
  }

  async function handleAddComment(post: CommunityPost) {
    const content = post.newComment?.trim()
    if (!content) return
    try {
      await addPostComment(post.id, content)
      setPosts((prev) =>
        prev.map((p) => (p.id === post.id ? { ...p, newComment: '' } : p)),
      )
      setExpandedComments((prev) => (prev.includes(post.id) ? prev : [...prev, post.id]))
      await loadPosts()
    } catch (err) {
      alert(err instanceof ApiError ? err.message : 'Erro ao adicionar comentário.')
    }
  }

  async function handleDeletePost(id: string) {
    setOpenMenuPostId(null)
    if (!window.confirm('Deseja excluir esta publicação? Esta ação não pode ser desfeita.')) return
    try {
      await deleteCommunityPost(id)
      setExpandedComments((prev) => prev.filter((postId) => postId !== id))
      await loadPosts()
    } catch (err) {
      alert(err instanceof ApiError ? err.message : 'Erro ao excluir publicação.')
    }
  }

  function toggleComments(id: string) {
    setExpandedComments((prev) => {
      if (prev.includes(id)) return prev.filter((x) => x !== id)
      queueMicrotask(() => document.getElementById(`comment-input-${id}`)?.focus())
      return [...prev, id]
    })
  }

  async function copyPost(post: CommunityPost) {
    setOpenMenuPostId(null)
    if (!post.content) return
    try {
      await navigator.clipboard.writeText(post.content)
    } catch {
      /* ignore */
    }
  }

  function openLightbox(url: string) {
    setLightboxUrl(url)
    document.body.style.overflow = 'hidden'
  }

  function closeLightbox() {
    setLightboxUrl('')
    document.body.style.overflow = ''
  }

  return (
    <div className={styles.page}>
      <header className="admin-shell-header">
        <div>
          <h1>Comunidade</h1>
          <p>Compartilhe novidades, conquistas e interaja com os pacientes.</p>
        </div>
      </header>

      {error ? <p className={styles.error}>{error}</p> : null}

      <CommunityFeed
        isNutri
        posts={posts}
        activeTab={activeTab}
        activePostType={activePostType}
        newPostContent={newPostContent}
        loading={loading}
        postImagePreviewUrl={previewUrl}
        expandedComments={expandedComments}
        openMenuPostId={openMenuPostId}
        likingPostId={likingPostId}
        userInitial={userInitial}
        userId={userId}
        formatDistance={formatCommunityDistance}
        onActiveTabChange={setActiveTab}
        onActivePostTypeChange={setActivePostType}
        onNewPostContentChange={setNewPostContent}
        onCreatePost={() => void handleCreatePost()}
        onPostImageSelect={onPostImageSelect}
        onClearPostImage={clearPostImage}
        onToggleLike={(post) => void handleToggleLike(post)}
        onToggleComments={toggleComments}
        onAddComment={(post) => void handleAddComment(post)}
        onCommentChange={(postId, value) =>
          setPosts((prev) =>
            prev.map((p) => (p.id === postId ? { ...p, newComment: value } : p)),
          )
        }
        onDeletePost={(id) => void handleDeletePost(id)}
        onTogglePostMenu={(id) => setOpenMenuPostId((cur) => (cur === id ? null : id))}
        onCopyPost={(post) => void copyPost(post)}
        onOpenLightbox={openLightbox}
      />

      {lightboxUrl && typeof document !== 'undefined'
        ? createPortal(
            <div
              className={styles.lightbox}
              role="dialog"
              aria-modal="true"
              aria-label="Visualização da imagem"
              onClick={closeLightbox}
            >
              <button
                type="button"
                className={styles.lightboxClose}
                aria-label="Fechar"
                onClick={closeLightbox}
              >
                <X size={20} aria-hidden />
              </button>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={lightboxUrl}
                alt="Imagem ampliada"
                className={styles.lightboxImg}
                onClick={(e) => e.stopPropagation()}
              />
            </div>,
            document.body,
          )
        : null}
    </div>
  )
}

// cliente/pages/comunidade.vue
<template>
  <div v-if="isPatientApp" class="patient-page comm-page">
    <PatientHeader title="Comunidade" :has-notifications="true">
      <template #actions>
        <button type="button" class="comm-header-btn" aria-label="Buscar">
          <Search class="comm-header-icon" />
        </button>
      </template>
    </PatientHeader>

    <CommunityFeed
      v-model:active-tab="activeTab"
      v-model:active-post-type="activePostType"
      v-model:new-post-content="newPostContent"
      :is-nutri="isNutri"
      :posts="posts"
      :loading="loading"
      :post-image-preview-url="postImagePreviewUrl"
      :expanded-comments="expandedComments"
      :open-menu-post-id="openMenuPostId"
      :liking-post-id="likingPostId"
      :user-initial="userInitial"
      :user-id="userId"
      :format-distance="formatDistance"
      @create-post="handleCreatePost"
      @post-image-select="handlePostImageSelect"
      @clear-post-image="clearPostImage"
      @toggle-like="handleToggleLike"
      @toggle-comments="toggleComments"
      @add-comment="handleAddComment"
      @delete-post="handleDeletePost"
      @toggle-post-menu="togglePostMenu"
      @copy-post="copyPostContent"
      @open-lightbox="openImageLightbox"
    />
  </div>

  <NuxtLayout v-else name="dashboard">
    <div class="comm-web-shell admin-shell">
      <CommunityFeed
        v-model:active-tab="activeTab"
        v-model:active-post-type="activePostType"
        v-model:new-post-content="newPostContent"
        :is-nutri="isNutri"
        :posts="posts"
        :loading="loading"
        :post-image-preview-url="postImagePreviewUrl"
        :expanded-comments="expandedComments"
        :open-menu-post-id="openMenuPostId"
        :liking-post-id="likingPostId"
        :user-initial="userInitial"
        :user-id="userId"
        :format-distance="formatDistance"
        @create-post="handleCreatePost"
        @post-image-select="handlePostImageSelect"
        @clear-post-image="clearPostImage"
        @toggle-like="handleToggleLike"
        @toggle-comments="toggleComments"
        @add-comment="handleAddComment"
        @delete-post="handleDeletePost"
        @toggle-post-menu="togglePostMenu"
        @copy-post="copyPostContent"
        @open-lightbox="openImageLightbox"
      />
    </div>
  </NuxtLayout>

  <Teleport to="body">
    <div
      v-if="lightboxImageUrl"
      class="comm-image-lightbox"
      role="dialog"
      aria-modal="true"
      aria-label="Visualização da imagem"
      @click.self="closeImageLightbox"
    >
      <button type="button" class="comm-image-lightbox-close" aria-label="Fechar" @click="closeImageLightbox">
        <X class="comm-image-lightbox-close-icon" />
      </button>
      <img :src="lightboxImageUrl" alt="Imagem ampliada" class="comm-image-lightbox-img" />
    </div>
  </Teleport>
</template>

<script setup>
import { Search, X } from 'lucide-vue-next'

const config = useRuntimeConfig()
const isPatientApp = computed(() => Boolean(config.public.mobileApp))
const apiBase = config.public.apiBase

const posts = ref([])
const newPostContent = ref('')
const loading = ref(false)
const expandedComments = ref([])
const openMenuPostId = ref(null)
const likingPostId = ref(null)
const isNutri = ref(false)
const userId = ref('')
const activeTab = ref('feed')
const activePostType = ref('achievement')
const selectedPostImageFile = ref(null)
const postImagePreviewUrl = ref('')
const lightboxImageUrl = ref('')

const { userInitials } = usePatientApp()
const userInitial = computed(() => userInitials().charAt(0))

const authHeaders = () => {
  if (import.meta.server) return {}
  const token = localStorage.getItem('auth_token')
  return token ? { Authorization: `Bearer ${token}` } : {}
}

const fetchPosts = async () => {
  if (import.meta.server) return
  try {
    const data = await $fetch(`${apiBase}/posts`, {
      headers: authHeaders(),
    })
    posts.value = data.map((p) => ({
      ...p,
      likes: p.likes ?? p.likesCount ?? 0,
      likedByMe: Boolean(p.likedByMe),
      newComment: '',
    }))
  } catch (err) {
    console.error('Erro ao carregar posts:', err)
  }
}

const handleToggleLike = async (post) => {
  if (likingPostId.value === post.id) return
  likingPostId.value = post.id
  try {
    const result = await $fetch(`${apiBase}/posts/${post.id}/toggle-like`, {
      method: 'POST',
      headers: authHeaders(),
    })
    post.likes = result.likes
    post.likedByMe = result.likedByMe
  } catch (err) {
    alert(err.data?.message || 'Erro ao curtir publicação.')
  } finally {
    likingPostId.value = null
  }
}

const handleCreatePost = async () => {
  if (!newPostContent.value.trim() && !selectedPostImageFile.value) return
  loading.value = true
  try {
    const formData = new FormData()
    formData.append('content', newPostContent.value.trim())
    if (selectedPostImageFile.value) {
      formData.append('image', selectedPostImageFile.value)
    }
    await $fetch(`${apiBase}/posts`, {
      method: 'POST',
      headers: authHeaders(),
      body: formData,
    })
    newPostContent.value = ''
    clearPostImage()
    fetchPosts()
  } catch (err) {
    alert(err.data?.message || 'Erro ao publicar post.')
  } finally {
    loading.value = false
  }
}

const handlePostImageSelect = (event) => {
  const file = event.target.files?.[0]
  if (!file) return

  if (!file.type.startsWith('image/')) {
    alert('Selecione uma imagem (JPG, PNG, WEBP ou GIF).')
    event.target.value = ''
    return
  }

  if (file.size > 8 * 1024 * 1024) {
    alert('A imagem deve ter no máximo 8MB.')
    event.target.value = ''
    return
  }

  if (postImagePreviewUrl.value) {
    URL.revokeObjectURL(postImagePreviewUrl.value)
  }

  selectedPostImageFile.value = file
  postImagePreviewUrl.value = URL.createObjectURL(file)
}

const clearPostImage = () => {
  selectedPostImageFile.value = null
  if (postImagePreviewUrl.value) {
    URL.revokeObjectURL(postImagePreviewUrl.value)
    postImagePreviewUrl.value = ''
  }
}

const handleAddComment = async (post) => {
  if (!post.newComment?.trim()) return
  try {
    await $fetch(`${apiBase}/posts/${post.id}/comments`, {
      method: 'POST',
      headers: authHeaders(),
      body: { content: post.newComment },
    })
    post.newComment = ''
    if (!expandedComments.value.includes(post.id)) {
      expandedComments.value.push(post.id)
    }
    await fetchPosts()
  } catch (err) {
    alert(err.data?.message || 'Erro ao adicionar comentário.')
  }
}

const handleDeletePost = async (id) => {
  openMenuPostId.value = null
  const { confirm } = useConfirm()
  const ok = await confirm({
    title: 'Excluir publicação',
    message: 'Deseja excluir esta publicação? Esta ação não pode ser desfeita.',
    confirmLabel: 'Excluir',
    cancelLabel: 'Cancelar',
  })
  if (!ok) return
  try {
    await $fetch(`${apiBase}/posts/${id}`, {
      method: 'DELETE',
      headers: authHeaders(),
    })
    expandedComments.value = expandedComments.value.filter((postId) => postId !== id)
    await fetchPosts()
  } catch (err) {
    alert(err.data?.message || 'Erro ao excluir publicação.')
  }
}

const togglePostMenu = (postId) => {
  openMenuPostId.value = openMenuPostId.value === postId ? null : postId
}

const closePostMenu = () => {
  openMenuPostId.value = null
}

const copyPostContent = async (post) => {
  openMenuPostId.value = null
  if (!import.meta.client || !post.content) return
  try {
    await navigator.clipboard.writeText(post.content)
  } catch {
    /* ignore */
  }
}

const toggleComments = async (id) => {
  const index = expandedComments.value.indexOf(id)
  if (index > -1) {
    expandedComments.value.splice(index, 1)
    return
  }
  expandedComments.value.push(id)
  await nextTick()
  if (import.meta.client) {
    document.getElementById(`comment-input-${id}`)?.focus()
  }
}

const formatDistance = (date) => {
  const diffMs = Date.now() - new Date(date).getTime()
  const mins = Math.floor(diffMs / 60000)
  if (mins < 1) return 'agora'
  if (mins < 60) return `${mins} min`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours}h`
  const days = Math.floor(hours / 24)
  if (days < 7) return `${days}d`
  return new Date(date).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })
}

const openImageLightbox = (url) => {
  if (!url) return
  lightboxImageUrl.value = url
  if (import.meta.client) {
    document.body.style.overflow = 'hidden'
  }
}

const closeImageLightbox = () => {
  lightboxImageUrl.value = ''
  if (import.meta.client) {
    document.body.style.overflow = ''
  }
}

const handleLightboxKeydown = (event) => {
  if (event.key === 'Escape') closeImageLightbox()
}

onMounted(() => {
  if (import.meta.client) {
    isNutri.value = localStorage.getItem('user_role') === 'NUTRICIONISTA'
    userId.value = localStorage.getItem('user_id') || ''
    const { hydrateProfile } = usePatientApp()
    hydrateProfile()
    document.addEventListener('click', closePostMenu)
    document.addEventListener('keydown', handleLightboxKeydown)
  }
  fetchPosts()
})

onUnmounted(() => {
  if (import.meta.client) {
    document.removeEventListener('click', closePostMenu)
    document.removeEventListener('keydown', handleLightboxKeydown)
    document.body.style.overflow = ''
    clearPostImage()
  }
})
</script>

<style scoped>
.comm-page {
  padding-top: 0;
  padding-inline: 1.25rem;
  padding-bottom: var(--cf-tab-clearance);
}

.comm-header-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 2.75rem;
  height: 2.75rem;
  border: none;
  border-radius: 50%;
  background: transparent;
  cursor: pointer;
}

.comm-header-icon {
  width: 1.25rem;
  height: 1.25rem;
  color: var(--cf-text);
}

.comm-web-shell {
  width: 100%;
  max-width: 720px;
  margin: 0 auto;
}

.comm-image-lightbox {
  position: fixed;
  inset: 0;
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1.25rem;
  background: rgba(0, 0, 0, 0.92);
}

.comm-image-lightbox-close {
  position: absolute;
  top: 1rem;
  right: 1rem;
  width: 2.5rem;
  height: 2.5rem;
  border: none;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.12);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.comm-image-lightbox-close-icon {
  width: 1.25rem;
  height: 1.25rem;
}

.comm-image-lightbox-img {
  max-width: min(100%, 960px);
  max-height: calc(100vh - 2.5rem);
  object-fit: contain;
  border-radius: 8px;
  user-select: none;
}

@media (max-width: 768px) {
  .comm-web-shell.admin-shell {
    padding-left: 1rem;
    padding-right: 1rem;
  }
}

@media (min-width: 769px) {
  .comm-web-shell :deep(.comm-tabs) {
    margin-left: 0;
    margin-right: 0;
    padding-left: 0;
    padding-right: 0;
  }
}
</style>
