// frontend2/components/whatsapp/BusinessProfileModal.vue
<template>
  <div v-if="open" class="business-profile-modal-backdrop" @click.self="$emit('close')">
    <div class="business-profile-modal">
      <div class="business-profile-header">
        <h4>Dados do contato</h4>
        <button type="button" class="business-profile-close" @click="$emit('close')">✕</button>
      </div>

      <div v-if="loading" class="business-profile-loading">
        <Loader class="spin icon-small" />
        <span>Carregando dados da empresa...</span>
      </div>

      <div v-else-if="profile" class="business-profile-content">
        <div class="business-profile-hero">
          <div class="business-profile-cover"></div>
          <div class="business-profile-avatar">
            <img v-if="avatarUrl" :src="avatarUrl" :alt="displayName" />
            <User v-else class="icon-xl" />
          </div>
        </div>

        <div class="business-profile-identity">
          <h5>{{ displayName }}</h5>
          <p class="business-profile-phone">{{ phoneLabel }}</p>
          <p v-if="primaryCategory" class="business-profile-category">{{ primaryCategory }}</p>
          <p v-if="profile.description" class="business-profile-description">{{ profile.description }}</p>

          <div v-if="openingLabel || hoursLabel" class="business-profile-hours-block">
            <button
              type="button"
              class="business-profile-hours-toggle"
              @click="hoursExpanded = !hoursExpanded"
            >
              <span
                v-if="openingLabel"
                :class="['business-profile-open-state', profile.openNow === true ? 'is-open' : 'is-closed']"
              >
                {{ openingLabel }}
              </span>
              <span v-if="hoursLabel" class="business-profile-hours">{{ hoursLabel }}</span>
              <span class="business-profile-hours-caret">{{ hoursExpanded ? '▲' : '▼' }}</span>
            </button>
            <ul v-if="hoursExpanded && weeklySchedule.length" class="business-profile-hours-list">
              <li v-for="row in weeklySchedule" :key="row.dayKey" class="business-profile-hours-item">
                <span>{{ row.dayLabel }}</span>
                <span>{{ row.value }}</span>
              </li>
            </ul>
          </div>

          <p v-if="addressLine" class="business-profile-address">{{ addressLine }}</p>
        </div>

        <div class="business-profile-actions-row">
          <button type="button" class="business-profile-action-btn"><span>Catálogo</span></button>
          <button type="button" class="business-profile-action-btn"><span>Compartilhar</span></button>
        </div>

        <div class="business-profile-section">
          <h6>Conta comercial</h6>
          <p v-if="openingLabel"><strong>Status:</strong> {{ openingLabel }}</p>
          <p v-if="hoursLabel"><strong>Horário:</strong> {{ hoursLabel }}</p>
          <p v-if="addressLine"><strong>Endereço:</strong> {{ addressLine }}</p>
          <p v-if="emailLabel"><strong>Email:</strong> {{ emailLabel }}</p>
          <p v-if="primaryWebsite"><strong>Site:</strong> {{ primaryWebsite }}</p>
          <p v-if="categoriesLabel"><strong>Categoria:</strong> {{ categoriesLabel }}</p>
          <p v-if="profile.description"><strong>Descrição:</strong> {{ profile.description }}</p>
          <p
            v-if="!openingLabel && !hoursLabel && !addressLine && !emailLabel && !primaryWebsite && !categoriesLabel && !profile.description"
            class="business-profile-empty-note"
          >
            Esta conta não retornou detalhes comerciais adicionais na UAZAPI.
          </p>
        </div>

        <div v-if="catalog.length" class="business-profile-catalog">
          <h6>Catálogo</h6>
          <ul class="business-products-grid">
            <li v-for="product in catalog" :key="product.id || product.retailerId || product.name">
              <div class="business-product-row">
                <div class="business-product-main">
                  <div class="business-product-thumb">
                    <img v-if="product.imageUrl" :src="product.imageUrl" :alt="product.name || 'Produto'" />
                    <span v-else>Sem imagem</span>
                  </div>
                  <span class="business-product-name">{{ product.name || 'Produto sem nome' }}</span>
                </div>
              </div>
            </li>
          </ul>
        </div>

        <div class="business-profile-section business-profile-section-muted">
          <h6>Recado e número de telefone</h6>
          <p>{{ phoneLabel }}</p>
        </div>
      </div>

      <div v-else class="business-profile-empty">
        Não foi possível carregar o perfil comercial.
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { Loader, User } from 'lucide-vue-next'

const props = defineProps({
  open: { type: Boolean, default: false },
  loading: { type: Boolean, default: false },
  profile: { type: Object, default: null },
  catalog: { type: Array, default: () => [] },
  avatarUrl: { type: String, default: '' },
  displayName: { type: String, default: 'Empresa' },
  phoneLabel: { type: String, default: '' },
  primaryCategory: { type: String, default: '' },
  primaryWebsite: { type: String, default: '' },
  openingLabel: { type: String, default: '' },
  hoursLabel: { type: String, default: '' },
  weeklySchedule: { type: Array, default: () => [] },
  addressLine: { type: String, default: '' },
  emailLabel: { type: String, default: '' },
  categoriesLabel: { type: String, default: '' }
})

defineEmits(['close'])

const hoursExpanded = ref(false)
</script>

// frontend/components/whatsapp/contact/BusinessProfileModal.tsx
// @ts-nocheck
'use client'
import { useState } from 'react'
import { Loader2, User } from 'lucide-react'

interface BusinessProfile {
  description?: string
  openNow?: boolean
  address?: string
  email?: string
  websites?: string[]
  categories?: Array<{ displayValue?: string; id?: string }>
  businessHours?: Record<string, unknown>
}

interface Props {
  open: boolean
  loading?: boolean
  profile?: BusinessProfile | null
  catalog?: Array<{ id?: string; name?: string; imageUrl?: string }>
  avatarUrl?: string
  displayName?: string
  phoneLabel?: string
  primaryCategory?: string
  primaryWebsite?: string
  openingLabel?: string
  hoursLabel?: string
  weeklySchedule?: Array<{ dayLabel: string; value: string }>
  addressLine?: string
  emailLabel?: string
  categoriesLabel?: string
  onClose: () => void
}

export function BusinessProfileModal({
  open, loading, profile, catalog = [], avatarUrl, displayName = 'Empresa',
  phoneLabel = '', primaryCategory = '', primaryWebsite = '', openingLabel = '',
  hoursLabel = '', weeklySchedule = [], addressLine = '', emailLabel = '',
  categoriesLabel = '', onClose,
}: Props) {
  const [hoursExpanded, setHoursExpanded] = useState(false)

  if (!open) return null

  return (
    <div style={backdropStyle} onClick={onClose}>
      <div style={modalStyle} onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 20px', borderBottom: '1px solid #e9edef', background: '#f0f2f5' }}>
          <h4 style={{ margin: 0, fontSize: '1rem', fontWeight: 600, color: '#111b21' }}>Dados do contato</h4>
          <button onClick={onClose} style={closeBtnStyle}>✕</button>
        </div>

        {/* Content */}
        <div style={{ flex: 1, overflow: 'auto' }}>
          {loading && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: 32, color: '#667781' }}>
              <Loader2 size={24} style={{ animation: 'spin 1s linear infinite', color: '#008069' }} />
              <span>Carregando dados da empresa...</span>
            </div>
          )}

          {!loading && profile && (
            <>
              {/* Hero */}
              <div style={{ background: '#f0f2f5', height: 80, position: 'relative', marginBottom: 50 }}>
                <div style={{
                  position: 'absolute', bottom: -44, left: 24,
                  width: 88, height: 88, borderRadius: '50%', overflow: 'hidden',
                  background: '#dfe5e7', border: '3px solid #fff',
                  display: 'grid', placeItems: 'center',
                }}>
                  {avatarUrl
                    ? <img src={avatarUrl} alt={displayName} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    : <User size={40} style={{ color: '#54656f' }} />
                  }
                </div>
              </div>

              {/* Identity */}
              <div style={{ padding: '12px 24px 20px' }}>
                <h5 style={{ margin: '0 0 4px', fontSize: '1.25rem', fontWeight: 600, color: '#111b21' }}>{displayName}</h5>
                {phoneLabel && <p style={{ margin: '0 0 4px', color: '#667781', fontSize: '.9rem' }}>{phoneLabel}</p>}
                {primaryCategory && <p style={{ margin: '0 0 8px', color: '#008069', fontSize: '.88rem' }}>{primaryCategory}</p>}
                {profile.description && (
                  <p style={{ margin: '0 0 16px', color: '#111b21', fontSize: '.95rem', lineHeight: 1.45 }}>{profile.description}</p>
                )}

                {/* Hours */}
                {(openingLabel || hoursLabel) && (
                  <div style={{ marginBottom: 12 }}>
                    <button onClick={() => setHoursExpanded((v) => !v)} style={hoursBtnStyle}>
                      {openingLabel && (
                        <span style={{ color: profile.openNow ? '#25d366' : '#ea0038', fontWeight: 600, marginRight: 8 }}>
                          {openingLabel}
                        </span>
                      )}
                      {hoursLabel && <span style={{ color: '#667781' }}>{hoursLabel}</span>}
                      <span style={{ marginLeft: 'auto', color: '#8696a0' }}>{hoursExpanded ? '▲' : '▼'}</span>
                    </button>
                    {hoursExpanded && weeklySchedule.length > 0 && (
                      <ul style={{ margin: '8px 0 0', padding: 0, listStyle: 'none' }}>
                        {weeklySchedule.map((row) => (
                          <li key={row.dayLabel} style={{ display: 'flex', justifyContent: 'space-between', padding: '4px 0', fontSize: '.88rem', color: '#111b21', borderBottom: '1px solid #f0f2f5' }}>
                            <span>{row.dayLabel}</span>
                            <span style={{ color: '#667781' }}>{row.value}</span>
                          </li>
                        ))}
                      </ul>
                    )}
                  </div>
                )}

                {addressLine && <p style={{ margin: '0 0 6px', color: '#667781', fontSize: '.9rem' }}>📍 {addressLine}</p>}
              </div>

              {/* Details section */}
              <div style={{ padding: '0 24px 20px', borderTop: '8px solid #f0f2f5' }}>
                <h6 style={{ margin: '16px 0 10px', fontSize: '.88rem', fontWeight: 600, color: '#667781', textTransform: 'uppercase', letterSpacing: '.05em' }}>
                  Conta comercial
                </h6>
                {openingLabel && <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#111b21' }}><strong>Status:</strong> {openingLabel}</p>}
                {hoursLabel && <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#111b21' }}><strong>Horário:</strong> {hoursLabel}</p>}
                {addressLine && <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#111b21' }}><strong>Endereço:</strong> {addressLine}</p>}
                {emailLabel && <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#111b21' }}><strong>Email:</strong> {emailLabel}</p>}
                {primaryWebsite && <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#111b21' }}><strong>Site:</strong> <a href={primaryWebsite} target="_blank" rel="noopener noreferrer" style={{ color: '#008069' }}>{primaryWebsite}</a></p>}
                {categoriesLabel && <p style={{ margin: '0 0 4px', fontSize: '.9rem', color: '#111b21' }}><strong>Categoria:</strong> {categoriesLabel}</p>}
                {!openingLabel && !hoursLabel && !addressLine && !emailLabel && !primaryWebsite && !categoriesLabel && !profile.description && (
                  <p style={{ margin: 0, color: '#8696a0', fontSize: '.86rem' }}>
                    Esta conta não retornou detalhes comerciais adicionais.
                  </p>
                )}
              </div>

              {/* Catalog */}
              {catalog.length > 0 && (
                <div style={{ padding: '0 24px 20px', borderTop: '8px solid #f0f2f5' }}>
                  <h6 style={{ margin: '16px 0 10px', fontSize: '.88rem', fontWeight: 600, color: '#667781', textTransform: 'uppercase' }}>Catálogo</h6>
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(80px,1fr))', gap: 10 }}>
                    {catalog.map((product, i) => (
                      <div key={product.id || i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
                        <div style={{ width: 72, height: 72, borderRadius: 8, overflow: 'hidden', background: '#dfe5e7', display: 'grid', placeItems: 'center' }}>
                          {product.imageUrl
                            ? <img src={product.imageUrl} alt={product.name || ''} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                            : <span style={{ fontSize: '.72rem', color: '#667781' }}>Sem imagem</span>
                          }
                        </div>
                        <span style={{ fontSize: '.72rem', color: '#111b21', textAlign: 'center', lineHeight: 1.2 }}>
                          {product.name || 'Produto'}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </>
          )}

          {!loading && !profile && (
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 32, color: '#667781', fontSize: '.9rem' }}>
              Não foi possível carregar o perfil comercial.
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const backdropStyle: React.CSSProperties = {
  position: 'fixed', inset: 0, zIndex: 10080, background: 'rgba(17,27,33,.55)',
  display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, boxSizing: 'border-box',
}

const modalStyle: React.CSSProperties = {
  width: 'min(480px,calc(100vw - 32px))', maxHeight: 'min(88vh,700px)', background: '#fff',
  borderRadius: 12, overflow: 'hidden', boxShadow: '0 8px 32px rgba(11,20,26,.2)',
  display: 'flex', flexDirection: 'column',
}

const closeBtnStyle: React.CSSProperties = {
  border: 'none', background: 'transparent', color: '#54656f', cursor: 'pointer', fontSize: '1.15rem',
}

const hoursBtnStyle: React.CSSProperties = {
  width: '100%', border: 'none', background: '#f0f2f5', color: '#111b21',
  padding: '8px 12px', borderRadius: 8, fontSize: '.9rem', cursor: 'pointer',
  display: 'flex', alignItems: 'center', gap: 6, textAlign: 'left',
}
