// frontend2/components/whatsapp/SendContactsModal.vue
<template>
  <div v-if="open" class="send-contacts-backdrop" @click.self="$emit('cancel')">
    <section class="send-contacts-modal" role="dialog" aria-modal="true" aria-label="Enviar contatos">
      <header class="send-contacts-header">
        <button type="button" class="send-contacts-close" @click="$emit('cancel')">✕</button>
        <h3>Enviar contatos</h3>
      </header>

      <div class="send-contacts-search-wrap">
        <input
          :value="searchQuery"
          class="send-contacts-search"
          type="text"
          placeholder="Pesquisar nome ou número"
          :disabled="sending"
          @input="$emit('update:searchQuery', $event.target.value)"
        />
      </div>

      <p v-if="feedback" class="send-contacts-feedback">{{ feedback }}</p>

      <div class="send-contacts-list">
        <button
          v-for="contact in contacts"
          :key="contact.id"
          type="button"
          class="send-contacts-row"
          :disabled="sending"
          @click="$emit('toggle', contact.id)"
        >
          <span class="send-contacts-check" :class="{ 'is-selected': isSelected(contact.id) }" />
          <span class="send-contacts-avatar">
            <img v-if="contact.avatarUrl" :src="contact.avatarUrl" :alt="contact.name" />
            <span v-else>{{ contact.name.charAt(0).toUpperCase() }}</span>
          </span>
          <span class="send-contacts-main">
            <strong>{{ contact.name }}</strong>
            <small v-if="contact.subtitle">{{ contact.subtitle }}</small>
          </span>
        </button>
      </div>

      <footer class="send-contacts-footer">
        <button type="button" class="send-contacts-confirm" :disabled="sending || !selectedIds.length" @click="$emit('confirm')">
          {{ sending ? 'Enviando...' : 'Enviar contato(s)' }}
        </button>
      </footer>
    </section>
  </div>
</template>

<script setup>
const props = defineProps({
  open: { type: Boolean, default: false },
  sending: { type: Boolean, default: false },
  contacts: { type: Array, default: () => [] },
  selectedIds: { type: Array, default: () => [] },
  searchQuery: { type: String, default: '' },
  feedback: { type: String, default: '' }
})

defineEmits(['cancel', 'confirm', 'toggle', 'update:searchQuery'])

const isSelected = (id) => props.selectedIds.includes(id)
</script>

<style scoped>
.send-contacts-backdrop { position: fixed; inset: 0; background: rgba(0, 0, 0, 0.52); z-index: 10090; display: flex; justify-content: center; align-items: center; padding: 14px; }
.send-contacts-modal { width: min(430px, 100%); max-height: 88vh; border-radius: 16px; background: #111b21; color: #e9edef; display: flex; flex-direction: column; overflow: hidden; }
.send-contacts-header { display: flex; align-items: center; gap: 12px; padding: 14px 16px 8px; }
.send-contacts-header h3 { margin: 0; font-size: 1.35rem; font-weight: 700; }
.send-contacts-close { border: none; background: transparent; color: #e9edef; font-size: 1.1rem; cursor: pointer; }
.send-contacts-search-wrap { padding: 0 16px 10px; }
.send-contacts-search { width: 100%; height: 44px; border-radius: 999px; border: 2px solid #00a884; background: transparent; color: #e9edef; padding: 0 16px; font-size: 0.98rem; }
.send-contacts-feedback { margin: 0 16px 10px; color: #fca5a5; font-size: 0.85rem; }
.send-contacts-list { padding: 0 10px 10px; overflow: auto; display: flex; flex-direction: column; gap: 4px; }
.send-contacts-row { width: 100%; border: none; background: transparent; color: inherit; padding: 10px 8px; border-radius: 10px; display: flex; align-items: center; gap: 12px; text-align: left; cursor: pointer; }
.send-contacts-row:hover { background: rgba(255, 255, 255, 0.04); }
.send-contacts-check { width: 16px; height: 16px; border-radius: 4px; border: 2px solid rgba(233, 237, 237, 0.5); }
.send-contacts-check.is-selected { background: #00a884; border-color: #00a884; }
.send-contacts-avatar { width: 52px; height: 52px; border-radius: 999px; overflow: hidden; display: inline-flex; align-items: center; justify-content: center; background: #22303a; font-weight: 700; }
.send-contacts-avatar img { width: 100%; height: 100%; object-fit: cover; }
.send-contacts-main { display: inline-flex; flex-direction: column; min-width: 0; }
.send-contacts-main strong { font-size: 1rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.send-contacts-main small { color: #9ca3af; font-size: 0.8rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.send-contacts-footer { padding: 12px 16px 16px; }
.send-contacts-confirm { width: 100%; border: none; height: 44px; border-radius: 999px; background: #00a884; color: #052e16; font-weight: 700; cursor: pointer; }
.send-contacts-confirm:disabled { opacity: 0.55; cursor: not-allowed; }
</style>

// frontend/components/whatsapp/contact/SendContactsModal.tsx
// @ts-nocheck
'use client'
import { useState, useEffect } from 'react'
import type { WaContactForPicker } from '@/lib/whatsapp/groups'

interface Props {
  open: boolean
  contacts: WaContactForPicker[]
  sending?: boolean
  feedback?: string
  onCancel: () => void
  onConfirm: (selectedIds: string[]) => void
}

export function SendContactsModal({ open, contacts, sending, feedback, onCancel, onConfirm }: Props) {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedIds, setSelectedIds] = useState<string[]>([])

  useEffect(() => {
    if (!open) { setSearchQuery(''); setSelectedIds([]) }
  }, [open])

  if (!open) return null

  const filtered = contacts.filter((c) => {
    const q = searchQuery.toLowerCase()
    return !q || c.name.toLowerCase().includes(q) || c.number.includes(q)
  })

  const toggle = (id: string) => {
    setSelectedIds((prev) => prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id])
  }

  return (
    <div style={backdropStyle} onClick={onCancel}>
      <section
        role="dialog"
        aria-modal="true"
        aria-label="Enviar contatos"
        style={modalStyle}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <header style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '14px 16px', borderBottom: '1px solid #e9edef', background: '#f0f2f5' }}>
          <button onClick={onCancel} style={closeBtnStyle}>✕</button>
          <h3 style={{ margin: 0, fontSize: '1rem', fontWeight: 600, color: '#111b21', flex: 1, textAlign: 'center' }}>Enviar contatos</h3>
          <span style={{ width: 32 }} />
        </header>

        {/* Search */}
        <div style={{ padding: '10px 16px', borderBottom: '1px solid #e9edef' }}>
          <input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Pesquisar nome ou número"
            disabled={sending}
            style={searchInputStyle}
          />
        </div>

        {feedback && (
          <p style={{ margin: 0, padding: '8px 16px', color: '#b3261e', fontSize: '.86rem', background: '#fce8e6' }}>{feedback}</p>
        )}

        {/* List */}
        <div style={{ flex: 1, overflow: 'auto' }}>
          {filtered.map((c) => {
            const sel = selectedIds.includes(c.id)
            return (
              <button
                key={c.id}
                type="button"
                onClick={() => toggle(c.id)}
                disabled={sending}
                style={{
                  width: '100%', border: 'none', background: sel ? 'rgba(37,211,102,.06)' : 'transparent',
                  padding: '10px 16px', display: 'flex', alignItems: 'center', gap: 12,
                  textAlign: 'left', cursor: 'pointer', borderBottom: '1px solid #f0f2f5',
                }}
              >
                {/* Checkbox */}
                <span style={{
                  width: 20, height: 20, borderRadius: '50%', flexShrink: 0,
                  border: sel ? '6px solid #25d366' : '2px solid #b2bec3', background: '#fff',
                  display: 'inline-block',
                }} />

                {/* Avatar */}
                {c.avatarUrl ? (
                  <img src={c.avatarUrl} alt={c.name} style={{ width: 40, height: 40, borderRadius: '50%', objectFit: 'cover', flexShrink: 0 }} />
                ) : (
                  <div style={{ width: 40, height: 40, borderRadius: '50%', background: '#dfe5e7', display: 'grid', placeItems: 'center', color: '#54656f', fontWeight: 600, flexShrink: 0 }}>
                    {c.name.charAt(0).toUpperCase()}
                  </div>
                )}

                {/* Name */}
                <div style={{ minWidth: 0 }}>
                  <div style={{ fontWeight: 600, color: '#111b21', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{c.name}</div>
                  {c.number && <div style={{ fontSize: '.82rem', color: '#667781', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{c.number}</div>}
                </div>
              </button>
            )
          })}
          {filtered.length === 0 && (
            <p style={{ margin: 0, padding: '20px 16px', color: '#8696a0', fontSize: '.9rem', textAlign: 'center' }}>Nenhum contato encontrado.</p>
          )}
        </div>

        {/* Footer */}
        <footer style={{ padding: '12px 16px', borderTop: '1px solid #e9edef', background: '#f0f2f5' }}>
          <button
            onClick={() => onConfirm(selectedIds)}
            disabled={sending || selectedIds.length === 0}
            style={{
              width: '100%', height: 44, border: 'none', borderRadius: 10, fontWeight: 600,
              fontSize: '.95rem', cursor: 'pointer', background: '#25d366', color: '#04130a',
              opacity: (sending || selectedIds.length === 0) ? .55 : 1,
            }}
          >
            {sending ? 'Enviando...' : `Enviar contato${selectedIds.length > 1 ? 's' : ''}${selectedIds.length > 0 ? ` (${selectedIds.length})` : ''}`}
          </button>
        </footer>
      </section>
    </div>
  )
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const backdropStyle: React.CSSProperties = {
  position: 'fixed', inset: 0, zIndex: 10080, background: 'rgba(17,27,33,.55)',
  display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24, boxSizing: 'border-box',
}

const modalStyle: React.CSSProperties = {
  width: 'min(420px,calc(100vw - 32px))', maxHeight: 'min(88vh,640px)', background: '#fff',
  borderRadius: 12, overflow: 'hidden', boxShadow: '0 8px 32px rgba(11,20,26,.2)',
  display: 'flex', flexDirection: 'column',
}

const closeBtnStyle: React.CSSProperties = {
  border: 'none', background: 'transparent', color: '#54656f', cursor: 'pointer', fontSize: '1.15rem',
  width: 32, height: 32, display: 'grid', placeItems: 'center',
}

const searchInputStyle: React.CSSProperties = {
  width: '100%', height: 40, border: '1px solid #e9edef', borderRadius: 8,
  padding: '0 12px', outline: 'none', fontSize: '.9rem', color: '#111b21',
  background: '#fff', boxSizing: 'border-box',
}
